package b4a.example;


import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.B4AClass;
import anywheresoftware.b4a.BALayout;
import anywheresoftware.b4a.debug.*;

public class bargraph extends B4AClass.ImplB4AClass implements BA.SubDelegator{
    private static java.util.HashMap<String, java.lang.reflect.Method> htSubs;
    private void innerInitialize(BA _ba) throws Exception {
        if (ba == null) {
            ba = new anywheresoftware.b4a.ShellBA(_ba, this, htSubs, "b4a.example.bargraph");
            if (htSubs == null) {
                ba.loadHtSubs(this.getClass());
                htSubs = ba.htSubs;
            }
            
        }
        if (BA.isShellModeRuntimeCheck(ba)) 
			   this.getClass().getMethod("_class_globals", b4a.example.bargraph.class).invoke(this, new Object[] {null});
        else
            ba.raiseEvent2(null, true, "class_globals", false);
    }

 
    public void  innerInitializeHelper(anywheresoftware.b4a.BA _ba) throws Exception{
        innerInitialize(_ba);
    }
    public Object callSub(String sub, Object sender, Object[] args) throws Exception {
        return BA.SubDelegator.SubNotFound;
    }
public anywheresoftware.b4a.keywords.Common __c = null;
public anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[] _checkboxes = null;
public boolean[] _checkedsales = null;
public int[] _color = null;
public anywheresoftware.b4a.objects.PanelWrapper _legendpanel = null;
public anywheresoftware.b4a.objects.PanelWrapper _sortpanels = null;
public anywheresoftware.b4a.objects.PanelWrapper _radiopanel = null;
public anywheresoftware.b4a.objects.PanelWrapper _salespanels = null;
public anywheresoftware.b4a.objects.LabelWrapper _radiolabelsalestitles = null;
public anywheresoftware.b4a.objects.LabelWrapper _radiolabelsorttitles = null;
public anywheresoftware.b4a.objects.LabelWrapper _radiolabellegendtitles = null;
public anywheresoftware.b4a.objects.ActivityWrapper _active1 = null;
public anywheresoftware.b4a.objects.PanelWrapper _panel_l = null;
public int[] _sale_1 = null;
public int[] _sale_2 = null;
public int[] _sale_3 = null;
public String[] _product1 = null;
public String[] _legend1 = null;
public int _maxsales1 = 0;
public String _titlestring1 = "";
public int[] _comid1 = null;
public int _currentpage = 0;
public int _itemsperpage = 0;
public anywheresoftware.b4a.objects.ButtonWrapper _btnnext = null;
public anywheresoftware.b4a.objects.ButtonWrapper _btnback = null;
public anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sortbtn1 = null;
public anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sortbtn2 = null;
public anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _defbtn = null;
public anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sales1 = null;
public anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sales2 = null;
public anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sales3 = null;
public String _layout = "";
public boolean _isfirstinit = false;
public anywheresoftware.b4a.objects.PanelWrapper _sortmainpanel = null;
public anywheresoftware.b4a.objects.PanelWrapper _shownmainpanel = null;
public b4a.example.main _main = null;
public b4a.example.branch _branch = null;
public b4a.example.device _device = null;
public b4a.example.starter _starter = null;
public b4a.example.httputils2service _httputils2service = null;
public String  _initialize(b4a.example.bargraph __ref,anywheresoftware.b4a.BA _ba,anywheresoftware.b4a.objects.ActivityWrapper _active,anywheresoftware.b4a.objects.PanelWrapper _panel,int[] _sale1,int[] _sale2,int[] _sale3,String[] _product,String[] _legend,int _maxsales,String _titlestring,int[] _comid,String _layout1,anywheresoftware.b4a.objects.ButtonWrapper _nextbtn,anywheresoftware.b4a.objects.ButtonWrapper _backbtn,anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sortbtn,anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _btnsort2,anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _defaultbtn,anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sales1btn,anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sales2btn,anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sales3btn) throws Exception{
__ref = this;
innerInitialize(_ba);
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "initialize", false))
	 {return ((String) Debug.delegate(ba, "initialize", new Object[] {_ba,_active,_panel,_sale1,_sale2,_sale3,_product,_legend,_maxsales,_titlestring,_comid,_layout1,_nextbtn,_backbtn,_sortbtn,_btnsort2,_defaultbtn,_sales1btn,_sales2btn,_sales3btn}));}
anywheresoftware.b4a.objects.drawable.ColorDrawable _cd = null;
int _halfwidth = 0;
anywheresoftware.b4a.objects.PanelWrapper _borderpanel = null;
int _legendwidth = 0;
anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[] _tempcheckboxes = null;
boolean[] _tempcheckedsales = null;
int _i = 0;
anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper _chk = null;
anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper[] _radiobuttons = null;
String[] _radiotexts = null;
int _totalbuttons = 0;
int _buttonwidth = 0;
int _spacing = 0;
anywheresoftware.b4a.objects.drawable.ColorDrawable _cdnext = null;
anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper[] _saleslabels = null;
String[] _salestexts = null;
int _totallabels = 0;
int _labelwidth = 0;
anywheresoftware.b4a.objects.drawable.ColorDrawable _cdback = null;
RDebugUtils.currentLine=1310720;
 //BA.debugLineNum = 1310720;BA.debugLine="Public Sub Initialize(Active As Activity, panel As";
RDebugUtils.currentLine=1310721;
 //BA.debugLineNum = 1310721;BA.debugLine="If Active.IsInitialized = False Then";
if (_active.IsInitialized()==__c.False) { 
RDebugUtils.currentLine=1310722;
 //BA.debugLineNum = 1310722;BA.debugLine="Log(\"Error: Activity is not initialized\")";
__c.LogImpl("41310722","Error: Activity is not initialized",0);
RDebugUtils.currentLine=1310723;
 //BA.debugLineNum = 1310723;BA.debugLine="Return";
if (true) return "";
 };
RDebugUtils.currentLine=1310725;
 //BA.debugLineNum = 1310725;BA.debugLine="Active1 = Active";
__ref._active1 /*anywheresoftware.b4a.objects.ActivityWrapper*/  = _active;
RDebugUtils.currentLine=1310726;
 //BA.debugLineNum = 1310726;BA.debugLine="panel_l = panel";
__ref._panel_l /*anywheresoftware.b4a.objects.PanelWrapper*/  = _panel;
RDebugUtils.currentLine=1310727;
 //BA.debugLineNum = 1310727;BA.debugLine="sale_1 = sale1";
__ref._sale_1 /*int[]*/  = _sale1;
RDebugUtils.currentLine=1310728;
 //BA.debugLineNum = 1310728;BA.debugLine="sale_2 = sale2";
__ref._sale_2 /*int[]*/  = _sale2;
RDebugUtils.currentLine=1310729;
 //BA.debugLineNum = 1310729;BA.debugLine="sale_3 = sale3";
__ref._sale_3 /*int[]*/  = _sale3;
RDebugUtils.currentLine=1310730;
 //BA.debugLineNum = 1310730;BA.debugLine="product1 = product";
__ref._product1 /*String[]*/  = _product;
RDebugUtils.currentLine=1310731;
 //BA.debugLineNum = 1310731;BA.debugLine="legend1 = legend";
__ref._legend1 /*String[]*/  = _legend;
RDebugUtils.currentLine=1310732;
 //BA.debugLineNum = 1310732;BA.debugLine="maxSales1 = maxSales";
__ref._maxsales1 /*int*/  = _maxsales;
RDebugUtils.currentLine=1310733;
 //BA.debugLineNum = 1310733;BA.debugLine="titleString1 = TitleString";
__ref._titlestring1 /*String*/  = _titlestring;
RDebugUtils.currentLine=1310734;
 //BA.debugLineNum = 1310734;BA.debugLine="comId1 = comId";
__ref._comid1 /*int[]*/  = _comid;
RDebugUtils.currentLine=1310735;
 //BA.debugLineNum = 1310735;BA.debugLine="layout = layout1";
__ref._layout /*String*/  = _layout1;
RDebugUtils.currentLine=1310736;
 //BA.debugLineNum = 1310736;BA.debugLine="btnNext = NextBtn";
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/  = _nextbtn;
RDebugUtils.currentLine=1310737;
 //BA.debugLineNum = 1310737;BA.debugLine="btnBack = Backbtn";
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/  = _backbtn;
RDebugUtils.currentLine=1310738;
 //BA.debugLineNum = 1310738;BA.debugLine="sortBtn1 = sortBtn";
__ref._sortbtn1 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/  = _sortbtn;
RDebugUtils.currentLine=1310739;
 //BA.debugLineNum = 1310739;BA.debugLine="sortBtn2 = BtnSort2";
__ref._sortbtn2 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/  = _btnsort2;
RDebugUtils.currentLine=1310740;
 //BA.debugLineNum = 1310740;BA.debugLine="defBtn = Defaultbtn";
__ref._defbtn /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/  = _defaultbtn;
RDebugUtils.currentLine=1310741;
 //BA.debugLineNum = 1310741;BA.debugLine="sales1 = Sales1btn";
__ref._sales1 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/  = _sales1btn;
RDebugUtils.currentLine=1310742;
 //BA.debugLineNum = 1310742;BA.debugLine="sales2 = Sales2btn";
__ref._sales2 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/  = _sales2btn;
RDebugUtils.currentLine=1310743;
 //BA.debugLineNum = 1310743;BA.debugLine="sales3 = Sales3btn";
__ref._sales3 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/  = _sales3btn;
RDebugUtils.currentLine=1310745;
 //BA.debugLineNum = 1310745;BA.debugLine="Dim cd As ColorDrawable";
_cd = new anywheresoftware.b4a.objects.drawable.ColorDrawable();
RDebugUtils.currentLine=1310746;
 //BA.debugLineNum = 1310746;BA.debugLine="cd.Initialize2(Colors.White, 5dip, 1dip, Colors.B";
_cd.Initialize2(__c.Colors.White,__c.DipToCurrent((int) (5)),__c.DipToCurrent((int) (1)),__c.Colors.Black);
RDebugUtils.currentLine=1310749;
 //BA.debugLineNum = 1310749;BA.debugLine="If sale1.Length <> product.Length Or sale2.Length";
if (_sale1.length!=_product.length || _sale2.length!=_product.length || _sale3.length!=_product.length) { 
RDebugUtils.currentLine=1310750;
 //BA.debugLineNum = 1310750;BA.debugLine="Return";
if (true) return "";
 };
RDebugUtils.currentLine=1310752;
 //BA.debugLineNum = 1310752;BA.debugLine="Dim halfWidth As Int = panel.Width / 2";
_halfwidth = (int) (_panel.getWidth()/(double)2);
RDebugUtils.currentLine=1310754;
 //BA.debugLineNum = 1310754;BA.debugLine="legendPanel.Initialize(\"\")";
__ref._legendpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .Initialize(ba,"");
RDebugUtils.currentLine=1310755;
 //BA.debugLineNum = 1310755;BA.debugLine="legendPanel.Width = halfWidth";
__ref._legendpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .setWidth(_halfwidth);
RDebugUtils.currentLine=1310756;
 //BA.debugLineNum = 1310756;BA.debugLine="legendPanel.Height = 60dip";
__ref._legendpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .setHeight(__c.DipToCurrent((int) (60)));
RDebugUtils.currentLine=1310758;
 //BA.debugLineNum = 1310758;BA.debugLine="radioPanel.Initialize(\"\")";
__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .Initialize(ba,"");
RDebugUtils.currentLine=1310759;
 //BA.debugLineNum = 1310759;BA.debugLine="radioPanel.Width = halfWidth";
__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .setWidth(_halfwidth);
RDebugUtils.currentLine=1310760;
 //BA.debugLineNum = 1310760;BA.debugLine="radioPanel.Height = 30dip";
__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .setHeight(__c.DipToCurrent((int) (30)));
RDebugUtils.currentLine=1310762;
 //BA.debugLineNum = 1310762;BA.debugLine="radioPanel.Color = Colors.Transparent ' Keep it t";
__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .setColor(__c.Colors.Transparent);
RDebugUtils.currentLine=1310763;
 //BA.debugLineNum = 1310763;BA.debugLine="Dim borderPanel As Panel";
_borderpanel = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=1310764;
 //BA.debugLineNum = 1310764;BA.debugLine="borderPanel.Initialize(\"\")";
_borderpanel.Initialize(ba,"");
RDebugUtils.currentLine=1310765;
 //BA.debugLineNum = 1310765;BA.debugLine="borderPanel.Color = Colors.Black ' Border color";
_borderpanel.setColor(__c.Colors.Black);
RDebugUtils.currentLine=1310766;
 //BA.debugLineNum = 1310766;BA.debugLine="panel.AddView(borderPanel, radioPanel.Left, radio";
_panel.AddView((android.view.View)(_borderpanel.getObject()),__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getLeft(),__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getTop(),__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getWidth(),__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getHeight());
RDebugUtils.currentLine=1310767;
 //BA.debugLineNum = 1310767;BA.debugLine="panel.AddView(radioPanel, radioPanel.Left + 1dip,";
_panel.AddView((android.view.View)(__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getObject()),(int) (__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getLeft()+__c.DipToCurrent((int) (1))),(int) (__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getTop()+__c.DipToCurrent((int) (1))),(int) (__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getWidth()-__c.DipToCurrent((int) (2))),(int) (__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getHeight()-__c.DipToCurrent((int) (2))));
RDebugUtils.currentLine=1310769;
 //BA.debugLineNum = 1310769;BA.debugLine="Dim legendWidth As Int = (legendPanel.Width-20dip";
_legendwidth = (int) ((__ref._legendpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getWidth()-__c.DipToCurrent((int) (20)))/(double)_legend.length);
RDebugUtils.currentLine=1310770;
 //BA.debugLineNum = 1310770;BA.debugLine="checkBoxes = Array As CheckBox()";
__ref._checkboxes /*anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[]*/  = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[]{};
RDebugUtils.currentLine=1310771;
 //BA.debugLineNum = 1310771;BA.debugLine="checkedSales = Array As Boolean()";
__ref._checkedsales /*boolean[]*/  = new boolean[]{};
RDebugUtils.currentLine=1310773;
 //BA.debugLineNum = 1310773;BA.debugLine="Dim checkBoxes(legend.Length) As CheckBox";
_checkboxes = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[_legend.length];
{
int d0 = _checkboxes.length;
for (int i0 = 0;i0 < d0;i0++) {
_checkboxes[i0] = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper();
}
}
;
RDebugUtils.currentLine=1310774;
 //BA.debugLineNum = 1310774;BA.debugLine="Dim checkedSales(legend.Length) As Boolean";
_checkedsales = new boolean[_legend.length];
;
RDebugUtils.currentLine=1310775;
 //BA.debugLineNum = 1310775;BA.debugLine="If isFirstInit Then";
if (__ref._isfirstinit /*boolean*/ ) { 
RDebugUtils.currentLine=1310777;
 //BA.debugLineNum = 1310777;BA.debugLine="Dim tempCheckBoxes(legend.Length) As CheckBox";
_tempcheckboxes = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[_legend.length];
{
int d0 = _tempcheckboxes.length;
for (int i0 = 0;i0 < d0;i0++) {
_tempcheckboxes[i0] = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper();
}
}
;
RDebugUtils.currentLine=1310778;
 //BA.debugLineNum = 1310778;BA.debugLine="checkBoxes = tempCheckBoxes";
__ref._checkboxes /*anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[]*/  = _tempcheckboxes;
RDebugUtils.currentLine=1310779;
 //BA.debugLineNum = 1310779;BA.debugLine="Dim tempCheckedSales(legend.Length) As Boolean";
_tempcheckedsales = new boolean[_legend.length];
;
RDebugUtils.currentLine=1310780;
 //BA.debugLineNum = 1310780;BA.debugLine="checkedSales = tempCheckedSales";
__ref._checkedsales /*boolean[]*/  = _tempcheckedsales;
RDebugUtils.currentLine=1310783;
 //BA.debugLineNum = 1310783;BA.debugLine="For i = 0 To legend.Length - 1";
{
final int step52 = 1;
final int limit52 = (int) (_legend.length-1);
_i = (int) (0) ;
for (;_i <= limit52 ;_i = _i + step52 ) {
RDebugUtils.currentLine=1310784;
 //BA.debugLineNum = 1310784;BA.debugLine="Dim chk As CheckBox";
_chk = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper();
RDebugUtils.currentLine=1310785;
 //BA.debugLineNum = 1310785;BA.debugLine="chk.Initialize(\"chkChange\")";
_chk.Initialize(ba,"chkChange");
RDebugUtils.currentLine=1310786;
 //BA.debugLineNum = 1310786;BA.debugLine="chk.Text = legend(i)";
_chk.setText(BA.ObjectToCharSequence(_legend[_i]));
RDebugUtils.currentLine=1310787;
 //BA.debugLineNum = 1310787;BA.debugLine="chk.TextSize = 10";
_chk.setTextSize((float) (10));
RDebugUtils.currentLine=1310788;
 //BA.debugLineNum = 1310788;BA.debugLine="chk.Typeface = Typeface.MONOSPACE";
_chk.setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=1310789;
 //BA.debugLineNum = 1310789;BA.debugLine="chk.TextColor = color(i)";
_chk.setTextColor(__ref._color /*int[]*/ [_i]);
RDebugUtils.currentLine=1310790;
 //BA.debugLineNum = 1310790;BA.debugLine="chk.Gravity = Gravity.CENTER";
_chk.setGravity(__c.Gravity.CENTER);
RDebugUtils.currentLine=1310791;
 //BA.debugLineNum = 1310791;BA.debugLine="chk.Tag = i";
_chk.setTag((Object)(_i));
RDebugUtils.currentLine=1310792;
 //BA.debugLineNum = 1310792;BA.debugLine="chk.Checked = True  ' Default state";
_chk.setChecked(__c.True);
RDebugUtils.currentLine=1310793;
 //BA.debugLineNum = 1310793;BA.debugLine="checkedSales(i) = True";
__ref._checkedsales /*boolean[]*/ [_i] = __c.True;
RDebugUtils.currentLine=1310794;
 //BA.debugLineNum = 1310794;BA.debugLine="legendPanel.AddView(chk, (legendWidth * i), 10d";
__ref._legendpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(_chk.getObject()),(int) ((_legendwidth*_i)),__c.DipToCurrent((int) (10)),_legendwidth,(int) (__ref._legendpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getHeight()-__c.DipToCurrent((int) (20))));
RDebugUtils.currentLine=1310795;
 //BA.debugLineNum = 1310795;BA.debugLine="checkBoxes(i) = chk";
__ref._checkboxes /*anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[]*/ [_i] = _chk;
 }
};
RDebugUtils.currentLine=1310797;
 //BA.debugLineNum = 1310797;BA.debugLine="isFirstInit = False";
__ref._isfirstinit /*boolean*/  = __c.False;
 }else {
RDebugUtils.currentLine=1310800;
 //BA.debugLineNum = 1310800;BA.debugLine="For i = 0 To checkBoxes.Length - 1";
{
final int step68 = 1;
final int limit68 = (int) (__ref._checkboxes /*anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[]*/ .length-1);
_i = (int) (0) ;
for (;_i <= limit68 ;_i = _i + step68 ) {
RDebugUtils.currentLine=1310801;
 //BA.debugLineNum = 1310801;BA.debugLine="checkBoxes(i).Checked = checkedSales(i)";
__ref._checkboxes /*anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[]*/ [_i].setChecked(__ref._checkedsales /*boolean[]*/ [_i]);
 }
};
 };
RDebugUtils.currentLine=1310807;
 //BA.debugLineNum = 1310807;BA.debugLine="sortMainpanel.Initialize(\"\")";
__ref._sortmainpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .Initialize(ba,"");
RDebugUtils.currentLine=1310808;
 //BA.debugLineNum = 1310808;BA.debugLine="panel.AddView(sortMainpanel, 0dip, 5dip, halfWidt";
_panel.AddView((android.view.View)(__ref._sortmainpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getObject()),__c.DipToCurrent((int) (0)),__c.DipToCurrent((int) (5)),_halfwidth,__c.DipToCurrent((int) (120)));
RDebugUtils.currentLine=1310811;
 //BA.debugLineNum = 1310811;BA.debugLine="Dim radioButtons() As RadioButton = Array As Radi";
_radiobuttons = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper[]{__ref._sortbtn1 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/ ,__ref._sortbtn2 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/ ,__ref._defbtn /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/ };
RDebugUtils.currentLine=1310812;
 //BA.debugLineNum = 1310812;BA.debugLine="Dim radioTexts() As String = Array As String(\"ASC";
_radiotexts = new String[]{"ASC","DESC","DEFAULT"};
RDebugUtils.currentLine=1310814;
 //BA.debugLineNum = 1310814;BA.debugLine="sortPanels.Initialize(\"\")";
__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .Initialize(ba,"");
RDebugUtils.currentLine=1310815;
 //BA.debugLineNum = 1310815;BA.debugLine="sortPanels.Width = halfWidth";
__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .setWidth(_halfwidth);
RDebugUtils.currentLine=1310816;
 //BA.debugLineNum = 1310816;BA.debugLine="sortPanels.Height = 30dip";
__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .setHeight(__c.DipToCurrent((int) (30)));
RDebugUtils.currentLine=1310817;
 //BA.debugLineNum = 1310817;BA.debugLine="sortPanels.SendToBack";
__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .SendToBack();
RDebugUtils.currentLine=1310818;
 //BA.debugLineNum = 1310818;BA.debugLine="sortMainpanel.AddView(sortPanels, 10dip, 5dip, so";
__ref._sortmainpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .getObject()),__c.DipToCurrent((int) (10)),__c.DipToCurrent((int) (5)),(int) (__ref._sortmainpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getWidth()-__c.DipToCurrent((int) (20))),__c.DipToCurrent((int) (45)));
RDebugUtils.currentLine=1310819;
 //BA.debugLineNum = 1310819;BA.debugLine="sortPanels.Background = cd";
__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .setBackground((android.graphics.drawable.Drawable)(_cd.getObject()));
RDebugUtils.currentLine=1310821;
 //BA.debugLineNum = 1310821;BA.debugLine="radioLabelSalesTitles.Initialize(\"radioLabelSales";
__ref._radiolabelsalestitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .Initialize(ba,"radioLabelSalesTitles");
RDebugUtils.currentLine=1310822;
 //BA.debugLineNum = 1310822;BA.debugLine="radioLabelSalesTitles.Text = \"Base on\"";
__ref._radiolabelsalestitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setText(BA.ObjectToCharSequence("Base on"));
RDebugUtils.currentLine=1310823;
 //BA.debugLineNum = 1310823;BA.debugLine="radioLabelSalesTitles.TextSize = 12";
__ref._radiolabelsalestitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTextSize((float) (12));
RDebugUtils.currentLine=1310824;
 //BA.debugLineNum = 1310824;BA.debugLine="radioLabelSalesTitles.Gravity = Gravity.CENTER";
__ref._radiolabelsalestitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setGravity(__c.Gravity.CENTER);
RDebugUtils.currentLine=1310825;
 //BA.debugLineNum = 1310825;BA.debugLine="radioLabelSalesTitles.Typeface = Typeface.MONOSPA";
__ref._radiolabelsalestitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=1310826;
 //BA.debugLineNum = 1310826;BA.debugLine="radioLabelSalesTitles.TextColor = Colors.Black";
__ref._radiolabelsalestitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=1310827;
 //BA.debugLineNum = 1310827;BA.debugLine="radioLabelSalesTitles.Color = Colors.White";
__ref._radiolabelsalestitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setColor(__c.Colors.White);
RDebugUtils.currentLine=1310828;
 //BA.debugLineNum = 1310828;BA.debugLine="sortMainpanel.AddView(radioLabelSalesTitles, 15di";
__ref._sortmainpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(__ref._radiolabelsalestitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .getObject()),__c.DipToCurrent((int) (15)),(int) (-__c.DipToCurrent((int) (2))),__c.DipToCurrent((int) (60)),__c.DipToCurrent((int) (15)));
RDebugUtils.currentLine=1310830;
 //BA.debugLineNum = 1310830;BA.debugLine="If sortPanels.Width = 0 Then";
if (__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .getWidth()==0) { 
RDebugUtils.currentLine=1310831;
 //BA.debugLineNum = 1310831;BA.debugLine="sortPanels.Width = halfWidth ' Default width to";
__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .setWidth(_halfwidth);
 };
RDebugUtils.currentLine=1310834;
 //BA.debugLineNum = 1310834;BA.debugLine="Dim totalButtons As Int = radioButtons.Length";
_totalbuttons = _radiobuttons.length;
RDebugUtils.currentLine=1310835;
 //BA.debugLineNum = 1310835;BA.debugLine="Dim buttonWidth As Int = (sortPanels.Width - (tot";
_buttonwidth = (int) ((__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .getWidth()-(_totalbuttons*__c.DipToCurrent((int) (5))))/(double)_totalbuttons);
RDebugUtils.currentLine=1310836;
 //BA.debugLineNum = 1310836;BA.debugLine="Dim spacing As Int = 5dip ' Small gap between but";
_spacing = __c.DipToCurrent((int) (5));
RDebugUtils.currentLine=1310838;
 //BA.debugLineNum = 1310838;BA.debugLine="For i = 0 To totalButtons - 1";
{
final int step96 = 1;
final int limit96 = (int) (_totalbuttons-1);
_i = (int) (0) ;
for (;_i <= limit96 ;_i = _i + step96 ) {
RDebugUtils.currentLine=1310839;
 //BA.debugLineNum = 1310839;BA.debugLine="radioButtons(i).Text = radioTexts(i)";
_radiobuttons[_i].setText(BA.ObjectToCharSequence(_radiotexts[_i]));
RDebugUtils.currentLine=1310840;
 //BA.debugLineNum = 1310840;BA.debugLine="radioButtons(i).TextSize = 10";
_radiobuttons[_i].setTextSize((float) (10));
RDebugUtils.currentLine=1310841;
 //BA.debugLineNum = 1310841;BA.debugLine="radioButtons(i).Tag = radioTexts(i)";
_radiobuttons[_i].setTag((Object)(_radiotexts[_i]));
RDebugUtils.currentLine=1310842;
 //BA.debugLineNum = 1310842;BA.debugLine="radioButtons(i).Gravity = Gravity.CENTER_VERTICA";
_radiobuttons[_i].setGravity(__c.Gravity.CENTER_VERTICAL);
RDebugUtils.currentLine=1310843;
 //BA.debugLineNum = 1310843;BA.debugLine="radioButtons(i).Typeface = Typeface.MONOSPACE";
_radiobuttons[_i].setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=1310844;
 //BA.debugLineNum = 1310844;BA.debugLine="radioButtons(i).TextColor = Colors.Black";
_radiobuttons[_i].setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=1310847;
 //BA.debugLineNum = 1310847;BA.debugLine="Dim cdNext As ColorDrawable";
_cdnext = new anywheresoftware.b4a.objects.drawable.ColorDrawable();
RDebugUtils.currentLine=1310848;
 //BA.debugLineNum = 1310848;BA.debugLine="cdNext.Initialize2(Colors.RGB(128, 128, 128), 10";
_cdnext.Initialize2(__c.Colors.RGB((int) (128),(int) (128),(int) (128)),__c.DipToCurrent((int) (10)),__c.DipToCurrent((int) (2)),__c.Colors.Black);
RDebugUtils.currentLine=1310851;
 //BA.debugLineNum = 1310851;BA.debugLine="sortPanels.AddView(radioButtons(i), (i * (button";
__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(_radiobuttons[_i].getObject()),(int) ((_i*(_buttonwidth+_spacing))),__c.DipToCurrent((int) (10)),_buttonwidth,__c.DipToCurrent((int) (25)));
 }
};
RDebugUtils.currentLine=1310854;
 //BA.debugLineNum = 1310854;BA.debugLine="Dim salesLabels() As RadioButton = Array As Radio";
_saleslabels = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper[]{__ref._sales1 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/ ,__ref._sales2 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/ ,__ref._sales3 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/ };
RDebugUtils.currentLine=1310855;
 //BA.debugLineNum = 1310855;BA.debugLine="Dim salesTexts() As String = Array As String(\"1\",";
_salestexts = new String[]{"1","2","3"};
RDebugUtils.currentLine=1310857;
 //BA.debugLineNum = 1310857;BA.debugLine="salesPanels.Initialize(\"\")";
__ref._salespanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .Initialize(ba,"");
RDebugUtils.currentLine=1310858;
 //BA.debugLineNum = 1310858;BA.debugLine="salesPanels.Width = halfWidth ' Half of the main";
__ref._salespanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .setWidth(_halfwidth);
RDebugUtils.currentLine=1310859;
 //BA.debugLineNum = 1310859;BA.debugLine="salesPanels.Height = 30dip ' Height remains the s";
__ref._salespanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .setHeight(__c.DipToCurrent((int) (30)));
RDebugUtils.currentLine=1310860;
 //BA.debugLineNum = 1310860;BA.debugLine="sortMainpanel.AddView(salesPanels, 10dip, sortPan";
__ref._sortmainpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(__ref._salespanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .getObject()),__c.DipToCurrent((int) (10)),(int) (__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .getHeight()+__c.DipToCurrent((int) (20))),(int) (__ref._sortmainpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getWidth()-__c.DipToCurrent((int) (20))),__c.DipToCurrent((int) (45)));
RDebugUtils.currentLine=1310861;
 //BA.debugLineNum = 1310861;BA.debugLine="salesPanels.Background = cd";
__ref._salespanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .setBackground((android.graphics.drawable.Drawable)(_cd.getObject()));
RDebugUtils.currentLine=1310863;
 //BA.debugLineNum = 1310863;BA.debugLine="radioLabelSortTitles.Initialize(\"radioLabelSortTi";
__ref._radiolabelsorttitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .Initialize(ba,"radioLabelSortTitles");
RDebugUtils.currentLine=1310864;
 //BA.debugLineNum = 1310864;BA.debugLine="radioLabelSortTitles.Text = \"Sort By\"";
__ref._radiolabelsorttitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setText(BA.ObjectToCharSequence("Sort By"));
RDebugUtils.currentLine=1310865;
 //BA.debugLineNum = 1310865;BA.debugLine="radioLabelSortTitles.TextSize = 12";
__ref._radiolabelsorttitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTextSize((float) (12));
RDebugUtils.currentLine=1310866;
 //BA.debugLineNum = 1310866;BA.debugLine="radioLabelSortTitles.Typeface = Typeface.MONOSPAC";
__ref._radiolabelsorttitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=1310867;
 //BA.debugLineNum = 1310867;BA.debugLine="radioLabelSortTitles.Gravity = Gravity.CENTER";
__ref._radiolabelsorttitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setGravity(__c.Gravity.CENTER);
RDebugUtils.currentLine=1310868;
 //BA.debugLineNum = 1310868;BA.debugLine="radioLabelSortTitles.TextColor = Colors.Black";
__ref._radiolabelsorttitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=1310869;
 //BA.debugLineNum = 1310869;BA.debugLine="radioLabelSortTitles.Color = Colors.White";
__ref._radiolabelsorttitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setColor(__c.Colors.White);
RDebugUtils.currentLine=1310870;
 //BA.debugLineNum = 1310870;BA.debugLine="sortMainpanel.AddView(radioLabelSortTitles,15dip,";
__ref._sortmainpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(__ref._radiolabelsorttitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .getObject()),__c.DipToCurrent((int) (15)),(int) (__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .getHeight()+__c.DipToCurrent((int) (12))),__c.DipToCurrent((int) (60)),__c.DipToCurrent((int) (15)));
RDebugUtils.currentLine=1310872;
 //BA.debugLineNum = 1310872;BA.debugLine="Dim totalLabels As Int = salesLabels.Length";
_totallabels = _saleslabels.length;
RDebugUtils.currentLine=1310873;
 //BA.debugLineNum = 1310873;BA.debugLine="Dim labelWidth As Int = (salesPanels.Width - (tot";
_labelwidth = (int) ((__ref._salespanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .getWidth()-(_totallabels*__c.DipToCurrent((int) (5))))/(double)_totallabels);
RDebugUtils.currentLine=1310874;
 //BA.debugLineNum = 1310874;BA.debugLine="Dim spacing As Int = 5dip ' Small spacing between";
_spacing = __c.DipToCurrent((int) (5));
RDebugUtils.currentLine=1310876;
 //BA.debugLineNum = 1310876;BA.debugLine="For i = 0 To totalLabels - 1";
{
final int step125 = 1;
final int limit125 = (int) (_totallabels-1);
_i = (int) (0) ;
for (;_i <= limit125 ;_i = _i + step125 ) {
RDebugUtils.currentLine=1310877;
 //BA.debugLineNum = 1310877;BA.debugLine="salesLabels(i).Text = \"Sales\" & (i + 1)";
_saleslabels[_i].setText(BA.ObjectToCharSequence("Sales"+BA.NumberToString((_i+1))));
RDebugUtils.currentLine=1310878;
 //BA.debugLineNum = 1310878;BA.debugLine="salesLabels(i).TextSize = 10";
_saleslabels[_i].setTextSize((float) (10));
RDebugUtils.currentLine=1310879;
 //BA.debugLineNum = 1310879;BA.debugLine="salesLabels(i).Tag = salesTexts(i)";
_saleslabels[_i].setTag((Object)(_salestexts[_i]));
RDebugUtils.currentLine=1310880;
 //BA.debugLineNum = 1310880;BA.debugLine="salesLabels(i).Typeface = Typeface.MONOSPACE";
_saleslabels[_i].setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=1310881;
 //BA.debugLineNum = 1310881;BA.debugLine="salesLabels(i).TextColor = Colors.Black";
_saleslabels[_i].setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=1310883;
 //BA.debugLineNum = 1310883;BA.debugLine="Dim cdBack As ColorDrawable";
_cdback = new anywheresoftware.b4a.objects.drawable.ColorDrawable();
RDebugUtils.currentLine=1310884;
 //BA.debugLineNum = 1310884;BA.debugLine="cdBack.Initialize2(Colors.RGB(128, 128, 128), 10";
_cdback.Initialize2(__c.Colors.RGB((int) (128),(int) (128),(int) (128)),__c.DipToCurrent((int) (10)),__c.DipToCurrent((int) (2)),__c.Colors.Black);
RDebugUtils.currentLine=1310888;
 //BA.debugLineNum = 1310888;BA.debugLine="salesPanels.AddView(salesLabels(i), (i * (labelW";
__ref._salespanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(_saleslabels[_i].getObject()),(int) ((_i*(_labelwidth+_spacing))),__c.DipToCurrent((int) (10)),_labelwidth,__c.DipToCurrent((int) (20)));
 }
};
RDebugUtils.currentLine=1310894;
 //BA.debugLineNum = 1310894;BA.debugLine="End Sub";
return "";
}
public String  _updategraph(b4a.example.bargraph __ref) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "updategraph", false))
	 {return ((String) Debug.delegate(ba, "updategraph", null));}
RDebugUtils.currentLine=1441792;
 //BA.debugLineNum = 1441792;BA.debugLine="Public Sub UpdateGraph";
RDebugUtils.currentLine=1441793;
 //BA.debugLineNum = 1441793;BA.debugLine="DrawGraph(Active1, panel_l, sale_1, sale_2, sale_";
__ref._drawgraph /*String*/ (null,__ref._active1 /*anywheresoftware.b4a.objects.ActivityWrapper*/ ,__ref._panel_l /*anywheresoftware.b4a.objects.PanelWrapper*/ ,__ref._sale_1 /*int[]*/ ,__ref._sale_2 /*int[]*/ ,__ref._sale_3 /*int[]*/ ,__ref._product1 /*String[]*/ ,__ref._maxsales1 /*int*/ ,__ref._titlestring1 /*String*/ );
RDebugUtils.currentLine=1441794;
 //BA.debugLineNum = 1441794;BA.debugLine="End Sub";
return "";
}
public String  _setcurrentpage(b4a.example.bargraph __ref,int _page) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "setcurrentpage", false))
	 {return ((String) Debug.delegate(ba, "setcurrentpage", new Object[] {_page}));}
RDebugUtils.currentLine=1572864;
 //BA.debugLineNum = 1572864;BA.debugLine="Public Sub SetCurrentPage(page As Int)";
RDebugUtils.currentLine=1572865;
 //BA.debugLineNum = 1572865;BA.debugLine="currentPage = page";
__ref._currentpage /*int*/  = _page;
RDebugUtils.currentLine=1572866;
 //BA.debugLineNum = 1572866;BA.debugLine="UpdateGraph";
__ref._updategraph /*String*/ (null);
RDebugUtils.currentLine=1572867;
 //BA.debugLineNum = 1572867;BA.debugLine="End Sub";
return "";
}
public String  _chkchange_checkedchange(b4a.example.bargraph __ref,boolean _checked) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "chkchange_checkedchange", false))
	 {return ((String) Debug.delegate(ba, "chkchange_checkedchange", new Object[] {_checked}));}
anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper _chk = null;
int _index = 0;
int _checkedcount = 0;
int _i = 0;
RDebugUtils.currentLine=1835008;
 //BA.debugLineNum = 1835008;BA.debugLine="Sub chkChange_CheckedChange(Checked As Boolean)";
RDebugUtils.currentLine=1835009;
 //BA.debugLineNum = 1835009;BA.debugLine="If Sender Is CheckBox Then";
if (__c.Sender(ba) instanceof android.widget.CheckBox) { 
RDebugUtils.currentLine=1835010;
 //BA.debugLineNum = 1835010;BA.debugLine="Dim chk As CheckBox = Sender";
_chk = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper();
_chk = (anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper(), (android.widget.CheckBox)(__c.Sender(ba)));
RDebugUtils.currentLine=1835011;
 //BA.debugLineNum = 1835011;BA.debugLine="Dim index As Int = chk.Tag";
_index = (int)(BA.ObjectToNumber(_chk.getTag()));
RDebugUtils.currentLine=1835013;
 //BA.debugLineNum = 1835013;BA.debugLine="Dim checkedCount As Int = 0";
_checkedcount = (int) (0);
RDebugUtils.currentLine=1835014;
 //BA.debugLineNum = 1835014;BA.debugLine="For i = 0 To checkedSales.Length - 1";
{
final int step5 = 1;
final int limit5 = (int) (__ref._checkedsales /*boolean[]*/ .length-1);
_i = (int) (0) ;
for (;_i <= limit5 ;_i = _i + step5 ) {
RDebugUtils.currentLine=1835015;
 //BA.debugLineNum = 1835015;BA.debugLine="If checkedSales(i) = True Then checkedCount = c";
if (__ref._checkedsales /*boolean[]*/ [_i]==__c.True) { 
_checkedcount = (int) (_checkedcount+1);};
 }
};
RDebugUtils.currentLine=1835018;
 //BA.debugLineNum = 1835018;BA.debugLine="If Checked = False And checkedCount = 1 Then";
if (_checked==__c.False && _checkedcount==1) { 
RDebugUtils.currentLine=1835019;
 //BA.debugLineNum = 1835019;BA.debugLine="chk.Checked = True";
_chk.setChecked(__c.True);
RDebugUtils.currentLine=1835020;
 //BA.debugLineNum = 1835020;BA.debugLine="Return";
if (true) return "";
 };
RDebugUtils.currentLine=1835023;
 //BA.debugLineNum = 1835023;BA.debugLine="checkedSales(index) = Checked";
__ref._checkedsales /*boolean[]*/ [_index] = _checked;
RDebugUtils.currentLine=1835024;
 //BA.debugLineNum = 1835024;BA.debugLine="UpdateGraph ' Call DrawGraph without parameters";
__ref._updategraph /*String*/ (null);
 }else {
RDebugUtils.currentLine=1835026;
 //BA.debugLineNum = 1835026;BA.debugLine="Log(\"Error: Sender is not a CheckBox\")";
__c.LogImpl("41835026","Error: Sender is not a CheckBox",0);
 };
RDebugUtils.currentLine=1835028;
 //BA.debugLineNum = 1835028;BA.debugLine="End Sub";
return "";
}
public String  _class_globals(b4a.example.bargraph __ref) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
RDebugUtils.currentLine=1245184;
 //BA.debugLineNum = 1245184;BA.debugLine="Sub Class_Globals";
RDebugUtils.currentLine=1245185;
 //BA.debugLineNum = 1245185;BA.debugLine="Private checkBoxes() As CheckBox";
_checkboxes = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[(int) (0)];
{
int d0 = _checkboxes.length;
for (int i0 = 0;i0 < d0;i0++) {
_checkboxes[i0] = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper();
}
}
;
RDebugUtils.currentLine=1245186;
 //BA.debugLineNum = 1245186;BA.debugLine="Public checkedSales() As Boolean";
_checkedsales = new boolean[(int) (0)];
;
RDebugUtils.currentLine=1245187;
 //BA.debugLineNum = 1245187;BA.debugLine="Dim color() As Int = Array As Int(Colors.RGB(255,";
_color = new int[]{__c.Colors.RGB((int) (255),(int) (0),(int) (0)),__c.Colors.RGB((int) (200),(int) (20),(int) (20)),__c.Colors.RGB((int) (100),(int) (10),(int) (10))};
RDebugUtils.currentLine=1245188;
 //BA.debugLineNum = 1245188;BA.debugLine="Dim legendPanel As Panel";
_legendpanel = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=1245189;
 //BA.debugLineNum = 1245189;BA.debugLine="Dim sortPanels As Panel";
_sortpanels = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=1245190;
 //BA.debugLineNum = 1245190;BA.debugLine="Dim radioPanel As Panel";
_radiopanel = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=1245191;
 //BA.debugLineNum = 1245191;BA.debugLine="Dim salesPanels As Panel";
_salespanels = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=1245192;
 //BA.debugLineNum = 1245192;BA.debugLine="Dim radioLabelSalesTitles As Label";
_radiolabelsalestitles = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=1245193;
 //BA.debugLineNum = 1245193;BA.debugLine="Dim radioLabelSortTitles As Label";
_radiolabelsorttitles = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=1245194;
 //BA.debugLineNum = 1245194;BA.debugLine="Dim radioLabelLegendTitles As Label";
_radiolabellegendtitles = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=1245195;
 //BA.debugLineNum = 1245195;BA.debugLine="Dim Active1 As Activity";
_active1 = new anywheresoftware.b4a.objects.ActivityWrapper();
RDebugUtils.currentLine=1245196;
 //BA.debugLineNum = 1245196;BA.debugLine="Dim panel_l As Panel";
_panel_l = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=1245197;
 //BA.debugLineNum = 1245197;BA.debugLine="Dim sale_1() As Int";
_sale_1 = new int[(int) (0)];
;
RDebugUtils.currentLine=1245198;
 //BA.debugLineNum = 1245198;BA.debugLine="Dim sale_2() As Int";
_sale_2 = new int[(int) (0)];
;
RDebugUtils.currentLine=1245199;
 //BA.debugLineNum = 1245199;BA.debugLine="Dim sale_3() As Int";
_sale_3 = new int[(int) (0)];
;
RDebugUtils.currentLine=1245200;
 //BA.debugLineNum = 1245200;BA.debugLine="Dim product1() As String";
_product1 = new String[(int) (0)];
java.util.Arrays.fill(_product1,"");
RDebugUtils.currentLine=1245201;
 //BA.debugLineNum = 1245201;BA.debugLine="Dim legend1() As String";
_legend1 = new String[(int) (0)];
java.util.Arrays.fill(_legend1,"");
RDebugUtils.currentLine=1245202;
 //BA.debugLineNum = 1245202;BA.debugLine="Dim maxSales1 As Int = 0";
_maxsales1 = (int) (0);
RDebugUtils.currentLine=1245203;
 //BA.debugLineNum = 1245203;BA.debugLine="Dim titleString1 As String = \"\"";
_titlestring1 = "";
RDebugUtils.currentLine=1245204;
 //BA.debugLineNum = 1245204;BA.debugLine="Dim comId1() As Int";
_comid1 = new int[(int) (0)];
;
RDebugUtils.currentLine=1245205;
 //BA.debugLineNum = 1245205;BA.debugLine="Private currentPage As Int = 1";
_currentpage = (int) (1);
RDebugUtils.currentLine=1245206;
 //BA.debugLineNum = 1245206;BA.debugLine="Private itemsPerPage As Int = 5";
_itemsperpage = (int) (5);
RDebugUtils.currentLine=1245207;
 //BA.debugLineNum = 1245207;BA.debugLine="Public btnNext As Button";
_btnnext = new anywheresoftware.b4a.objects.ButtonWrapper();
RDebugUtils.currentLine=1245208;
 //BA.debugLineNum = 1245208;BA.debugLine="Public btnBack As Button";
_btnback = new anywheresoftware.b4a.objects.ButtonWrapper();
RDebugUtils.currentLine=1245209;
 //BA.debugLineNum = 1245209;BA.debugLine="Public sortBtn1 As RadioButton";
_sortbtn1 = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper();
RDebugUtils.currentLine=1245210;
 //BA.debugLineNum = 1245210;BA.debugLine="Public sortBtn2 As RadioButton";
_sortbtn2 = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper();
RDebugUtils.currentLine=1245211;
 //BA.debugLineNum = 1245211;BA.debugLine="Public defBtn As RadioButton";
_defbtn = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper();
RDebugUtils.currentLine=1245212;
 //BA.debugLineNum = 1245212;BA.debugLine="Public sales1 As RadioButton";
_sales1 = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper();
RDebugUtils.currentLine=1245213;
 //BA.debugLineNum = 1245213;BA.debugLine="Public sales2 As RadioButton";
_sales2 = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper();
RDebugUtils.currentLine=1245214;
 //BA.debugLineNum = 1245214;BA.debugLine="Public sales3 As RadioButton";
_sales3 = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper();
RDebugUtils.currentLine=1245215;
 //BA.debugLineNum = 1245215;BA.debugLine="Dim layout As String = \"\"";
_layout = "";
RDebugUtils.currentLine=1245216;
 //BA.debugLineNum = 1245216;BA.debugLine="Private isFirstInit As Boolean = True";
_isfirstinit = __c.True;
RDebugUtils.currentLine=1245217;
 //BA.debugLineNum = 1245217;BA.debugLine="Dim sortMainpanel As Panel";
_sortmainpanel = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=1245218;
 //BA.debugLineNum = 1245218;BA.debugLine="Dim shownMainpanel As Panel";
_shownmainpanel = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=1245219;
 //BA.debugLineNum = 1245219;BA.debugLine="End Sub";
return "";
}
public String  _drawgraph(b4a.example.bargraph __ref,anywheresoftware.b4a.objects.ActivityWrapper _active,anywheresoftware.b4a.objects.PanelWrapper _panel,int[] _sale1,int[] _sale2,int[] _sale3,String[] _product,int _maxsales,String _titlestring) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "drawgraph", false))
	 {return ((String) Debug.delegate(ba, "drawgraph", new Object[] {_active,_panel,_sale1,_sale2,_sale3,_product,_maxsales,_titlestring}));}
int _halfwidth = 0;
anywheresoftware.b4a.objects.drawable.ColorDrawable _cd = null;
anywheresoftware.b4a.objects.PanelWrapper _activitypanel = null;
int _alignleftcenter = 0;
int _aligntopcenter = 0;
anywheresoftware.b4a.objects.LabelWrapper _title = null;
anywheresoftware.b4a.objects.drawable.CanvasWrapper _graphcanvas = null;
int _maxsale = 0;
anywheresoftware.b4a.objects.drawable.CanvasWrapper _cv = null;
int _totalproducts = 0;
int _startindex = 0;
int _endindex = 0;
int _barsperproduct = 0;
int _totalbars = 0;
int _gap = 0;
int _productgap = 0;
int _padding = 0;
int _availablewidth = 0;
int _barwidth = 0;
int _xstart = 0;
int _i = 0;
int _xpos = 0;
int[] _salevalues = null;
int _indexoffset = 0;
int _j = 0;
int _sale = 0;
int _barheight = 0;
int _xbar = 0;
anywheresoftware.b4a.objects.drawable.CanvasWrapper.RectWrapper _r = null;
int _fontsize = 0;
anywheresoftware.b4a.objects.LabelWrapper _productlabel = null;
int _productlabely = 0;
int _productlabelx = 0;
int _numlabels = 0;
int _labelvalue = 0;
int _labelypos = 0;
anywheresoftware.b4a.objects.LabelWrapper _yaxislabel = null;
int _buttonwidth = 0;
int _buttonheight = 0;
int _buttonspacing = 0;
int _graphbottom = 0;
int _buttony = 0;
int _btnbackx = 0;
int _btnnextx = 0;
anywheresoftware.b4a.objects.PanelWrapper _btnmainpanel = null;
anywheresoftware.b4a.objects.PanelWrapper _paginationpanel = null;
anywheresoftware.b4a.objects.drawable.ColorDrawable _cdback = null;
anywheresoftware.b4a.objects.drawable.ColorDrawable _cdnext = null;
anywheresoftware.b4a.objects.LabelWrapper _paginationlabel = null;
anywheresoftware.b4a.objects.ButtonWrapper _showhidebtn = null;
RDebugUtils.currentLine=1376256;
 //BA.debugLineNum = 1376256;BA.debugLine="Public Sub DrawGraph(Active As Activity, panel As";
RDebugUtils.currentLine=1376257;
 //BA.debugLineNum = 1376257;BA.debugLine="Try";
try {RDebugUtils.currentLine=1376258;
 //BA.debugLineNum = 1376258;BA.debugLine="panel.Invalidate";
_panel.Invalidate();
RDebugUtils.currentLine=1376259;
 //BA.debugLineNum = 1376259;BA.debugLine="panel.RemoveAllViews";
_panel.RemoveAllViews();
RDebugUtils.currentLine=1376260;
 //BA.debugLineNum = 1376260;BA.debugLine="panel.Height = 530dip";
_panel.setHeight(__c.DipToCurrent((int) (530)));
RDebugUtils.currentLine=1376261;
 //BA.debugLineNum = 1376261;BA.debugLine="If panel.Width = 0 Then";
if (_panel.getWidth()==0) { 
RDebugUtils.currentLine=1376262;
 //BA.debugLineNum = 1376262;BA.debugLine="panel.Width = 800dip";
_panel.setWidth(__c.DipToCurrent((int) (800)));
 };
RDebugUtils.currentLine=1376264;
 //BA.debugLineNum = 1376264;BA.debugLine="Dim halfWidth As Int = panel.Width / 2";
_halfwidth = (int) (_panel.getWidth()/(double)2);
RDebugUtils.currentLine=1376266;
 //BA.debugLineNum = 1376266;BA.debugLine="Dim cd As ColorDrawable";
_cd = new anywheresoftware.b4a.objects.drawable.ColorDrawable();
RDebugUtils.currentLine=1376267;
 //BA.debugLineNum = 1376267;BA.debugLine="cd.Initialize2(Colors.White, 5dip, 1dip, Colors.";
_cd.Initialize2(__c.Colors.White,__c.DipToCurrent((int) (5)),__c.DipToCurrent((int) (1)),__c.Colors.Black);
RDebugUtils.currentLine=1376268;
 //BA.debugLineNum = 1376268;BA.debugLine="panel.AddView(legendPanel, halfWidth +10dip, 10d";
_panel.AddView((android.view.View)(__ref._legendpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getObject()),(int) (_halfwidth+__c.DipToCurrent((int) (10))),__c.DipToCurrent((int) (10)),(int) (_halfwidth-__c.DipToCurrent((int) (20))),__c.DipToCurrent((int) (45)));
RDebugUtils.currentLine=1376269;
 //BA.debugLineNum = 1376269;BA.debugLine="legendPanel.Background = cd";
__ref._legendpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .setBackground((android.graphics.drawable.Drawable)(_cd.getObject()));
RDebugUtils.currentLine=1376271;
 //BA.debugLineNum = 1376271;BA.debugLine="radioLabelLegendTitles.Initialize(\"radioLabelLeg";
__ref._radiolabellegendtitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .Initialize(ba,"radioLabelLegendTitles");
RDebugUtils.currentLine=1376272;
 //BA.debugLineNum = 1376272;BA.debugLine="radioLabelLegendTitles.Text = \"Shown Details\"";
__ref._radiolabellegendtitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setText(BA.ObjectToCharSequence("Shown Details"));
RDebugUtils.currentLine=1376273;
 //BA.debugLineNum = 1376273;BA.debugLine="radioLabelLegendTitles.TextSize = 12";
__ref._radiolabellegendtitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTextSize((float) (12));
RDebugUtils.currentLine=1376274;
 //BA.debugLineNum = 1376274;BA.debugLine="radioLabelLegendTitles.Typeface = Typeface.MONOS";
__ref._radiolabellegendtitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=1376275;
 //BA.debugLineNum = 1376275;BA.debugLine="radioLabelLegendTitles.Gravity = Gravity.CENTER";
__ref._radiolabellegendtitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setGravity(__c.Gravity.CENTER);
RDebugUtils.currentLine=1376276;
 //BA.debugLineNum = 1376276;BA.debugLine="radioLabelLegendTitles.TextColor = Colors.Black";
__ref._radiolabellegendtitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=1376277;
 //BA.debugLineNum = 1376277;BA.debugLine="radioLabelLegendTitles.Color = Colors.White";
__ref._radiolabellegendtitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setColor(__c.Colors.White);
RDebugUtils.currentLine=1376278;
 //BA.debugLineNum = 1376278;BA.debugLine="panel.AddView(radioLabelLegendTitles, halfWidth+";
_panel.AddView((android.view.View)(__ref._radiolabellegendtitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .getObject()),(int) (_halfwidth+__c.DipToCurrent((int) (15))),__c.DipToCurrent((int) (2.5)),__c.DipToCurrent((int) (100)),__c.DipToCurrent((int) (16)));
RDebugUtils.currentLine=1376281;
 //BA.debugLineNum = 1376281;BA.debugLine="Dim activityPanel As Panel";
_activitypanel = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=1376282;
 //BA.debugLineNum = 1376282;BA.debugLine="activityPanel.Initialize(\"activityPanel\")";
_activitypanel.Initialize(ba,"activityPanel");
RDebugUtils.currentLine=1376284;
 //BA.debugLineNum = 1376284;BA.debugLine="activityPanel.Width = 80%x";
_activitypanel.setWidth(__c.PerXToCurrent((float) (80),ba));
RDebugUtils.currentLine=1376285;
 //BA.debugLineNum = 1376285;BA.debugLine="If Active.Width > 800 Then";
if (_active.getWidth()>800) { 
RDebugUtils.currentLine=1376286;
 //BA.debugLineNum = 1376286;BA.debugLine="activityPanel.Width = 55%x";
_activitypanel.setWidth(__c.PerXToCurrent((float) (55),ba));
 };
RDebugUtils.currentLine=1376288;
 //BA.debugLineNum = 1376288;BA.debugLine="activityPanel.Height = 250dip";
_activitypanel.setHeight(__c.DipToCurrent((int) (250)));
RDebugUtils.currentLine=1376289;
 //BA.debugLineNum = 1376289;BA.debugLine="activityPanel.Color = Colors.ARGB(70, 211, 211,";
_activitypanel.setColor(__c.Colors.ARGB((int) (70),(int) (211),(int) (211),(int) (211)));
RDebugUtils.currentLine=1376291;
 //BA.debugLineNum = 1376291;BA.debugLine="Dim alignLeftCenter As Int = (Active.Width - act";
_alignleftcenter = (int) ((_active.getWidth()-_activitypanel.getWidth())/(double)2);
RDebugUtils.currentLine=1376292;
 //BA.debugLineNum = 1376292;BA.debugLine="Dim alignTopCenter As Int = (panel.Height - acti";
_aligntopcenter = (int) ((_panel.getHeight()-_activitypanel.getHeight())/(double)2-__c.DipToCurrent((int) (20)));
RDebugUtils.currentLine=1376294;
 //BA.debugLineNum = 1376294;BA.debugLine="Dim Title As Label";
_title = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=1376295;
 //BA.debugLineNum = 1376295;BA.debugLine="Title.Initialize(\"\")";
_title.Initialize(ba,"");
RDebugUtils.currentLine=1376296;
 //BA.debugLineNum = 1376296;BA.debugLine="Title.Text = TitleString";
_title.setText(BA.ObjectToCharSequence(_titlestring));
RDebugUtils.currentLine=1376297;
 //BA.debugLineNum = 1376297;BA.debugLine="Title.TextSize = 20";
_title.setTextSize((float) (20));
RDebugUtils.currentLine=1376298;
 //BA.debugLineNum = 1376298;BA.debugLine="Title.Typeface = Typeface.MONOSPACE";
_title.setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=1376299;
 //BA.debugLineNum = 1376299;BA.debugLine="Title.Gravity = Gravity.CENTER";
_title.setGravity(__c.Gravity.CENTER);
RDebugUtils.currentLine=1376300;
 //BA.debugLineNum = 1376300;BA.debugLine="Title.TextColor = Colors.Black";
_title.setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=1376301;
 //BA.debugLineNum = 1376301;BA.debugLine="panel.AddView(Title, 0, alignTopCenter / 2 +55di";
_panel.AddView((android.view.View)(_title.getObject()),(int) (0),(int) (_aligntopcenter/(double)2+__c.DipToCurrent((int) (55))),_panel.getWidth(),__c.DipToCurrent((int) (30)));
RDebugUtils.currentLine=1376303;
 //BA.debugLineNum = 1376303;BA.debugLine="panel.AddView(activityPanel, alignLeftCenter, al";
_panel.AddView((android.view.View)(_activitypanel.getObject()),_alignleftcenter,(int) (_aligntopcenter+(_aligntopcenter/(double)4)),_activitypanel.getWidth(),_activitypanel.getHeight());
RDebugUtils.currentLine=1376305;
 //BA.debugLineNum = 1376305;BA.debugLine="Dim graphCanvas As Canvas";
_graphcanvas = new anywheresoftware.b4a.objects.drawable.CanvasWrapper();
RDebugUtils.currentLine=1376306;
 //BA.debugLineNum = 1376306;BA.debugLine="graphCanvas.Initialize(activityPanel)";
_graphcanvas.Initialize((android.view.View)(_activitypanel.getObject()));
RDebugUtils.currentLine=1376308;
 //BA.debugLineNum = 1376308;BA.debugLine="Dim maxSale As Int = maxSales * 1.2";
_maxsale = (int) (_maxsales*1.2);
RDebugUtils.currentLine=1376309;
 //BA.debugLineNum = 1376309;BA.debugLine="Dim cv As Canvas";
_cv = new anywheresoftware.b4a.objects.drawable.CanvasWrapper();
RDebugUtils.currentLine=1376310;
 //BA.debugLineNum = 1376310;BA.debugLine="cv.Initialize(panel)";
_cv.Initialize((android.view.View)(_panel.getObject()));
RDebugUtils.currentLine=1376312;
 //BA.debugLineNum = 1376312;BA.debugLine="Dim totalProducts As Int = sale1.Length";
_totalproducts = _sale1.length;
RDebugUtils.currentLine=1376313;
 //BA.debugLineNum = 1376313;BA.debugLine="Dim startIndex As Int = (currentPage - 1) * item";
_startindex = (int) ((__ref._currentpage /*int*/ -1)*__ref._itemsperpage /*int*/ );
RDebugUtils.currentLine=1376314;
 //BA.debugLineNum = 1376314;BA.debugLine="Dim endIndex As Int = Min(startIndex + itemsPerP";
_endindex = (int) (__c.Min(_startindex+__ref._itemsperpage /*int*/ -1,_totalproducts-1));
RDebugUtils.currentLine=1376315;
 //BA.debugLineNum = 1376315;BA.debugLine="Dim barsPerProduct As Int = 3";
_barsperproduct = (int) (3);
RDebugUtils.currentLine=1376316;
 //BA.debugLineNum = 1376316;BA.debugLine="Dim totalBars As Int = (endIndex - startIndex +";
_totalbars = (int) ((_endindex-_startindex+1)*_barsperproduct);
RDebugUtils.currentLine=1376317;
 //BA.debugLineNum = 1376317;BA.debugLine="Dim gap As Int = 5dip";
_gap = __c.DipToCurrent((int) (5));
RDebugUtils.currentLine=1376318;
 //BA.debugLineNum = 1376318;BA.debugLine="Dim productGap As Int = 0dip";
_productgap = __c.DipToCurrent((int) (0));
RDebugUtils.currentLine=1376319;
 //BA.debugLineNum = 1376319;BA.debugLine="Dim padding As Int = 10dip";
_padding = __c.DipToCurrent((int) (10));
RDebugUtils.currentLine=1376321;
 //BA.debugLineNum = 1376321;BA.debugLine="Dim availableWidth As Int = activityPanel.Width";
_availablewidth = (int) (_activitypanel.getWidth()-(_padding*2)-(((_endindex-_startindex+1)-1)*_productgap)-((_totalbars-(_endindex-_startindex+1))*_gap));
RDebugUtils.currentLine=1376322;
 //BA.debugLineNum = 1376322;BA.debugLine="Dim barWidth As Int = availableWidth / totalBars";
_barwidth = (int) (_availablewidth/(double)_totalbars);
RDebugUtils.currentLine=1376323;
 //BA.debugLineNum = 1376323;BA.debugLine="Dim xStart As Int = padding";
_xstart = _padding;
RDebugUtils.currentLine=1376325;
 //BA.debugLineNum = 1376325;BA.debugLine="For i = startIndex To endIndex";
{
final int step56 = 1;
final int limit56 = _endindex;
_i = _startindex ;
for (;_i <= limit56 ;_i = _i + step56 ) {
RDebugUtils.currentLine=1376326;
 //BA.debugLineNum = 1376326;BA.debugLine="Dim xPos As Int = xStart + (i - startIndex) * (";
_xpos = (int) (_xstart+(_i-_startindex)*(_barsperproduct*(_barwidth+_gap)+_productgap));
RDebugUtils.currentLine=1376327;
 //BA.debugLineNum = 1376327;BA.debugLine="Dim saleValues() As Int = Array As Int(sale1(i)";
_salevalues = new int[]{_sale1[_i],_sale2[_i],_sale3[_i]};
RDebugUtils.currentLine=1376328;
 //BA.debugLineNum = 1376328;BA.debugLine="Dim indexOffset As Int = 0";
_indexoffset = (int) (0);
RDebugUtils.currentLine=1376330;
 //BA.debugLineNum = 1376330;BA.debugLine="For j = 0 To barsPerProduct - 1";
{
final int step60 = 1;
final int limit60 = (int) (_barsperproduct-1);
_j = (int) (0) ;
for (;_j <= limit60 ;_j = _j + step60 ) {
RDebugUtils.currentLine=1376331;
 //BA.debugLineNum = 1376331;BA.debugLine="If j < checkedSales.Length And checkedSales(j)";
if (_j<__ref._checkedsales /*boolean[]*/ .length && __ref._checkedsales /*boolean[]*/ [_j]) { 
RDebugUtils.currentLine=1376332;
 //BA.debugLineNum = 1376332;BA.debugLine="Dim sale As Int = saleValues(j)";
_sale = _salevalues[_j];
RDebugUtils.currentLine=1376333;
 //BA.debugLineNum = 1376333;BA.debugLine="Dim barHeight As Int = (sale / maxSale) * (ac";
_barheight = (int) ((_sale/(double)_maxsale)*(_activitypanel.getHeight()));
RDebugUtils.currentLine=1376334;
 //BA.debugLineNum = 1376334;BA.debugLine="Dim xBar As Int = xPos + indexOffset * barWid";
_xbar = (int) (_xpos+_indexoffset*_barwidth);
RDebugUtils.currentLine=1376336;
 //BA.debugLineNum = 1376336;BA.debugLine="Dim r As Rect";
_r = new anywheresoftware.b4a.objects.drawable.CanvasWrapper.RectWrapper();
RDebugUtils.currentLine=1376337;
 //BA.debugLineNum = 1376337;BA.debugLine="r.Initialize(xBar, activityPanel.Height - bar";
_r.Initialize(_xbar,(int) (_activitypanel.getHeight()-_barheight),(int) (_xbar+_barwidth),_activitypanel.getHeight());
RDebugUtils.currentLine=1376338;
 //BA.debugLineNum = 1376338;BA.debugLine="graphCanvas.DrawRect(r, color(j), True, 2dip)";
_graphcanvas.DrawRect((android.graphics.Rect)(_r.getObject()),__ref._color /*int[]*/ [_j],__c.True,(float) (__c.DipToCurrent((int) (2))));
RDebugUtils.currentLine=1376340;
 //BA.debugLineNum = 1376340;BA.debugLine="Dim fontSize As Int = 8";
_fontsize = (int) (8);
RDebugUtils.currentLine=1376341;
 //BA.debugLineNum = 1376341;BA.debugLine="If Active.Width > 800 Then";
if (_active.getWidth()>800) { 
RDebugUtils.currentLine=1376342;
 //BA.debugLineNum = 1376342;BA.debugLine="fontSize = 10";
_fontsize = (int) (10);
 };
RDebugUtils.currentLine=1376344;
 //BA.debugLineNum = 1376344;BA.debugLine="graphCanvas.DrawText(FormatNumberWithSuffix(s";
_graphcanvas.DrawText(ba,__ref._formatnumberwithsuffix /*String*/ (null,_sale),(float) (_xbar+(_barwidth/(double)2)),(float) (_activitypanel.getHeight()-_barheight-__c.DipToCurrent((int) (5))),__c.Typeface.MONOSPACE,(float) (_fontsize),__c.Colors.Black,BA.getEnumFromString(android.graphics.Paint.Align.class,"CENTER"));
RDebugUtils.currentLine=1376345;
 //BA.debugLineNum = 1376345;BA.debugLine="indexOffset = indexOffset + 1";
_indexoffset = (int) (_indexoffset+1);
 };
 }
};
RDebugUtils.currentLine=1376349;
 //BA.debugLineNum = 1376349;BA.debugLine="Dim productLabel As Label";
_productlabel = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=1376350;
 //BA.debugLineNum = 1376350;BA.debugLine="productLabel.Initialize(\"productLabel\")";
_productlabel.Initialize(ba,"productLabel");
RDebugUtils.currentLine=1376351;
 //BA.debugLineNum = 1376351;BA.debugLine="productLabel.Text = product(i)";
_productlabel.setText(BA.ObjectToCharSequence(_product[_i]));
RDebugUtils.currentLine=1376352;
 //BA.debugLineNum = 1376352;BA.debugLine="productLabel.Typeface = Typeface.MONOSPACE";
_productlabel.setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=1376353;
 //BA.debugLineNum = 1376353;BA.debugLine="productLabel.TextSize = 12";
_productlabel.setTextSize((float) (12));
RDebugUtils.currentLine=1376354;
 //BA.debugLineNum = 1376354;BA.debugLine="productLabel.Tag = comId1(i)";
_productlabel.setTag((Object)(__ref._comid1 /*int[]*/ [_i]));
RDebugUtils.currentLine=1376355;
 //BA.debugLineNum = 1376355;BA.debugLine="productLabel.TextColor = Colors.Black";
_productlabel.setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=1376356;
 //BA.debugLineNum = 1376356;BA.debugLine="productLabel.Gravity = Gravity.CENTER";
_productlabel.setGravity(__c.Gravity.CENTER);
RDebugUtils.currentLine=1376357;
 //BA.debugLineNum = 1376357;BA.debugLine="Dim productLabelY As Int = activityPanel.Height";
_productlabely = (int) (_activitypanel.getHeight()+_aligntopcenter+__c.DipToCurrent((int) (30)));
RDebugUtils.currentLine=1376358;
 //BA.debugLineNum = 1376358;BA.debugLine="Dim productLabelX As Int = alignLeftCenter";
_productlabelx = _alignleftcenter;
RDebugUtils.currentLine=1376359;
 //BA.debugLineNum = 1376359;BA.debugLine="panel.AddView(productLabel, xPos + productLabel";
_panel.AddView((android.view.View)(_productlabel.getObject()),(int) (_xpos+_productlabelx),(int) (_productlabely+20),__c.DipToCurrent((int) (100)),__c.DipToCurrent((int) (30)));
 }
};
RDebugUtils.currentLine=1376362;
 //BA.debugLineNum = 1376362;BA.debugLine="Dim numLabels As Int = 10";
_numlabels = (int) (10);
RDebugUtils.currentLine=1376363;
 //BA.debugLineNum = 1376363;BA.debugLine="For i = 0 To numLabels";
{
final int step89 = 1;
final int limit89 = _numlabels;
_i = (int) (0) ;
for (;_i <= limit89 ;_i = _i + step89 ) {
RDebugUtils.currentLine=1376364;
 //BA.debugLineNum = 1376364;BA.debugLine="Dim labelValue As Int = Round((maxSale / numLab";
_labelvalue = (int) (__c.Round((_maxsale/(double)_numlabels)*_i));
RDebugUtils.currentLine=1376365;
 //BA.debugLineNum = 1376365;BA.debugLine="Dim labelYPos As Int = activityPanel.Height - (";
_labelypos = (int) (_activitypanel.getHeight()-((_labelvalue/(double)_maxsale)*_activitypanel.getHeight()));
RDebugUtils.currentLine=1376367;
 //BA.debugLineNum = 1376367;BA.debugLine="Dim yAxisLabel As Label";
_yaxislabel = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=1376368;
 //BA.debugLineNum = 1376368;BA.debugLine="yAxisLabel.Initialize(\"\")";
_yaxislabel.Initialize(ba,"");
RDebugUtils.currentLine=1376369;
 //BA.debugLineNum = 1376369;BA.debugLine="yAxisLabel.Text = FormatNumberWithLabel(labelVa";
_yaxislabel.setText(BA.ObjectToCharSequence(__ref._formatnumberwithlabel /*String*/ (null,_labelvalue)));
RDebugUtils.currentLine=1376370;
 //BA.debugLineNum = 1376370;BA.debugLine="yAxisLabel.TextSize = 10";
_yaxislabel.setTextSize((float) (10));
RDebugUtils.currentLine=1376371;
 //BA.debugLineNum = 1376371;BA.debugLine="yAxisLabel.Typeface = Typeface.MONOSPACE";
_yaxislabel.setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=1376372;
 //BA.debugLineNum = 1376372;BA.debugLine="yAxisLabel.TextColor = Colors.Black";
_yaxislabel.setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=1376373;
 //BA.debugLineNum = 1376373;BA.debugLine="yAxisLabel.Gravity = Gravity.RIGHT";
_yaxislabel.setGravity(__c.Gravity.RIGHT);
RDebugUtils.currentLine=1376375;
 //BA.debugLineNum = 1376375;BA.debugLine="panel.AddView(yAxisLabel, alignLeftCenter - 40d";
_panel.AddView((android.view.View)(_yaxislabel.getObject()),(int) (_alignleftcenter-__c.DipToCurrent((int) (40))),(int) (_activitypanel.getTop()+_labelypos-__c.DipToCurrent((int) (10))),__c.DipToCurrent((int) (30)),__c.DipToCurrent((int) (15)));
 }
};
RDebugUtils.currentLine=1376377;
 //BA.debugLineNum = 1376377;BA.debugLine="btnBack.Enabled = currentPage > 1";
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setEnabled(__ref._currentpage /*int*/ >1);
RDebugUtils.currentLine=1376378;
 //BA.debugLineNum = 1376378;BA.debugLine="btnNext.Enabled = (currentPage * itemsPerPage) <";
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setEnabled((__ref._currentpage /*int*/ *__ref._itemsperpage /*int*/ )<_sale1.length);
RDebugUtils.currentLine=1376383;
 //BA.debugLineNum = 1376383;BA.debugLine="Dim buttonWidth As Int = 50dip";
_buttonwidth = __c.DipToCurrent((int) (50));
RDebugUtils.currentLine=1376384;
 //BA.debugLineNum = 1376384;BA.debugLine="Dim buttonHeight As Int = 40dip";
_buttonheight = __c.DipToCurrent((int) (40));
RDebugUtils.currentLine=1376385;
 //BA.debugLineNum = 1376385;BA.debugLine="Dim buttonSpacing As Int = 25dip ' Adjust as nee";
_buttonspacing = __c.DipToCurrent((int) (25));
RDebugUtils.currentLine=1376387;
 //BA.debugLineNum = 1376387;BA.debugLine="Dim graphBottom As Int = activityPanel.Top + act";
_graphbottom = (int) (_activitypanel.getTop()+_activitypanel.getHeight());
RDebugUtils.currentLine=1376388;
 //BA.debugLineNum = 1376388;BA.debugLine="Dim buttonY As Int = graphBottom + buttonSpacing";
_buttony = (int) (_graphbottom+_buttonspacing);
RDebugUtils.currentLine=1376390;
 //BA.debugLineNum = 1376390;BA.debugLine="Dim btnBackX As Int = (panel.Width / 2) - button";
_btnbackx = (int) ((_panel.getWidth()/(double)2)-_buttonwidth-__c.DipToCurrent((int) (100)));
RDebugUtils.currentLine=1376391;
 //BA.debugLineNum = 1376391;BA.debugLine="Dim btnNextX As Int = (panel.Width / 2) + 100dip";
_btnnextx = (int) ((_panel.getWidth()/(double)2)+__c.DipToCurrent((int) (100)));
RDebugUtils.currentLine=1376393;
 //BA.debugLineNum = 1376393;BA.debugLine="Dim btnMainPanel As Panel";
_btnmainpanel = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=1376394;
 //BA.debugLineNum = 1376394;BA.debugLine="btnMainPanel.Initialize(\"\")";
_btnmainpanel.Initialize(ba,"");
RDebugUtils.currentLine=1376395;
 //BA.debugLineNum = 1376395;BA.debugLine="Log($\"alignTopCenter:${alignTopCenter}\"$)";
__c.LogImpl("41376395",("alignTopCenter:"+__c.SmartStringFormatter("",(Object)(_aligntopcenter))+""),0);
RDebugUtils.currentLine=1376396;
 //BA.debugLineNum = 1376396;BA.debugLine="panel.AddView(btnMainPanel,alignLeftCenter,panel";
_panel.AddView((android.view.View)(_btnmainpanel.getObject()),_alignleftcenter,(int) (_panel.getHeight()-((_aligntopcenter/(double)2)+__c.DipToCurrent((int) (20)))),_activitypanel.getWidth(),__c.DipToCurrent((int) (50)));
RDebugUtils.currentLine=1376398;
 //BA.debugLineNum = 1376398;BA.debugLine="Dim paginationPanel As Panel";
_paginationpanel = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=1376399;
 //BA.debugLineNum = 1376399;BA.debugLine="paginationPanel.Initialize(\"\")";
_paginationpanel.Initialize(ba,"");
RDebugUtils.currentLine=1376400;
 //BA.debugLineNum = 1376400;BA.debugLine="btnMainPanel.AddView(paginationPanel,0,0,btnMain";
_btnmainpanel.AddView((android.view.View)(_paginationpanel.getObject()),(int) (0),(int) (0),(int) (_btnmainpanel.getWidth()-__c.DipToCurrent((int) (150))),_btnmainpanel.getHeight());
RDebugUtils.currentLine=1376404;
 //BA.debugLineNum = 1376404;BA.debugLine="If btnBack.Parent <> Null Then btnBack.RemoveVie";
if (__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .getParent()!= null) { 
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .RemoveView();};
RDebugUtils.currentLine=1376405;
 //BA.debugLineNum = 1376405;BA.debugLine="If btnNext.Parent <> Null Then btnNext.RemoveVie";
if (__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .getParent()!= null) { 
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .RemoveView();};
RDebugUtils.currentLine=1376408;
 //BA.debugLineNum = 1376408;BA.debugLine="btnBack.Text = \"<\"";
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setText(BA.ObjectToCharSequence("<"));
RDebugUtils.currentLine=1376409;
 //BA.debugLineNum = 1376409;BA.debugLine="btnBack.TextSize = 14";
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setTextSize((float) (14));
RDebugUtils.currentLine=1376410;
 //BA.debugLineNum = 1376410;BA.debugLine="btnBack.Typeface = Typeface.MONOSPACE";
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=1376411;
 //BA.debugLineNum = 1376411;BA.debugLine="btnBack.TextColor = Colors.White";
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setTextColor(__c.Colors.White);
RDebugUtils.currentLine=1376412;
 //BA.debugLineNum = 1376412;BA.debugLine="Dim cdBack As ColorDrawable";
_cdback = new anywheresoftware.b4a.objects.drawable.ColorDrawable();
RDebugUtils.currentLine=1376413;
 //BA.debugLineNum = 1376413;BA.debugLine="cdBack.Initialize2(Colors.RGB(61, 12, 2), 10dip,";
_cdback.Initialize2(__c.Colors.RGB((int) (61),(int) (12),(int) (2)),__c.DipToCurrent((int) (10)),__c.DipToCurrent((int) (2)),__c.Colors.Black);
RDebugUtils.currentLine=1376414;
 //BA.debugLineNum = 1376414;BA.debugLine="btnBack.Background = cdBack";
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setBackground((android.graphics.drawable.Drawable)(_cdback.getObject()));
RDebugUtils.currentLine=1376417;
 //BA.debugLineNum = 1376417;BA.debugLine="btnNext.Text = \">\"";
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setText(BA.ObjectToCharSequence(">"));
RDebugUtils.currentLine=1376418;
 //BA.debugLineNum = 1376418;BA.debugLine="btnNext.TextSize = 14";
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setTextSize((float) (14));
RDebugUtils.currentLine=1376419;
 //BA.debugLineNum = 1376419;BA.debugLine="btnNext.Typeface = Typeface.MONOSPACE";
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=1376420;
 //BA.debugLineNum = 1376420;BA.debugLine="btnNext.TextColor = Colors.White";
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setTextColor(__c.Colors.White);
RDebugUtils.currentLine=1376421;
 //BA.debugLineNum = 1376421;BA.debugLine="Dim cdNext As ColorDrawable";
_cdnext = new anywheresoftware.b4a.objects.drawable.ColorDrawable();
RDebugUtils.currentLine=1376422;
 //BA.debugLineNum = 1376422;BA.debugLine="cdNext.Initialize2(Colors.RGB(185, 46, 52), 10di";
_cdnext.Initialize2(__c.Colors.RGB((int) (185),(int) (46),(int) (52)),__c.DipToCurrent((int) (10)),__c.DipToCurrent((int) (2)),__c.Colors.Black);
RDebugUtils.currentLine=1376423;
 //BA.debugLineNum = 1376423;BA.debugLine="btnNext.Background = cdNext";
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setBackground((android.graphics.drawable.Drawable)(_cdnext.getObject()));
RDebugUtils.currentLine=1376425;
 //BA.debugLineNum = 1376425;BA.debugLine="Dim paginationLabel As Label";
_paginationlabel = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=1376426;
 //BA.debugLineNum = 1376426;BA.debugLine="paginationLabel.Initialize(\"\")";
_paginationlabel.Initialize(ba,"");
RDebugUtils.currentLine=1376427;
 //BA.debugLineNum = 1376427;BA.debugLine="paginationLabel.Text = $\"Page 1 out of 10\"$";
_paginationlabel.setText(BA.ObjectToCharSequence(("Page 1 out of 10")));
RDebugUtils.currentLine=1376428;
 //BA.debugLineNum = 1376428;BA.debugLine="paginationLabel.Gravity = Gravity.CENTER";
_paginationlabel.setGravity(__c.Gravity.CENTER);
RDebugUtils.currentLine=1376429;
 //BA.debugLineNum = 1376429;BA.debugLine="paginationLabel.Typeface = Typeface.MONOSPACE";
_paginationlabel.setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=1376430;
 //BA.debugLineNum = 1376430;BA.debugLine="paginationPanel.AddView(paginationLabel,buttonWi";
_paginationpanel.AddView((android.view.View)(_paginationlabel.getObject()),_buttonwidth,(int) (0),(int) (_paginationpanel.getWidth()-(_buttonwidth*2)),_paginationpanel.getHeight());
RDebugUtils.currentLine=1376432;
 //BA.debugLineNum = 1376432;BA.debugLine="Dim buttonWidth As Int = 50dip";
_buttonwidth = __c.DipToCurrent((int) (50));
RDebugUtils.currentLine=1376433;
 //BA.debugLineNum = 1376433;BA.debugLine="Dim buttonHeight As Int = 40dip";
_buttonheight = __c.DipToCurrent((int) (40));
RDebugUtils.currentLine=1376435;
 //BA.debugLineNum = 1376435;BA.debugLine="paginationPanel.AddView(btnBack, 0, (paginationP";
_paginationpanel.AddView((android.view.View)(__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .getObject()),(int) (0),(int) ((_paginationpanel.getHeight()-_buttonheight)/(double)2),_buttonwidth,_buttonheight);
RDebugUtils.currentLine=1376436;
 //BA.debugLineNum = 1376436;BA.debugLine="paginationPanel.AddView(btnNext, paginationPanel";
_paginationpanel.AddView((android.view.View)(__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .getObject()),(int) (_paginationpanel.getWidth()-_buttonwidth),(int) ((_paginationpanel.getHeight()-_buttonheight)/(double)2),_buttonwidth,_buttonheight);
RDebugUtils.currentLine=1376439;
 //BA.debugLineNum = 1376439;BA.debugLine="btnBack.Enabled = currentPage > 1";
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setEnabled(__ref._currentpage /*int*/ >1);
RDebugUtils.currentLine=1376440;
 //BA.debugLineNum = 1376440;BA.debugLine="btnNext.Enabled = (currentPage * itemsPerPage) <";
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setEnabled((__ref._currentpage /*int*/ *__ref._itemsperpage /*int*/ )<_sale1.length);
RDebugUtils.currentLine=1376442;
 //BA.debugLineNum = 1376442;BA.debugLine="Dim showHideBtn As Button";
_showhidebtn = new anywheresoftware.b4a.objects.ButtonWrapper();
RDebugUtils.currentLine=1376443;
 //BA.debugLineNum = 1376443;BA.debugLine="showHideBtn.Initialize(\"\")";
_showhidebtn.Initialize(ba,"");
RDebugUtils.currentLine=1376444;
 //BA.debugLineNum = 1376444;BA.debugLine="showHideBtn.Text = $\"Show Details\"$";
_showhidebtn.setText(BA.ObjectToCharSequence(("Show Details")));
RDebugUtils.currentLine=1376445;
 //BA.debugLineNum = 1376445;BA.debugLine="showHideBtn.TextColor = Colors.White";
_showhidebtn.setTextColor(__c.Colors.White);
RDebugUtils.currentLine=1376446;
 //BA.debugLineNum = 1376446;BA.debugLine="btnMainPanel.AddView(showHideBtn,paginationPanel";
_btnmainpanel.AddView((android.view.View)(_showhidebtn.getObject()),(int) (_paginationpanel.getWidth()+__c.DipToCurrent((int) (5))),__c.DipToCurrent((int) (5)),(int) ((_btnmainpanel.getWidth()-_paginationpanel.getWidth())-__c.DipToCurrent((int) (10))),_buttonheight);
RDebugUtils.currentLine=1376448;
 //BA.debugLineNum = 1376448;BA.debugLine="Dim cdBack As ColorDrawable";
_cdback = new anywheresoftware.b4a.objects.drawable.ColorDrawable();
RDebugUtils.currentLine=1376449;
 //BA.debugLineNum = 1376449;BA.debugLine="cdBack.Initialize2(Colors.RGB(61, 12, 2), 10dip,";
_cdback.Initialize2(__c.Colors.RGB((int) (61),(int) (12),(int) (2)),__c.DipToCurrent((int) (10)),__c.DipToCurrent((int) (2)),__c.Colors.Black);
RDebugUtils.currentLine=1376450;
 //BA.debugLineNum = 1376450;BA.debugLine="showHideBtn.Background = cdBack";
_showhidebtn.setBackground((android.graphics.drawable.Drawable)(_cdback.getObject()));
 } 
       catch (Exception e154) {
			ba.setLastException(e154);RDebugUtils.currentLine=1376452;
 //BA.debugLineNum = 1376452;BA.debugLine="Log(LastException)";
__c.LogImpl("41376452",BA.ObjectToString(__c.LastException(ba)),0);
 };
RDebugUtils.currentLine=1376454;
 //BA.debugLineNum = 1376454;BA.debugLine="End Sub";
return "";
}
public String  _formatnumberwithsuffix(b4a.example.bargraph __ref,int _number) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "formatnumberwithsuffix", false))
	 {return ((String) Debug.delegate(ba, "formatnumberwithsuffix", new Object[] {_number}));}
RDebugUtils.currentLine=1703936;
 //BA.debugLineNum = 1703936;BA.debugLine="Sub FormatNumberWithSuffix(number As Int) As Strin";
RDebugUtils.currentLine=1703937;
 //BA.debugLineNum = 1703937;BA.debugLine="If number >= 1000000 Then";
if (_number>=1000000) { 
RDebugUtils.currentLine=1703938;
 //BA.debugLineNum = 1703938;BA.debugLine="Return NumberFormat(number / 1000000, 1, 1) & \"M";
if (true) return __c.NumberFormat(_number/(double)1000000,(int) (1),(int) (1))+"M";
 }else 
{RDebugUtils.currentLine=1703939;
 //BA.debugLineNum = 1703939;BA.debugLine="Else If number >= 1000 Then";
if (_number>=1000) { 
RDebugUtils.currentLine=1703940;
 //BA.debugLineNum = 1703940;BA.debugLine="Return NumberFormat(number / 1000, 1, 1) & \"k\"";
if (true) return __c.NumberFormat(_number/(double)1000,(int) (1),(int) (1))+"k";
 }else {
RDebugUtils.currentLine=1703942;
 //BA.debugLineNum = 1703942;BA.debugLine="Return NumberFormat(number, 1, 0)";
if (true) return __c.NumberFormat(_number,(int) (1),(int) (0));
 }}
;
RDebugUtils.currentLine=1703944;
 //BA.debugLineNum = 1703944;BA.debugLine="End Sub";
return "";
}
public String  _formatnumberwithlabel(b4a.example.bargraph __ref,int _number) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "formatnumberwithlabel", false))
	 {return ((String) Debug.delegate(ba, "formatnumberwithlabel", new Object[] {_number}));}
RDebugUtils.currentLine=1769472;
 //BA.debugLineNum = 1769472;BA.debugLine="Sub FormatNumberWithLabel(number As Int) As String";
RDebugUtils.currentLine=1769473;
 //BA.debugLineNum = 1769473;BA.debugLine="If number >= 1000000 Then";
if (_number>=1000000) { 
RDebugUtils.currentLine=1769474;
 //BA.debugLineNum = 1769474;BA.debugLine="Return Floor(number / 1000000) & \"M\"";
if (true) return BA.NumberToString(__c.Floor(_number/(double)1000000))+"M";
 }else 
{RDebugUtils.currentLine=1769475;
 //BA.debugLineNum = 1769475;BA.debugLine="Else If number >= 1000 Then";
if (_number>=1000) { 
RDebugUtils.currentLine=1769476;
 //BA.debugLineNum = 1769476;BA.debugLine="Return Floor(number / 1000) & \"k\"";
if (true) return BA.NumberToString(__c.Floor(_number/(double)1000))+"k";
 }else {
RDebugUtils.currentLine=1769478;
 //BA.debugLineNum = 1769478;BA.debugLine="Return number";
if (true) return BA.NumberToString(_number);
 }}
;
RDebugUtils.currentLine=1769480;
 //BA.debugLineNum = 1769480;BA.debugLine="End Sub";
return "";
}
public int  _getcurrentpage(b4a.example.bargraph __ref) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "getcurrentpage", false))
	 {return ((Integer) Debug.delegate(ba, "getcurrentpage", null));}
RDebugUtils.currentLine=1507328;
 //BA.debugLineNum = 1507328;BA.debugLine="Public Sub GetCurrentPage As Int";
RDebugUtils.currentLine=1507329;
 //BA.debugLineNum = 1507329;BA.debugLine="Return currentPage";
if (true) return __ref._currentpage /*int*/ ;
RDebugUtils.currentLine=1507330;
 //BA.debugLineNum = 1507330;BA.debugLine="End Sub";
return 0;
}
public String  _productlabel_click(b4a.example.bargraph __ref) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "productlabel_click", false))
	 {return ((String) Debug.delegate(ba, "productlabel_click", null));}
anywheresoftware.b4a.objects.LabelWrapper _clickedlabel = null;
int _selectedcompany = 0;
RDebugUtils.currentLine=1638400;
 //BA.debugLineNum = 1638400;BA.debugLine="Sub productLabel_Click";
RDebugUtils.currentLine=1638401;
 //BA.debugLineNum = 1638401;BA.debugLine="Dim clickedLabel As Label = Sender";
_clickedlabel = new anywheresoftware.b4a.objects.LabelWrapper();
_clickedlabel = (anywheresoftware.b4a.objects.LabelWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.LabelWrapper(), (android.widget.TextView)(__c.Sender(ba)));
RDebugUtils.currentLine=1638402;
 //BA.debugLineNum = 1638402;BA.debugLine="Dim selectedCompany As Int = clickedLabel.Tag";
_selectedcompany = (int)(BA.ObjectToNumber(_clickedlabel.getTag()));
RDebugUtils.currentLine=1638403;
 //BA.debugLineNum = 1638403;BA.debugLine="Log(\"Selected Company ID: \" & selectedCompany)";
__c.LogImpl("41638403","Selected Company ID: "+BA.NumberToString(_selectedcompany),0);
RDebugUtils.currentLine=1638404;
 //BA.debugLineNum = 1638404;BA.debugLine="Starter.company_selected = selectedCompany";
_starter._company_selected /*String*/  = BA.NumberToString(_selectedcompany);
RDebugUtils.currentLine=1638405;
 //BA.debugLineNum = 1638405;BA.debugLine="StartActivity(layout)";
__c.StartActivity(ba,(Object)(__ref._layout /*String*/ ));
RDebugUtils.currentLine=1638406;
 //BA.debugLineNum = 1638406;BA.debugLine="Active1.Finish";
__ref._active1 /*anywheresoftware.b4a.objects.ActivityWrapper*/ .Finish();
RDebugUtils.currentLine=1638407;
 //BA.debugLineNum = 1638407;BA.debugLine="End Sub";
return "";
}
}