package b4a.example;


import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.B4AClass;
import anywheresoftware.b4a.BALayout;
import anywheresoftware.b4a.debug.*;

public class bargraph extends B4AClass.ImplB4AClass implements BA.SubDelegator{
    private static java.util.HashMap<String, java.lang.reflect.Method> htSubs;
    private void innerInitialize(BA _ba) throws Exception {
        if (ba == null) {
            ba = new anywheresoftware.b4a.ShellBA(_ba, this, htSubs, "b4a.example.bargraph");
            if (htSubs == null) {
                ba.loadHtSubs(this.getClass());
                htSubs = ba.htSubs;
            }
            
        }
        if (BA.isShellModeRuntimeCheck(ba)) 
			   this.getClass().getMethod("_class_globals", b4a.example.bargraph.class).invoke(this, new Object[] {null});
        else
            ba.raiseEvent2(null, true, "class_globals", false);
    }

 
    public void  innerInitializeHelper(anywheresoftware.b4a.BA _ba) throws Exception{
        innerInitialize(_ba);
    }
    public Object callSub(String sub, Object sender, Object[] args) throws Exception {
        return BA.SubDelegator.SubNotFound;
    }
public anywheresoftware.b4a.keywords.Common __c = null;
public anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[] _checkboxes = null;
public boolean[] _checkedsales = null;
public int[] _color = null;
public anywheresoftware.b4a.objects.PanelWrapper _legendpanel = null;
public anywheresoftware.b4a.objects.PanelWrapper _sortpanels = null;
public anywheresoftware.b4a.objects.PanelWrapper _radiopanel = null;
public anywheresoftware.b4a.objects.PanelWrapper _salespanels = null;
public anywheresoftware.b4a.objects.LabelWrapper _radiolabelsalestitles = null;
public anywheresoftware.b4a.objects.LabelWrapper _radiolabelsorttitles = null;
public anywheresoftware.b4a.objects.LabelWrapper _radiolabellegendtitles = null;
public anywheresoftware.b4a.objects.ActivityWrapper _active1 = null;
public anywheresoftware.b4a.objects.PanelWrapper _panel_l = null;
public int[] _sale_1 = null;
public int[] _sale_2 = null;
public int[] _sale_3 = null;
public String[] _product1 = null;
public String[] _legend1 = null;
public int _maxsales1 = 0;
public String _titlestring1 = "";
public int[] _comid1 = null;
public int _currentpage = 0;
public int _itemsperpage = 0;
public anywheresoftware.b4a.objects.ButtonWrapper _btnnext = null;
public anywheresoftware.b4a.objects.ButtonWrapper _btnback = null;
public anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sortbtn1 = null;
public anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sortbtn2 = null;
public anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _defbtn = null;
public anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sales1 = null;
public anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sales2 = null;
public anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sales3 = null;
public String _layout = "";
public boolean _isfirstinit = false;
public b4a.example.main _main = null;
public b4a.example.branch _branch = null;
public b4a.example.device _device = null;
public b4a.example.starter _starter = null;
public b4a.example.httputils2service _httputils2service = null;
public String  _initialize(b4a.example.bargraph __ref,anywheresoftware.b4a.BA _ba,anywheresoftware.b4a.objects.ActivityWrapper _active,anywheresoftware.b4a.objects.PanelWrapper _panel,int[] _sale1,int[] _sale2,int[] _sale3,String[] _product,String[] _legend,int _maxsales,String _titlestring,int[] _comid,String _layout1,anywheresoftware.b4a.objects.ButtonWrapper _nextbtn,anywheresoftware.b4a.objects.ButtonWrapper _backbtn,anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sortbtn,anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _btnsort2,anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _defaultbtn,anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sales1btn,anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sales2btn,anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sales3btn) throws Exception{
__ref = this;
innerInitialize(_ba);
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "initialize", false))
	 {return ((String) Debug.delegate(ba, "initialize", new Object[] {_ba,_active,_panel,_sale1,_sale2,_sale3,_product,_legend,_maxsales,_titlestring,_comid,_layout1,_nextbtn,_backbtn,_sortbtn,_btnsort2,_defaultbtn,_sales1btn,_sales2btn,_sales3btn}));}
anywheresoftware.b4a.objects.PanelWrapper _borderpanel = null;
int _legendwidth = 0;
anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[] _tempcheckboxes = null;
boolean[] _tempcheckedsales = null;
int _i = 0;
anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper _chk = null;
anywheresoftware.b4a.objects.drawable.ColorDrawable _cdback = null;
anywheresoftware.b4a.objects.drawable.ColorDrawable _cdnext = null;
anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper[] _radiobuttons = null;
String[] _radiotexts = null;
int _totalbuttons = 0;
int _buttonwidth = 0;
int _spacing = 0;
anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper[] _saleslabels = null;
String[] _salestexts = null;
int _totallabels = 0;
int _labelwidth = 0;
RDebugUtils.currentLine=4653056;
 //BA.debugLineNum = 4653056;BA.debugLine="Public Sub Initialize(Active As Activity, panel As";
RDebugUtils.currentLine=4653057;
 //BA.debugLineNum = 4653057;BA.debugLine="If Active.IsInitialized = False Then";
if (_active.IsInitialized()==__c.False) { 
RDebugUtils.currentLine=4653058;
 //BA.debugLineNum = 4653058;BA.debugLine="Log(\"Error: Activity is not initialized\")";
__c.LogImpl("54653058","Error: Activity is not initialized",0);
RDebugUtils.currentLine=4653059;
 //BA.debugLineNum = 4653059;BA.debugLine="Return";
if (true) return "";
 };
RDebugUtils.currentLine=4653061;
 //BA.debugLineNum = 4653061;BA.debugLine="Active1 = Active";
__ref._active1 /*anywheresoftware.b4a.objects.ActivityWrapper*/  = _active;
RDebugUtils.currentLine=4653062;
 //BA.debugLineNum = 4653062;BA.debugLine="panel_l = panel";
__ref._panel_l /*anywheresoftware.b4a.objects.PanelWrapper*/  = _panel;
RDebugUtils.currentLine=4653063;
 //BA.debugLineNum = 4653063;BA.debugLine="sale_1 = sale1";
__ref._sale_1 /*int[]*/  = _sale1;
RDebugUtils.currentLine=4653064;
 //BA.debugLineNum = 4653064;BA.debugLine="sale_2 = sale2";
__ref._sale_2 /*int[]*/  = _sale2;
RDebugUtils.currentLine=4653065;
 //BA.debugLineNum = 4653065;BA.debugLine="sale_3 = sale3";
__ref._sale_3 /*int[]*/  = _sale3;
RDebugUtils.currentLine=4653066;
 //BA.debugLineNum = 4653066;BA.debugLine="product1 = product";
__ref._product1 /*String[]*/  = _product;
RDebugUtils.currentLine=4653067;
 //BA.debugLineNum = 4653067;BA.debugLine="legend1 = legend";
__ref._legend1 /*String[]*/  = _legend;
RDebugUtils.currentLine=4653068;
 //BA.debugLineNum = 4653068;BA.debugLine="maxSales1 = maxSales";
__ref._maxsales1 /*int*/  = _maxsales;
RDebugUtils.currentLine=4653069;
 //BA.debugLineNum = 4653069;BA.debugLine="titleString1 = TitleString";
__ref._titlestring1 /*String*/  = _titlestring;
RDebugUtils.currentLine=4653070;
 //BA.debugLineNum = 4653070;BA.debugLine="comId1 = comId";
__ref._comid1 /*int[]*/  = _comid;
RDebugUtils.currentLine=4653071;
 //BA.debugLineNum = 4653071;BA.debugLine="layout = layout1";
__ref._layout /*String*/  = _layout1;
RDebugUtils.currentLine=4653072;
 //BA.debugLineNum = 4653072;BA.debugLine="btnNext = NextBtn";
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/  = _nextbtn;
RDebugUtils.currentLine=4653073;
 //BA.debugLineNum = 4653073;BA.debugLine="btnBack = Backbtn";
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/  = _backbtn;
RDebugUtils.currentLine=4653074;
 //BA.debugLineNum = 4653074;BA.debugLine="sortBtn1 = sortBtn";
__ref._sortbtn1 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/  = _sortbtn;
RDebugUtils.currentLine=4653075;
 //BA.debugLineNum = 4653075;BA.debugLine="sortBtn2 = BtnSort2";
__ref._sortbtn2 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/  = _btnsort2;
RDebugUtils.currentLine=4653076;
 //BA.debugLineNum = 4653076;BA.debugLine="defBtn = Defaultbtn";
__ref._defbtn /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/  = _defaultbtn;
RDebugUtils.currentLine=4653077;
 //BA.debugLineNum = 4653077;BA.debugLine="sales1 = Sales1btn";
__ref._sales1 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/  = _sales1btn;
RDebugUtils.currentLine=4653078;
 //BA.debugLineNum = 4653078;BA.debugLine="sales2 = Sales2btn";
__ref._sales2 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/  = _sales2btn;
RDebugUtils.currentLine=4653079;
 //BA.debugLineNum = 4653079;BA.debugLine="sales3 = Sales3btn";
__ref._sales3 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/  = _sales3btn;
RDebugUtils.currentLine=4653081;
 //BA.debugLineNum = 4653081;BA.debugLine="If sale1.Length <> product.Length Or sale2.Length";
if (_sale1.length!=_product.length || _sale2.length!=_product.length || _sale3.length!=_product.length) { 
RDebugUtils.currentLine=4653082;
 //BA.debugLineNum = 4653082;BA.debugLine="Return";
if (true) return "";
 };
RDebugUtils.currentLine=4653085;
 //BA.debugLineNum = 4653085;BA.debugLine="legendPanel.Initialize(\"\")";
__ref._legendpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .Initialize(ba,"");
RDebugUtils.currentLine=4653086;
 //BA.debugLineNum = 4653086;BA.debugLine="legendPanel.Width = panel.Width/2";
__ref._legendpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .setWidth((int) (_panel.getWidth()/(double)2));
RDebugUtils.currentLine=4653087;
 //BA.debugLineNum = 4653087;BA.debugLine="legendPanel.Height = 30dip";
__ref._legendpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .setHeight(__c.DipToCurrent((int) (30)));
RDebugUtils.currentLine=4653089;
 //BA.debugLineNum = 4653089;BA.debugLine="sortPanels.Initialize(\"\")";
__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .Initialize(ba,"");
RDebugUtils.currentLine=4653090;
 //BA.debugLineNum = 4653090;BA.debugLine="sortPanels.Width = panel.Width/2";
__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .setWidth((int) (_panel.getWidth()/(double)2));
RDebugUtils.currentLine=4653091;
 //BA.debugLineNum = 4653091;BA.debugLine="sortPanels.Height = 30dip";
__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .setHeight(__c.DipToCurrent((int) (30)));
RDebugUtils.currentLine=4653093;
 //BA.debugLineNum = 4653093;BA.debugLine="salesPanels.Initialize(\"\")";
__ref._salespanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .Initialize(ba,"");
RDebugUtils.currentLine=4653094;
 //BA.debugLineNum = 4653094;BA.debugLine="salesPanels.Width = panel.Width / 2 ' Half of the";
__ref._salespanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .setWidth((int) (_panel.getWidth()/(double)2));
RDebugUtils.currentLine=4653095;
 //BA.debugLineNum = 4653095;BA.debugLine="salesPanels.Height = 30dip ' Height remains the s";
__ref._salespanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .setHeight(__c.DipToCurrent((int) (30)));
RDebugUtils.currentLine=4653097;
 //BA.debugLineNum = 4653097;BA.debugLine="radioPanel.Initialize(\"\")";
__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .Initialize(ba,"");
RDebugUtils.currentLine=4653098;
 //BA.debugLineNum = 4653098;BA.debugLine="radioPanel.Width = panel.Width/2";
__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .setWidth((int) (_panel.getWidth()/(double)2));
RDebugUtils.currentLine=4653099;
 //BA.debugLineNum = 4653099;BA.debugLine="radioPanel.Height = 30dip";
__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .setHeight(__c.DipToCurrent((int) (30)));
RDebugUtils.currentLine=4653101;
 //BA.debugLineNum = 4653101;BA.debugLine="radioLabelSalesTitles.Initialize(\"radioLabelSales";
__ref._radiolabelsalestitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .Initialize(ba,"radioLabelSalesTitles");
RDebugUtils.currentLine=4653102;
 //BA.debugLineNum = 4653102;BA.debugLine="radioLabelLegendTitles.Initialize(\"radioLabelLege";
__ref._radiolabellegendtitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .Initialize(ba,"radioLabelLegendTitles");
RDebugUtils.currentLine=4653103;
 //BA.debugLineNum = 4653103;BA.debugLine="radioLabelSortTitles.Initialize(\"radioLabelSortTi";
__ref._radiolabelsorttitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .Initialize(ba,"radioLabelSortTitles");
RDebugUtils.currentLine=4653105;
 //BA.debugLineNum = 4653105;BA.debugLine="radioPanel.Color = Colors.Transparent ' Keep it t";
__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .setColor(__c.Colors.Transparent);
RDebugUtils.currentLine=4653106;
 //BA.debugLineNum = 4653106;BA.debugLine="Dim borderPanel As Panel";
_borderpanel = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=4653107;
 //BA.debugLineNum = 4653107;BA.debugLine="borderPanel.Initialize(\"\")";
_borderpanel.Initialize(ba,"");
RDebugUtils.currentLine=4653108;
 //BA.debugLineNum = 4653108;BA.debugLine="borderPanel.Color = Colors.Black ' Border color";
_borderpanel.setColor(__c.Colors.Black);
RDebugUtils.currentLine=4653109;
 //BA.debugLineNum = 4653109;BA.debugLine="panel.AddView(borderPanel, radioPanel.Left, radio";
_panel.AddView((android.view.View)(_borderpanel.getObject()),__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getLeft(),__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getTop(),__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getWidth(),__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getHeight());
RDebugUtils.currentLine=4653110;
 //BA.debugLineNum = 4653110;BA.debugLine="panel.AddView(radioPanel, radioPanel.Left + 1dip,";
_panel.AddView((android.view.View)(__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getObject()),(int) (__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getLeft()+__c.DipToCurrent((int) (1))),(int) (__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getTop()+__c.DipToCurrent((int) (1))),(int) (__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getWidth()-__c.DipToCurrent((int) (2))),(int) (__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getHeight()-__c.DipToCurrent((int) (2))));
RDebugUtils.currentLine=4653116;
 //BA.debugLineNum = 4653116;BA.debugLine="Dim legendWidth As Int = legendPanel.Width / lege";
_legendwidth = (int) (__ref._legendpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getWidth()/(double)_legend.length);
RDebugUtils.currentLine=4653117;
 //BA.debugLineNum = 4653117;BA.debugLine="checkBoxes = Array As CheckBox()";
__ref._checkboxes /*anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[]*/  = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[]{};
RDebugUtils.currentLine=4653118;
 //BA.debugLineNum = 4653118;BA.debugLine="checkedSales = Array As Boolean()";
__ref._checkedsales /*boolean[]*/  = new boolean[]{};
RDebugUtils.currentLine=4653120;
 //BA.debugLineNum = 4653120;BA.debugLine="Dim checkBoxes(legend.Length) As CheckBox";
_checkboxes = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[_legend.length];
{
int d0 = _checkboxes.length;
for (int i0 = 0;i0 < d0;i0++) {
_checkboxes[i0] = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper();
}
}
;
RDebugUtils.currentLine=4653121;
 //BA.debugLineNum = 4653121;BA.debugLine="Dim checkedSales(legend.Length) As Boolean";
_checkedsales = new boolean[_legend.length];
;
RDebugUtils.currentLine=4653122;
 //BA.debugLineNum = 4653122;BA.debugLine="If isFirstInit Then";
if (__ref._isfirstinit /*boolean*/ ) { 
RDebugUtils.currentLine=4653124;
 //BA.debugLineNum = 4653124;BA.debugLine="Dim tempCheckBoxes(legend.Length) As CheckBox";
_tempcheckboxes = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[_legend.length];
{
int d0 = _tempcheckboxes.length;
for (int i0 = 0;i0 < d0;i0++) {
_tempcheckboxes[i0] = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper();
}
}
;
RDebugUtils.currentLine=4653125;
 //BA.debugLineNum = 4653125;BA.debugLine="checkBoxes = tempCheckBoxes";
__ref._checkboxes /*anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[]*/  = _tempcheckboxes;
RDebugUtils.currentLine=4653126;
 //BA.debugLineNum = 4653126;BA.debugLine="Dim tempCheckedSales(legend.Length) As Boolean";
_tempcheckedsales = new boolean[_legend.length];
;
RDebugUtils.currentLine=4653127;
 //BA.debugLineNum = 4653127;BA.debugLine="checkedSales = tempCheckedSales";
__ref._checkedsales /*boolean[]*/  = _tempcheckedsales;
RDebugUtils.currentLine=4653130;
 //BA.debugLineNum = 4653130;BA.debugLine="For i = 0 To legend.Length - 1";
{
final int step58 = 1;
final int limit58 = (int) (_legend.length-1);
_i = (int) (0) ;
for (;_i <= limit58 ;_i = _i + step58 ) {
RDebugUtils.currentLine=4653131;
 //BA.debugLineNum = 4653131;BA.debugLine="Dim chk As CheckBox";
_chk = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper();
RDebugUtils.currentLine=4653132;
 //BA.debugLineNum = 4653132;BA.debugLine="chk.Initialize(\"chkChange\")";
_chk.Initialize(ba,"chkChange");
RDebugUtils.currentLine=4653133;
 //BA.debugLineNum = 4653133;BA.debugLine="chk.Text = legend(i)";
_chk.setText(BA.ObjectToCharSequence(_legend[_i]));
RDebugUtils.currentLine=4653134;
 //BA.debugLineNum = 4653134;BA.debugLine="chk.TextSize = 10";
_chk.setTextSize((float) (10));
RDebugUtils.currentLine=4653135;
 //BA.debugLineNum = 4653135;BA.debugLine="chk.Typeface = Typeface.MONOSPACE";
_chk.setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=4653136;
 //BA.debugLineNum = 4653136;BA.debugLine="chk.TextColor = color(i)";
_chk.setTextColor(__ref._color /*int[]*/ [_i]);
RDebugUtils.currentLine=4653137;
 //BA.debugLineNum = 4653137;BA.debugLine="chk.Tag = i";
_chk.setTag((Object)(_i));
RDebugUtils.currentLine=4653138;
 //BA.debugLineNum = 4653138;BA.debugLine="chk.Checked = True  ' Default state";
_chk.setChecked(__c.True);
RDebugUtils.currentLine=4653139;
 //BA.debugLineNum = 4653139;BA.debugLine="checkedSales(i) = True";
__ref._checkedsales /*boolean[]*/ [_i] = __c.True;
RDebugUtils.currentLine=4653140;
 //BA.debugLineNum = 4653140;BA.debugLine="legendPanel.AddView(chk, (legendWidth * i) + 30";
__ref._legendpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(_chk.getObject()),(int) ((_legendwidth*_i)+__c.DipToCurrent((int) (30))),__c.DipToCurrent((int) (0)),(int) (_legendwidth-__c.DipToCurrent((int) (30))),__ref._legendpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getHeight());
RDebugUtils.currentLine=4653141;
 //BA.debugLineNum = 4653141;BA.debugLine="checkBoxes(i) = chk";
__ref._checkboxes /*anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[]*/ [_i] = _chk;
 }
};
RDebugUtils.currentLine=4653143;
 //BA.debugLineNum = 4653143;BA.debugLine="isFirstInit = False";
__ref._isfirstinit /*boolean*/  = __c.False;
 }else {
RDebugUtils.currentLine=4653146;
 //BA.debugLineNum = 4653146;BA.debugLine="For i = 0 To checkBoxes.Length - 1";
{
final int step73 = 1;
final int limit73 = (int) (__ref._checkboxes /*anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[]*/ .length-1);
_i = (int) (0) ;
for (;_i <= limit73 ;_i = _i + step73 ) {
RDebugUtils.currentLine=4653147;
 //BA.debugLineNum = 4653147;BA.debugLine="checkBoxes(i).Checked = checkedSales(i)";
__ref._checkboxes /*anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[]*/ [_i].setChecked(__ref._checkedsales /*boolean[]*/ [_i]);
 }
};
 };
RDebugUtils.currentLine=4653153;
 //BA.debugLineNum = 4653153;BA.debugLine="btnBack.Text = \"Back\"";
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setText(BA.ObjectToCharSequence("Back"));
RDebugUtils.currentLine=4653154;
 //BA.debugLineNum = 4653154;BA.debugLine="btnBack.TextSize = 14";
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setTextSize((float) (14));
RDebugUtils.currentLine=4653155;
 //BA.debugLineNum = 4653155;BA.debugLine="btnBack.Typeface = Typeface.MONOSPACE";
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=4653156;
 //BA.debugLineNum = 4653156;BA.debugLine="btnBack.TextColor = Colors.White";
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setTextColor(__c.Colors.White);
RDebugUtils.currentLine=4653157;
 //BA.debugLineNum = 4653157;BA.debugLine="Dim cdBack As ColorDrawable";
_cdback = new anywheresoftware.b4a.objects.drawable.ColorDrawable();
RDebugUtils.currentLine=4653158;
 //BA.debugLineNum = 4653158;BA.debugLine="cdBack.Initialize2(Colors.RGB(61, 12, 2), 10dip,";
_cdback.Initialize2(__c.Colors.RGB((int) (61),(int) (12),(int) (2)),__c.DipToCurrent((int) (10)),__c.DipToCurrent((int) (2)),__c.Colors.Black);
RDebugUtils.currentLine=4653159;
 //BA.debugLineNum = 4653159;BA.debugLine="btnBack.Background = cdBack";
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setBackground((android.graphics.drawable.Drawable)(_cdback.getObject()));
RDebugUtils.currentLine=4653162;
 //BA.debugLineNum = 4653162;BA.debugLine="btnNext.Text = \"Next\"";
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setText(BA.ObjectToCharSequence("Next"));
RDebugUtils.currentLine=4653163;
 //BA.debugLineNum = 4653163;BA.debugLine="btnNext.TextSize = 14";
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setTextSize((float) (14));
RDebugUtils.currentLine=4653164;
 //BA.debugLineNum = 4653164;BA.debugLine="btnNext.Typeface = Typeface.MONOSPACE";
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=4653165;
 //BA.debugLineNum = 4653165;BA.debugLine="btnNext.TextColor = Colors.White";
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setTextColor(__c.Colors.White);
RDebugUtils.currentLine=4653166;
 //BA.debugLineNum = 4653166;BA.debugLine="Dim cdNext As ColorDrawable";
_cdnext = new anywheresoftware.b4a.objects.drawable.ColorDrawable();
RDebugUtils.currentLine=4653167;
 //BA.debugLineNum = 4653167;BA.debugLine="cdNext.Initialize2(Colors.RGB(185, 46, 52), 10dip";
_cdnext.Initialize2(__c.Colors.RGB((int) (185),(int) (46),(int) (52)),__c.DipToCurrent((int) (10)),__c.DipToCurrent((int) (2)),__c.Colors.Black);
RDebugUtils.currentLine=4653168;
 //BA.debugLineNum = 4653168;BA.debugLine="btnNext.Background = cdNext";
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setBackground((android.graphics.drawable.Drawable)(_cdnext.getObject()));
RDebugUtils.currentLine=4653170;
 //BA.debugLineNum = 4653170;BA.debugLine="Dim radioButtons() As RadioButton = Array As Radi";
_radiobuttons = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper[]{__ref._sortbtn1 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/ ,__ref._sortbtn2 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/ ,__ref._defbtn /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/ };
RDebugUtils.currentLine=4653171;
 //BA.debugLineNum = 4653171;BA.debugLine="Dim radioTexts() As String = Array As String(\"ASC";
_radiotexts = new String[]{"ASC","DESC","DEFAULT"};
RDebugUtils.currentLine=4653173;
 //BA.debugLineNum = 4653173;BA.debugLine="If sortPanels.Width = 0 Then";
if (__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .getWidth()==0) { 
RDebugUtils.currentLine=4653174;
 //BA.debugLineNum = 4653174;BA.debugLine="sortPanels.Width = panel.Width / 2 ' Default wid";
__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .setWidth((int) (_panel.getWidth()/(double)2));
 };
RDebugUtils.currentLine=4653177;
 //BA.debugLineNum = 4653177;BA.debugLine="Dim totalButtons As Int = radioButtons.Length";
_totalbuttons = _radiobuttons.length;
RDebugUtils.currentLine=4653178;
 //BA.debugLineNum = 4653178;BA.debugLine="Dim buttonWidth As Int = (sortPanels.Width - (tot";
_buttonwidth = (int) ((__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .getWidth()-(_totalbuttons*__c.DipToCurrent((int) (5))))/(double)_totalbuttons);
RDebugUtils.currentLine=4653179;
 //BA.debugLineNum = 4653179;BA.debugLine="Dim spacing As Int = 5dip ' Small gap between but";
_spacing = __c.DipToCurrent((int) (5));
RDebugUtils.currentLine=4653181;
 //BA.debugLineNum = 4653181;BA.debugLine="For i = 0 To totalButtons - 1";
{
final int step99 = 1;
final int limit99 = (int) (_totalbuttons-1);
_i = (int) (0) ;
for (;_i <= limit99 ;_i = _i + step99 ) {
RDebugUtils.currentLine=4653182;
 //BA.debugLineNum = 4653182;BA.debugLine="radioButtons(i).Text = radioTexts(i)";
_radiobuttons[_i].setText(BA.ObjectToCharSequence(_radiotexts[_i]));
RDebugUtils.currentLine=4653183;
 //BA.debugLineNum = 4653183;BA.debugLine="radioButtons(i).TextSize = 10";
_radiobuttons[_i].setTextSize((float) (10));
RDebugUtils.currentLine=4653184;
 //BA.debugLineNum = 4653184;BA.debugLine="radioButtons(i).Tag = radioTexts(i)";
_radiobuttons[_i].setTag((Object)(_radiotexts[_i]));
RDebugUtils.currentLine=4653185;
 //BA.debugLineNum = 4653185;BA.debugLine="radioButtons(i).Typeface = Typeface.MONOSPACE";
_radiobuttons[_i].setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=4653186;
 //BA.debugLineNum = 4653186;BA.debugLine="radioButtons(i).TextColor = Colors.Black";
_radiobuttons[_i].setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=4653188;
 //BA.debugLineNum = 4653188;BA.debugLine="Dim cdNext As ColorDrawable";
_cdnext = new anywheresoftware.b4a.objects.drawable.ColorDrawable();
RDebugUtils.currentLine=4653189;
 //BA.debugLineNum = 4653189;BA.debugLine="cdNext.Initialize2(Colors.RGB(128, 128, 128), 10";
_cdnext.Initialize2(__c.Colors.RGB((int) (128),(int) (128),(int) (128)),__c.DipToCurrent((int) (10)),__c.DipToCurrent((int) (2)),__c.Colors.Black);
RDebugUtils.currentLine=4653192;
 //BA.debugLineNum = 4653192;BA.debugLine="sortPanels.AddView(radioButtons(i), (i * (button";
__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(_radiobuttons[_i].getObject()),(int) ((_i*(_buttonwidth+_spacing))),__c.DipToCurrent((int) (10)),_buttonwidth,__c.DipToCurrent((int) (20)));
 }
};
RDebugUtils.currentLine=4653195;
 //BA.debugLineNum = 4653195;BA.debugLine="Dim salesLabels() As RadioButton = Array As Radio";
_saleslabels = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper[]{__ref._sales1 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/ ,__ref._sales2 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/ ,__ref._sales3 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/ };
RDebugUtils.currentLine=4653196;
 //BA.debugLineNum = 4653196;BA.debugLine="Dim salesTexts() As String = Array As String(\"1\",";
_salestexts = new String[]{"1","2","3"};
RDebugUtils.currentLine=4653198;
 //BA.debugLineNum = 4653198;BA.debugLine="Dim totalLabels As Int = salesLabels.Length";
_totallabels = _saleslabels.length;
RDebugUtils.currentLine=4653199;
 //BA.debugLineNum = 4653199;BA.debugLine="Dim labelWidth As Int = (salesPanels.Width - (tot";
_labelwidth = (int) ((__ref._salespanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .getWidth()-(_totallabels*__c.DipToCurrent((int) (5))))/(double)_totallabels);
RDebugUtils.currentLine=4653200;
 //BA.debugLineNum = 4653200;BA.debugLine="Dim spacing As Int = 5dip ' Small spacing between";
_spacing = __c.DipToCurrent((int) (5));
RDebugUtils.currentLine=4653202;
 //BA.debugLineNum = 4653202;BA.debugLine="For i = 0 To totalLabels - 1";
{
final int step114 = 1;
final int limit114 = (int) (_totallabels-1);
_i = (int) (0) ;
for (;_i <= limit114 ;_i = _i + step114 ) {
RDebugUtils.currentLine=4653203;
 //BA.debugLineNum = 4653203;BA.debugLine="salesLabels(i).Text = \"Sales\" & (i + 1)";
_saleslabels[_i].setText(BA.ObjectToCharSequence("Sales"+BA.NumberToString((_i+1))));
RDebugUtils.currentLine=4653204;
 //BA.debugLineNum = 4653204;BA.debugLine="salesLabels(i).TextSize = 10";
_saleslabels[_i].setTextSize((float) (10));
RDebugUtils.currentLine=4653205;
 //BA.debugLineNum = 4653205;BA.debugLine="salesLabels(i).Tag = salesTexts(i)";
_saleslabels[_i].setTag((Object)(_salestexts[_i]));
RDebugUtils.currentLine=4653206;
 //BA.debugLineNum = 4653206;BA.debugLine="salesLabels(i).Typeface = Typeface.MONOSPACE";
_saleslabels[_i].setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=4653207;
 //BA.debugLineNum = 4653207;BA.debugLine="salesLabels(i).TextColor = Colors.Black";
_saleslabels[_i].setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=4653209;
 //BA.debugLineNum = 4653209;BA.debugLine="Dim cdBack As ColorDrawable";
_cdback = new anywheresoftware.b4a.objects.drawable.ColorDrawable();
RDebugUtils.currentLine=4653210;
 //BA.debugLineNum = 4653210;BA.debugLine="cdBack.Initialize2(Colors.RGB(128, 128, 128), 10";
_cdback.Initialize2(__c.Colors.RGB((int) (128),(int) (128),(int) (128)),__c.DipToCurrent((int) (10)),__c.DipToCurrent((int) (2)),__c.Colors.Black);
RDebugUtils.currentLine=4653214;
 //BA.debugLineNum = 4653214;BA.debugLine="salesPanels.AddView(salesLabels(i), (i * (labelW";
__ref._salespanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(_saleslabels[_i].getObject()),(int) ((_i*(_labelwidth+_spacing))),__c.DipToCurrent((int) (10)),_labelwidth,__c.DipToCurrent((int) (20)));
 }
};
RDebugUtils.currentLine=4653218;
 //BA.debugLineNum = 4653218;BA.debugLine="radioLabelSalesTitles.Text = \"Base on\"";
__ref._radiolabelsalestitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setText(BA.ObjectToCharSequence("Base on"));
RDebugUtils.currentLine=4653219;
 //BA.debugLineNum = 4653219;BA.debugLine="radioLabelSalesTitles.TextSize = 12";
__ref._radiolabelsalestitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTextSize((float) (12));
RDebugUtils.currentLine=4653220;
 //BA.debugLineNum = 4653220;BA.debugLine="radioLabelSalesTitles.Typeface = Typeface.MONOSPA";
__ref._radiolabelsalestitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=4653221;
 //BA.debugLineNum = 4653221;BA.debugLine="radioLabelSalesTitles.TextColor = Colors.Black";
__ref._radiolabelsalestitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=4653223;
 //BA.debugLineNum = 4653223;BA.debugLine="radioLabelSortTitles.Text = \"Sort By\"";
__ref._radiolabelsorttitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setText(BA.ObjectToCharSequence("Sort By"));
RDebugUtils.currentLine=4653224;
 //BA.debugLineNum = 4653224;BA.debugLine="radioLabelSortTitles.TextSize = 12";
__ref._radiolabelsorttitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTextSize((float) (12));
RDebugUtils.currentLine=4653225;
 //BA.debugLineNum = 4653225;BA.debugLine="radioLabelSortTitles.Typeface = Typeface.MONOSPAC";
__ref._radiolabelsorttitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=4653226;
 //BA.debugLineNum = 4653226;BA.debugLine="radioLabelSortTitles.TextColor = Colors.Black";
__ref._radiolabelsorttitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=4653229;
 //BA.debugLineNum = 4653229;BA.debugLine="radioLabelLegendTitles.Text = \"Shown\"";
__ref._radiolabellegendtitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setText(BA.ObjectToCharSequence("Shown"));
RDebugUtils.currentLine=4653230;
 //BA.debugLineNum = 4653230;BA.debugLine="radioLabelLegendTitles.TextSize = 12";
__ref._radiolabellegendtitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTextSize((float) (12));
RDebugUtils.currentLine=4653231;
 //BA.debugLineNum = 4653231;BA.debugLine="radioLabelLegendTitles.Typeface = Typeface.MONOSP";
__ref._radiolabellegendtitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=4653232;
 //BA.debugLineNum = 4653232;BA.debugLine="radioLabelLegendTitles.TextColor = Colors.Black";
__ref._radiolabellegendtitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=4653235;
 //BA.debugLineNum = 4653235;BA.debugLine="DrawGraph(Active, panel, sale1, sale2, sale3, pro";
__ref._drawgraph /*String*/ (null,_active,_panel,_sale1,_sale2,_sale3,_product,_maxsales,_titlestring);
RDebugUtils.currentLine=4653236;
 //BA.debugLineNum = 4653236;BA.debugLine="End Sub";
return "";
}
public String  _updategraph(b4a.example.bargraph __ref) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "updategraph", false))
	 {return ((String) Debug.delegate(ba, "updategraph", null));}
RDebugUtils.currentLine=4784128;
 //BA.debugLineNum = 4784128;BA.debugLine="Public Sub UpdateGraph";
RDebugUtils.currentLine=4784129;
 //BA.debugLineNum = 4784129;BA.debugLine="DrawGraph(Active1, panel_l, sale_1, sale_2, sale_";
__ref._drawgraph /*String*/ (null,__ref._active1 /*anywheresoftware.b4a.objects.ActivityWrapper*/ ,__ref._panel_l /*anywheresoftware.b4a.objects.PanelWrapper*/ ,__ref._sale_1 /*int[]*/ ,__ref._sale_2 /*int[]*/ ,__ref._sale_3 /*int[]*/ ,__ref._product1 /*String[]*/ ,__ref._maxsales1 /*int*/ ,__ref._titlestring1 /*String*/ );
RDebugUtils.currentLine=4784130;
 //BA.debugLineNum = 4784130;BA.debugLine="End Sub";
return "";
}
public String  _setcurrentpage(b4a.example.bargraph __ref,int _page) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "setcurrentpage", false))
	 {return ((String) Debug.delegate(ba, "setcurrentpage", new Object[] {_page}));}
RDebugUtils.currentLine=4915200;
 //BA.debugLineNum = 4915200;BA.debugLine="Public Sub SetCurrentPage(page As Int)";
RDebugUtils.currentLine=4915201;
 //BA.debugLineNum = 4915201;BA.debugLine="currentPage = page";
__ref._currentpage /*int*/  = _page;
RDebugUtils.currentLine=4915202;
 //BA.debugLineNum = 4915202;BA.debugLine="UpdateGraph";
__ref._updategraph /*String*/ (null);
RDebugUtils.currentLine=4915203;
 //BA.debugLineNum = 4915203;BA.debugLine="End Sub";
return "";
}
public String  _chkchange_checkedchange(b4a.example.bargraph __ref,boolean _checked) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "chkchange_checkedchange", false))
	 {return ((String) Debug.delegate(ba, "chkchange_checkedchange", new Object[] {_checked}));}
anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper _chk = null;
int _index = 0;
int _checkedcount = 0;
int _i = 0;
RDebugUtils.currentLine=5177344;
 //BA.debugLineNum = 5177344;BA.debugLine="Sub chkChange_CheckedChange(Checked As Boolean)";
RDebugUtils.currentLine=5177345;
 //BA.debugLineNum = 5177345;BA.debugLine="If Sender Is CheckBox Then";
if (__c.Sender(ba) instanceof android.widget.CheckBox) { 
RDebugUtils.currentLine=5177346;
 //BA.debugLineNum = 5177346;BA.debugLine="Dim chk As CheckBox = Sender";
_chk = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper();
_chk = (anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper(), (android.widget.CheckBox)(__c.Sender(ba)));
RDebugUtils.currentLine=5177347;
 //BA.debugLineNum = 5177347;BA.debugLine="Dim index As Int = chk.Tag";
_index = (int)(BA.ObjectToNumber(_chk.getTag()));
RDebugUtils.currentLine=5177349;
 //BA.debugLineNum = 5177349;BA.debugLine="Dim checkedCount As Int = 0";
_checkedcount = (int) (0);
RDebugUtils.currentLine=5177350;
 //BA.debugLineNum = 5177350;BA.debugLine="For i = 0 To checkedSales.Length - 1";
{
final int step5 = 1;
final int limit5 = (int) (__ref._checkedsales /*boolean[]*/ .length-1);
_i = (int) (0) ;
for (;_i <= limit5 ;_i = _i + step5 ) {
RDebugUtils.currentLine=5177351;
 //BA.debugLineNum = 5177351;BA.debugLine="If checkedSales(i) = True Then checkedCount = c";
if (__ref._checkedsales /*boolean[]*/ [_i]==__c.True) { 
_checkedcount = (int) (_checkedcount+1);};
 }
};
RDebugUtils.currentLine=5177354;
 //BA.debugLineNum = 5177354;BA.debugLine="If Checked = False And checkedCount = 1 Then";
if (_checked==__c.False && _checkedcount==1) { 
RDebugUtils.currentLine=5177355;
 //BA.debugLineNum = 5177355;BA.debugLine="chk.Checked = True";
_chk.setChecked(__c.True);
RDebugUtils.currentLine=5177356;
 //BA.debugLineNum = 5177356;BA.debugLine="Return";
if (true) return "";
 };
RDebugUtils.currentLine=5177359;
 //BA.debugLineNum = 5177359;BA.debugLine="checkedSales(index) = Checked";
__ref._checkedsales /*boolean[]*/ [_index] = _checked;
RDebugUtils.currentLine=5177360;
 //BA.debugLineNum = 5177360;BA.debugLine="UpdateGraph ' Call DrawGraph without parameters";
__ref._updategraph /*String*/ (null);
 }else {
RDebugUtils.currentLine=5177362;
 //BA.debugLineNum = 5177362;BA.debugLine="Log(\"Error: Sender is not a CheckBox\")";
__c.LogImpl("55177362","Error: Sender is not a CheckBox",0);
 };
RDebugUtils.currentLine=5177364;
 //BA.debugLineNum = 5177364;BA.debugLine="End Sub";
return "";
}
public String  _class_globals(b4a.example.bargraph __ref) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
RDebugUtils.currentLine=4587520;
 //BA.debugLineNum = 4587520;BA.debugLine="Sub Class_Globals";
RDebugUtils.currentLine=4587521;
 //BA.debugLineNum = 4587521;BA.debugLine="Private checkBoxes() As CheckBox";
_checkboxes = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[(int) (0)];
{
int d0 = _checkboxes.length;
for (int i0 = 0;i0 < d0;i0++) {
_checkboxes[i0] = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper();
}
}
;
RDebugUtils.currentLine=4587522;
 //BA.debugLineNum = 4587522;BA.debugLine="Public checkedSales() As Boolean";
_checkedsales = new boolean[(int) (0)];
;
RDebugUtils.currentLine=4587523;
 //BA.debugLineNum = 4587523;BA.debugLine="Dim color() As Int = Array As Int(Colors.RGB(255,";
_color = new int[]{__c.Colors.RGB((int) (255),(int) (0),(int) (0)),__c.Colors.RGB((int) (200),(int) (20),(int) (20)),__c.Colors.RGB((int) (100),(int) (10),(int) (10))};
RDebugUtils.currentLine=4587524;
 //BA.debugLineNum = 4587524;BA.debugLine="Dim legendPanel As Panel";
_legendpanel = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=4587525;
 //BA.debugLineNum = 4587525;BA.debugLine="Dim sortPanels As Panel";
_sortpanels = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=4587526;
 //BA.debugLineNum = 4587526;BA.debugLine="Dim radioPanel As Panel";
_radiopanel = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=4587527;
 //BA.debugLineNum = 4587527;BA.debugLine="Dim salesPanels As Panel";
_salespanels = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=4587528;
 //BA.debugLineNum = 4587528;BA.debugLine="Dim radioLabelSalesTitles As Label";
_radiolabelsalestitles = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=4587529;
 //BA.debugLineNum = 4587529;BA.debugLine="Dim radioLabelSortTitles As Label";
_radiolabelsorttitles = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=4587530;
 //BA.debugLineNum = 4587530;BA.debugLine="Dim radioLabelLegendTitles As Label";
_radiolabellegendtitles = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=4587531;
 //BA.debugLineNum = 4587531;BA.debugLine="Dim Active1 As Activity";
_active1 = new anywheresoftware.b4a.objects.ActivityWrapper();
RDebugUtils.currentLine=4587532;
 //BA.debugLineNum = 4587532;BA.debugLine="Dim panel_l As Panel";
_panel_l = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=4587533;
 //BA.debugLineNum = 4587533;BA.debugLine="Dim sale_1() As Int";
_sale_1 = new int[(int) (0)];
;
RDebugUtils.currentLine=4587534;
 //BA.debugLineNum = 4587534;BA.debugLine="Dim sale_2() As Int";
_sale_2 = new int[(int) (0)];
;
RDebugUtils.currentLine=4587535;
 //BA.debugLineNum = 4587535;BA.debugLine="Dim sale_3() As Int";
_sale_3 = new int[(int) (0)];
;
RDebugUtils.currentLine=4587536;
 //BA.debugLineNum = 4587536;BA.debugLine="Dim product1() As String";
_product1 = new String[(int) (0)];
java.util.Arrays.fill(_product1,"");
RDebugUtils.currentLine=4587537;
 //BA.debugLineNum = 4587537;BA.debugLine="Dim legend1() As String";
_legend1 = new String[(int) (0)];
java.util.Arrays.fill(_legend1,"");
RDebugUtils.currentLine=4587538;
 //BA.debugLineNum = 4587538;BA.debugLine="Dim maxSales1 As Int = 0";
_maxsales1 = (int) (0);
RDebugUtils.currentLine=4587539;
 //BA.debugLineNum = 4587539;BA.debugLine="Dim titleString1 As String = \"\"";
_titlestring1 = "";
RDebugUtils.currentLine=4587540;
 //BA.debugLineNum = 4587540;BA.debugLine="Dim comId1() As Int";
_comid1 = new int[(int) (0)];
;
RDebugUtils.currentLine=4587541;
 //BA.debugLineNum = 4587541;BA.debugLine="Private currentPage As Int = 1";
_currentpage = (int) (1);
RDebugUtils.currentLine=4587542;
 //BA.debugLineNum = 4587542;BA.debugLine="Private itemsPerPage As Int = 5";
_itemsperpage = (int) (5);
RDebugUtils.currentLine=4587543;
 //BA.debugLineNum = 4587543;BA.debugLine="Public btnNext As Button";
_btnnext = new anywheresoftware.b4a.objects.ButtonWrapper();
RDebugUtils.currentLine=4587544;
 //BA.debugLineNum = 4587544;BA.debugLine="Public btnBack As Button";
_btnback = new anywheresoftware.b4a.objects.ButtonWrapper();
RDebugUtils.currentLine=4587545;
 //BA.debugLineNum = 4587545;BA.debugLine="Public sortBtn1 As RadioButton";
_sortbtn1 = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper();
RDebugUtils.currentLine=4587546;
 //BA.debugLineNum = 4587546;BA.debugLine="Public sortBtn2 As RadioButton";
_sortbtn2 = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper();
RDebugUtils.currentLine=4587547;
 //BA.debugLineNum = 4587547;BA.debugLine="Public defBtn As RadioButton";
_defbtn = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper();
RDebugUtils.currentLine=4587548;
 //BA.debugLineNum = 4587548;BA.debugLine="Public sales1 As RadioButton";
_sales1 = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper();
RDebugUtils.currentLine=4587549;
 //BA.debugLineNum = 4587549;BA.debugLine="Public sales2 As RadioButton";
_sales2 = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper();
RDebugUtils.currentLine=4587550;
 //BA.debugLineNum = 4587550;BA.debugLine="Public sales3 As RadioButton";
_sales3 = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper();
RDebugUtils.currentLine=4587551;
 //BA.debugLineNum = 4587551;BA.debugLine="Dim layout As String = \"\"";
_layout = "";
RDebugUtils.currentLine=4587552;
 //BA.debugLineNum = 4587552;BA.debugLine="Private isFirstInit As Boolean = True";
_isfirstinit = __c.True;
RDebugUtils.currentLine=4587553;
 //BA.debugLineNum = 4587553;BA.debugLine="End Sub";
return "";
}
public String  _drawgraph(b4a.example.bargraph __ref,anywheresoftware.b4a.objects.ActivityWrapper _active,anywheresoftware.b4a.objects.PanelWrapper _panel,int[] _sale1,int[] _sale2,int[] _sale3,String[] _product,int _maxsales,String _titlestring) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "drawgraph", false))
	 {return ((String) Debug.delegate(ba, "drawgraph", new Object[] {_active,_panel,_sale1,_sale2,_sale3,_product,_maxsales,_titlestring}));}
int _halfwidth = 0;
int _radiolabelwidth = 0;
int _radiolabelheight = 0;
int _radiolabelx = 0;
int _radiolabely = 0;
anywheresoftware.b4a.objects.PanelWrapper _activitypanel = null;
int _alignleftcenter = 0;
int _aligntopcenter = 0;
anywheresoftware.b4a.objects.LabelWrapper _title = null;
anywheresoftware.b4a.objects.drawable.CanvasWrapper _graphcanvas = null;
int _maxsale = 0;
anywheresoftware.b4a.objects.drawable.CanvasWrapper _cv = null;
int _totalproducts = 0;
int _startindex = 0;
int _endindex = 0;
int _barsperproduct = 0;
int _totalbars = 0;
int _gap = 0;
int _productgap = 0;
int _padding = 0;
int _availablewidth = 0;
int _barwidth = 0;
int _xstart = 0;
int _i = 0;
int _xpos = 0;
int[] _salevalues = null;
int _indexoffset = 0;
int _j = 0;
int _sale = 0;
int _barheight = 0;
int _xbar = 0;
anywheresoftware.b4a.objects.drawable.CanvasWrapper.RectWrapper _r = null;
int _fontsize = 0;
anywheresoftware.b4a.objects.LabelWrapper _productlabel = null;
int _productlabely = 0;
int _productlabelx = 0;
int _numlabels = 0;
int _labelvalue = 0;
int _labelypos = 0;
int _buttonwidth = 0;
int _buttonheight = 0;
int _buttonspacing = 0;
int _graphbottom = 0;
int _buttony = 0;
int _btnbackx = 0;
int _btnnextx = 0;
RDebugUtils.currentLine=4718592;
 //BA.debugLineNum = 4718592;BA.debugLine="Public Sub DrawGraph(Active As Activity, panel As";
RDebugUtils.currentLine=4718593;
 //BA.debugLineNum = 4718593;BA.debugLine="Try";
try {RDebugUtils.currentLine=4718594;
 //BA.debugLineNum = 4718594;BA.debugLine="panel.Invalidate";
_panel.Invalidate();
RDebugUtils.currentLine=4718595;
 //BA.debugLineNum = 4718595;BA.debugLine="panel.RemoveAllViews";
_panel.RemoveAllViews();
RDebugUtils.currentLine=4718596;
 //BA.debugLineNum = 4718596;BA.debugLine="panel.Height = 450dip";
_panel.setHeight(__c.DipToCurrent((int) (450)));
RDebugUtils.currentLine=4718597;
 //BA.debugLineNum = 4718597;BA.debugLine="If panel.Width = 0 Then";
if (_panel.getWidth()==0) { 
RDebugUtils.currentLine=4718598;
 //BA.debugLineNum = 4718598;BA.debugLine="panel.Width = 800dip";
_panel.setWidth(__c.DipToCurrent((int) (800)));
 };
RDebugUtils.currentLine=4718603;
 //BA.debugLineNum = 4718603;BA.debugLine="Dim halfWidth As Int = panel.Width / 2";
_halfwidth = (int) (_panel.getWidth()/(double)2);
RDebugUtils.currentLine=4718604;
 //BA.debugLineNum = 4718604;BA.debugLine="salesPanels.Width = halfWidth ' Make salesPanels";
__ref._salespanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .setWidth(_halfwidth);
RDebugUtils.currentLine=4718605;
 //BA.debugLineNum = 4718605;BA.debugLine="salesPanels.Height = 30dip";
__ref._salespanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .setHeight(__c.DipToCurrent((int) (30)));
RDebugUtils.currentLine=4718606;
 //BA.debugLineNum = 4718606;BA.debugLine="sortPanels.Width = halfWidth";
__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .setWidth(_halfwidth);
RDebugUtils.currentLine=4718607;
 //BA.debugLineNum = 4718607;BA.debugLine="sortPanels.Height = 30dip";
__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .setHeight(__c.DipToCurrent((int) (30)));
RDebugUtils.currentLine=4718609;
 //BA.debugLineNum = 4718609;BA.debugLine="panel.AddView(legendPanel, halfWidth, 20dip, hal";
_panel.AddView((android.view.View)(__ref._legendpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getObject()),_halfwidth,__c.DipToCurrent((int) (20)),_halfwidth,__c.DipToCurrent((int) (35)));
RDebugUtils.currentLine=4718611;
 //BA.debugLineNum = 4718611;BA.debugLine="Dim radioLabelWidth As Int = halfWidth";
_radiolabelwidth = _halfwidth;
RDebugUtils.currentLine=4718612;
 //BA.debugLineNum = 4718612;BA.debugLine="Dim radioLabelHeight As Int = 35dip";
_radiolabelheight = __c.DipToCurrent((int) (35));
RDebugUtils.currentLine=4718613;
 //BA.debugLineNum = 4718613;BA.debugLine="Dim radioLabelX As Int = (panel.Width - radioLab";
_radiolabelx = (int) ((_panel.getWidth()-_radiolabelwidth)/(double)2+__c.DipToCurrent((int) (170)));
RDebugUtils.currentLine=4718614;
 //BA.debugLineNum = 4718614;BA.debugLine="Dim radioLabelY As Int = 5dip";
_radiolabely = __c.DipToCurrent((int) (5));
RDebugUtils.currentLine=4718616;
 //BA.debugLineNum = 4718616;BA.debugLine="radioLabelSalesTitles.Visible = sale1.Length >=";
__ref._radiolabelsalestitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setVisible(_sale1.length>=5);
RDebugUtils.currentLine=4718617;
 //BA.debugLineNum = 4718617;BA.debugLine="radioLabelSortTitles.Visible = sale1.Length >= 5";
__ref._radiolabelsorttitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setVisible(_sale1.length>=5);
RDebugUtils.currentLine=4718619;
 //BA.debugLineNum = 4718619;BA.debugLine="panel.AddView(radioLabelLegendTitles, halfWidth+";
_panel.AddView((android.view.View)(__ref._radiolabellegendtitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .getObject()),(int) (_halfwidth+__c.DipToCurrent((int) (47))),_radiolabely,_radiolabelwidth,_radiolabelheight);
RDebugUtils.currentLine=4718621;
 //BA.debugLineNum = 4718621;BA.debugLine="If sale1.Length >=5 Then";
if (_sale1.length>=5) { 
RDebugUtils.currentLine=4718622;
 //BA.debugLineNum = 4718622;BA.debugLine="panel.AddView(radioLabelSalesTitles, 0, radioLa";
_panel.AddView((android.view.View)(__ref._radiolabelsalestitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .getObject()),(int) (0),_radiolabely,_radiolabelwidth,_radiolabelheight);
RDebugUtils.currentLine=4718623;
 //BA.debugLineNum = 4718623;BA.debugLine="panel.AddView(radioLabelSortTitles, 0, radioLab";
_panel.AddView((android.view.View)(__ref._radiolabelsorttitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .getObject()),(int) (0),(int) (_radiolabely+__c.DipToCurrent((int) (48))),_radiolabelwidth,_radiolabelheight);
RDebugUtils.currentLine=4718624;
 //BA.debugLineNum = 4718624;BA.debugLine="panel.AddView(salesPanels, 0dip, 20dip, halfWid";
_panel.AddView((android.view.View)(__ref._salespanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .getObject()),__c.DipToCurrent((int) (0)),__c.DipToCurrent((int) (20)),_halfwidth,__c.DipToCurrent((int) (35)));
RDebugUtils.currentLine=4718625;
 //BA.debugLineNum = 4718625;BA.debugLine="panel.AddView(sortPanels, 0dip, 60dip, halfWidt";
_panel.AddView((android.view.View)(__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .getObject()),__c.DipToCurrent((int) (0)),__c.DipToCurrent((int) (60)),_halfwidth,__c.DipToCurrent((int) (38)));
 };
RDebugUtils.currentLine=4718631;
 //BA.debugLineNum = 4718631;BA.debugLine="Dim activityPanel As Panel";
_activitypanel = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=4718632;
 //BA.debugLineNum = 4718632;BA.debugLine="activityPanel.Initialize(\"activityPanel\")";
_activitypanel.Initialize(ba,"activityPanel");
RDebugUtils.currentLine=4718634;
 //BA.debugLineNum = 4718634;BA.debugLine="activityPanel.Width = 80%x";
_activitypanel.setWidth(__c.PerXToCurrent((float) (80),ba));
RDebugUtils.currentLine=4718635;
 //BA.debugLineNum = 4718635;BA.debugLine="If Active.Width > 800 Then";
if (_active.getWidth()>800) { 
RDebugUtils.currentLine=4718636;
 //BA.debugLineNum = 4718636;BA.debugLine="activityPanel.Width = 55%x";
_activitypanel.setWidth(__c.PerXToCurrent((float) (55),ba));
 };
RDebugUtils.currentLine=4718638;
 //BA.debugLineNum = 4718638;BA.debugLine="activityPanel.Height = 250dip";
_activitypanel.setHeight(__c.DipToCurrent((int) (250)));
RDebugUtils.currentLine=4718639;
 //BA.debugLineNum = 4718639;BA.debugLine="activityPanel.Color = Colors.ARGB(70, 211, 211,";
_activitypanel.setColor(__c.Colors.ARGB((int) (70),(int) (211),(int) (211),(int) (211)));
RDebugUtils.currentLine=4718641;
 //BA.debugLineNum = 4718641;BA.debugLine="Dim alignLeftCenter As Int = (Active.Width - act";
_alignleftcenter = (int) ((_active.getWidth()-_activitypanel.getWidth())/(double)2);
RDebugUtils.currentLine=4718642;
 //BA.debugLineNum = 4718642;BA.debugLine="Dim alignTopCenter As Int = (panel.Height - acti";
_aligntopcenter = (int) ((_panel.getHeight()-_activitypanel.getHeight())/(double)2-__c.DipToCurrent((int) (20)));
RDebugUtils.currentLine=4718644;
 //BA.debugLineNum = 4718644;BA.debugLine="Dim Title As Label";
_title = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=4718645;
 //BA.debugLineNum = 4718645;BA.debugLine="Title.Initialize(\"\")";
_title.Initialize(ba,"");
RDebugUtils.currentLine=4718646;
 //BA.debugLineNum = 4718646;BA.debugLine="Title.Text = TitleString";
_title.setText(BA.ObjectToCharSequence(_titlestring));
RDebugUtils.currentLine=4718647;
 //BA.debugLineNum = 4718647;BA.debugLine="Title.TextSize = 20";
_title.setTextSize((float) (20));
RDebugUtils.currentLine=4718648;
 //BA.debugLineNum = 4718648;BA.debugLine="Title.Typeface = Typeface.MONOSPACE";
_title.setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=4718649;
 //BA.debugLineNum = 4718649;BA.debugLine="Title.Gravity = Gravity.CENTER";
_title.setGravity(__c.Gravity.CENTER);
RDebugUtils.currentLine=4718650;
 //BA.debugLineNum = 4718650;BA.debugLine="Title.TextColor = Colors.Black";
_title.setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=4718651;
 //BA.debugLineNum = 4718651;BA.debugLine="panel.AddView(Title, 0, alignTopCenter / 2 +55di";
_panel.AddView((android.view.View)(_title.getObject()),(int) (0),(int) (_aligntopcenter/(double)2+__c.DipToCurrent((int) (55))),_panel.getWidth(),__c.DipToCurrent((int) (30)));
RDebugUtils.currentLine=4718653;
 //BA.debugLineNum = 4718653;BA.debugLine="panel.AddView(activityPanel, alignLeftCenter, al";
_panel.AddView((android.view.View)(_activitypanel.getObject()),_alignleftcenter,(int) (_aligntopcenter+__c.DipToCurrent((int) (47))),_activitypanel.getWidth(),_activitypanel.getHeight());
RDebugUtils.currentLine=4718655;
 //BA.debugLineNum = 4718655;BA.debugLine="Dim graphCanvas As Canvas";
_graphcanvas = new anywheresoftware.b4a.objects.drawable.CanvasWrapper();
RDebugUtils.currentLine=4718656;
 //BA.debugLineNum = 4718656;BA.debugLine="graphCanvas.Initialize(activityPanel)";
_graphcanvas.Initialize((android.view.View)(_activitypanel.getObject()));
RDebugUtils.currentLine=4718658;
 //BA.debugLineNum = 4718658;BA.debugLine="Dim maxSale As Int = maxSales * 1.2";
_maxsale = (int) (_maxsales*1.2);
RDebugUtils.currentLine=4718659;
 //BA.debugLineNum = 4718659;BA.debugLine="Dim cv As Canvas";
_cv = new anywheresoftware.b4a.objects.drawable.CanvasWrapper();
RDebugUtils.currentLine=4718660;
 //BA.debugLineNum = 4718660;BA.debugLine="cv.Initialize(panel)";
_cv.Initialize((android.view.View)(_panel.getObject()));
RDebugUtils.currentLine=4718662;
 //BA.debugLineNum = 4718662;BA.debugLine="Dim totalProducts As Int = sale1.Length";
_totalproducts = _sale1.length;
RDebugUtils.currentLine=4718663;
 //BA.debugLineNum = 4718663;BA.debugLine="Dim startIndex As Int = (currentPage - 1) * item";
_startindex = (int) ((__ref._currentpage /*int*/ -1)*__ref._itemsperpage /*int*/ );
RDebugUtils.currentLine=4718664;
 //BA.debugLineNum = 4718664;BA.debugLine="Dim endIndex As Int = Min(startIndex + itemsPerP";
_endindex = (int) (__c.Min(_startindex+__ref._itemsperpage /*int*/ -1,_totalproducts-1));
RDebugUtils.currentLine=4718665;
 //BA.debugLineNum = 4718665;BA.debugLine="Dim barsPerProduct As Int = 3";
_barsperproduct = (int) (3);
RDebugUtils.currentLine=4718666;
 //BA.debugLineNum = 4718666;BA.debugLine="Dim totalBars As Int = (endIndex - startIndex +";
_totalbars = (int) ((_endindex-_startindex+1)*_barsperproduct);
RDebugUtils.currentLine=4718667;
 //BA.debugLineNum = 4718667;BA.debugLine="Dim gap As Int = 5dip";
_gap = __c.DipToCurrent((int) (5));
RDebugUtils.currentLine=4718668;
 //BA.debugLineNum = 4718668;BA.debugLine="Dim productGap As Int = 0dip";
_productgap = __c.DipToCurrent((int) (0));
RDebugUtils.currentLine=4718669;
 //BA.debugLineNum = 4718669;BA.debugLine="Dim padding As Int = 10dip";
_padding = __c.DipToCurrent((int) (10));
RDebugUtils.currentLine=4718671;
 //BA.debugLineNum = 4718671;BA.debugLine="Dim availableWidth As Int = activityPanel.Width";
_availablewidth = (int) (_activitypanel.getWidth()-(_padding*2)-(((_endindex-_startindex+1)-1)*_productgap)-((_totalbars-(_endindex-_startindex+1))*_gap));
RDebugUtils.currentLine=4718672;
 //BA.debugLineNum = 4718672;BA.debugLine="Dim barWidth As Int = availableWidth / totalBars";
_barwidth = (int) (_availablewidth/(double)_totalbars);
RDebugUtils.currentLine=4718673;
 //BA.debugLineNum = 4718673;BA.debugLine="Dim xStart As Int = padding";
_xstart = _padding;
RDebugUtils.currentLine=4718675;
 //BA.debugLineNum = 4718675;BA.debugLine="For i = startIndex To endIndex";
{
final int step62 = 1;
final int limit62 = _endindex;
_i = _startindex ;
for (;_i <= limit62 ;_i = _i + step62 ) {
RDebugUtils.currentLine=4718676;
 //BA.debugLineNum = 4718676;BA.debugLine="Dim xPos As Int = xStart + (i - startIndex) * (";
_xpos = (int) (_xstart+(_i-_startindex)*(_barsperproduct*(_barwidth+_gap)+_productgap));
RDebugUtils.currentLine=4718677;
 //BA.debugLineNum = 4718677;BA.debugLine="Dim saleValues() As Int = Array As Int(sale1(i)";
_salevalues = new int[]{_sale1[_i],_sale2[_i],_sale3[_i]};
RDebugUtils.currentLine=4718678;
 //BA.debugLineNum = 4718678;BA.debugLine="Dim indexOffset As Int = 0";
_indexoffset = (int) (0);
RDebugUtils.currentLine=4718680;
 //BA.debugLineNum = 4718680;BA.debugLine="For j = 0 To barsPerProduct - 1";
{
final int step66 = 1;
final int limit66 = (int) (_barsperproduct-1);
_j = (int) (0) ;
for (;_j <= limit66 ;_j = _j + step66 ) {
RDebugUtils.currentLine=4718681;
 //BA.debugLineNum = 4718681;BA.debugLine="If j < checkedSales.Length And checkedSales(j)";
if (_j<__ref._checkedsales /*boolean[]*/ .length && __ref._checkedsales /*boolean[]*/ [_j]) { 
RDebugUtils.currentLine=4718682;
 //BA.debugLineNum = 4718682;BA.debugLine="Dim sale As Int = saleValues(j)";
_sale = _salevalues[_j];
RDebugUtils.currentLine=4718683;
 //BA.debugLineNum = 4718683;BA.debugLine="Dim barHeight As Int = (sale / maxSale) * (ac";
_barheight = (int) ((_sale/(double)_maxsale)*(_activitypanel.getHeight()));
RDebugUtils.currentLine=4718684;
 //BA.debugLineNum = 4718684;BA.debugLine="Dim xBar As Int = xPos + indexOffset * barWid";
_xbar = (int) (_xpos+_indexoffset*_barwidth);
RDebugUtils.currentLine=4718686;
 //BA.debugLineNum = 4718686;BA.debugLine="Dim r As Rect";
_r = new anywheresoftware.b4a.objects.drawable.CanvasWrapper.RectWrapper();
RDebugUtils.currentLine=4718687;
 //BA.debugLineNum = 4718687;BA.debugLine="r.Initialize(xBar, activityPanel.Height - bar";
_r.Initialize(_xbar,(int) (_activitypanel.getHeight()-_barheight),(int) (_xbar+_barwidth),_activitypanel.getHeight());
RDebugUtils.currentLine=4718688;
 //BA.debugLineNum = 4718688;BA.debugLine="graphCanvas.DrawRect(r, color(j), True, 2dip)";
_graphcanvas.DrawRect((android.graphics.Rect)(_r.getObject()),__ref._color /*int[]*/ [_j],__c.True,(float) (__c.DipToCurrent((int) (2))));
RDebugUtils.currentLine=4718690;
 //BA.debugLineNum = 4718690;BA.debugLine="Dim fontSize As Int = 8";
_fontsize = (int) (8);
RDebugUtils.currentLine=4718691;
 //BA.debugLineNum = 4718691;BA.debugLine="If Active.Width > 800 Then";
if (_active.getWidth()>800) { 
RDebugUtils.currentLine=4718692;
 //BA.debugLineNum = 4718692;BA.debugLine="fontSize = 10";
_fontsize = (int) (10);
 };
RDebugUtils.currentLine=4718694;
 //BA.debugLineNum = 4718694;BA.debugLine="graphCanvas.DrawText(FormatNumberWithSuffix(s";
_graphcanvas.DrawText(ba,__ref._formatnumberwithsuffix /*String*/ (null,_sale),(float) (_xbar+(_barwidth/(double)2)),(float) (_activitypanel.getHeight()-_barheight-__c.DipToCurrent((int) (5))),__c.Typeface.MONOSPACE,(float) (_fontsize),__c.Colors.Black,BA.getEnumFromString(android.graphics.Paint.Align.class,"CENTER"));
RDebugUtils.currentLine=4718695;
 //BA.debugLineNum = 4718695;BA.debugLine="indexOffset = indexOffset + 1";
_indexoffset = (int) (_indexoffset+1);
 };
 }
};
RDebugUtils.currentLine=4718699;
 //BA.debugLineNum = 4718699;BA.debugLine="Dim productLabel As Label";
_productlabel = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=4718700;
 //BA.debugLineNum = 4718700;BA.debugLine="productLabel.Initialize(\"productLabel\")";
_productlabel.Initialize(ba,"productLabel");
RDebugUtils.currentLine=4718701;
 //BA.debugLineNum = 4718701;BA.debugLine="productLabel.Text = product(i)";
_productlabel.setText(BA.ObjectToCharSequence(_product[_i]));
RDebugUtils.currentLine=4718702;
 //BA.debugLineNum = 4718702;BA.debugLine="productLabel.Typeface = Typeface.MONOSPACE";
_productlabel.setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=4718703;
 //BA.debugLineNum = 4718703;BA.debugLine="productLabel.TextSize = 12";
_productlabel.setTextSize((float) (12));
RDebugUtils.currentLine=4718704;
 //BA.debugLineNum = 4718704;BA.debugLine="productLabel.Tag = comId1(i)";
_productlabel.setTag((Object)(__ref._comid1 /*int[]*/ [_i]));
RDebugUtils.currentLine=4718705;
 //BA.debugLineNum = 4718705;BA.debugLine="productLabel.TextColor = Colors.Black";
_productlabel.setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=4718706;
 //BA.debugLineNum = 4718706;BA.debugLine="productLabel.Gravity = Gravity.CENTER";
_productlabel.setGravity(__c.Gravity.CENTER);
RDebugUtils.currentLine=4718707;
 //BA.debugLineNum = 4718707;BA.debugLine="Dim productLabelY As Int = activityPanel.Height";
_productlabely = (int) (_activitypanel.getHeight()+_aligntopcenter+__c.DipToCurrent((int) (30)));
RDebugUtils.currentLine=4718708;
 //BA.debugLineNum = 4718708;BA.debugLine="Dim productLabelX As Int = alignLeftCenter";
_productlabelx = _alignleftcenter;
RDebugUtils.currentLine=4718709;
 //BA.debugLineNum = 4718709;BA.debugLine="panel.AddView(productLabel, xPos + productLabel";
_panel.AddView((android.view.View)(_productlabel.getObject()),(int) (_xpos+_productlabelx),(int) (_productlabely+20),__c.DipToCurrent((int) (100)),__c.DipToCurrent((int) (30)));
 }
};
RDebugUtils.currentLine=4718712;
 //BA.debugLineNum = 4718712;BA.debugLine="Dim numLabels As Int = 10";
_numlabels = (int) (10);
RDebugUtils.currentLine=4718713;
 //BA.debugLineNum = 4718713;BA.debugLine="For i = 0 To numLabels";
{
final int step95 = 1;
final int limit95 = _numlabels;
_i = (int) (0) ;
for (;_i <= limit95 ;_i = _i + step95 ) {
RDebugUtils.currentLine=4718714;
 //BA.debugLineNum = 4718714;BA.debugLine="Dim labelValue As Int = Round((maxSale / numLab";
_labelvalue = (int) (__c.Round((_maxsale/(double)_numlabels)*_i));
RDebugUtils.currentLine=4718715;
 //BA.debugLineNum = 4718715;BA.debugLine="Dim labelYPos As Int = activityPanel.Height - (";
_labelypos = (int) (_activitypanel.getHeight()-((_labelvalue/(double)_maxsale)*_activitypanel.getHeight()));
RDebugUtils.currentLine=4718716;
 //BA.debugLineNum = 4718716;BA.debugLine="cv.DrawText(FormatNumberWithLabel(labelValue),";
_cv.DrawText(ba,__ref._formatnumberwithlabel /*String*/ (null,_labelvalue),(float) (_alignleftcenter-__c.DipToCurrent((int) (10))),(float) (_labelypos+_aligntopcenter+__c.DipToCurrent((int) (48))),__c.Typeface.MONOSPACE,(float) (10),__c.Colors.Black,BA.getEnumFromString(android.graphics.Paint.Align.class,"RIGHT"));
 }
};
RDebugUtils.currentLine=4718723;
 //BA.debugLineNum = 4718723;BA.debugLine="Dim buttonWidth As Int = 100dip";
_buttonwidth = __c.DipToCurrent((int) (100));
RDebugUtils.currentLine=4718724;
 //BA.debugLineNum = 4718724;BA.debugLine="Dim buttonHeight As Int = 40dip";
_buttonheight = __c.DipToCurrent((int) (40));
RDebugUtils.currentLine=4718725;
 //BA.debugLineNum = 4718725;BA.debugLine="Dim buttonSpacing As Int = 25dip ' Adjust as nee";
_buttonspacing = __c.DipToCurrent((int) (25));
RDebugUtils.currentLine=4718727;
 //BA.debugLineNum = 4718727;BA.debugLine="Dim graphBottom As Int = activityPanel.Top + act";
_graphbottom = (int) (_activitypanel.getTop()+_activitypanel.getHeight());
RDebugUtils.currentLine=4718728;
 //BA.debugLineNum = 4718728;BA.debugLine="Dim buttonY As Int = graphBottom + buttonSpacing";
_buttony = (int) (_graphbottom+_buttonspacing);
RDebugUtils.currentLine=4718730;
 //BA.debugLineNum = 4718730;BA.debugLine="Dim btnBackX As Int = (panel.Width / 2) - button";
_btnbackx = (int) ((_panel.getWidth()/(double)2)-_buttonwidth-__c.DipToCurrent((int) (100)));
RDebugUtils.currentLine=4718731;
 //BA.debugLineNum = 4718731;BA.debugLine="Dim btnNextX As Int = (panel.Width / 2) + 100dip";
_btnnextx = (int) ((_panel.getWidth()/(double)2)+__c.DipToCurrent((int) (100)));
RDebugUtils.currentLine=4718733;
 //BA.debugLineNum = 4718733;BA.debugLine="panel.AddView(btnBack, btnBackX, buttonY, button";
_panel.AddView((android.view.View)(__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .getObject()),_btnbackx,_buttony,_buttonwidth,_buttonheight);
RDebugUtils.currentLine=4718734;
 //BA.debugLineNum = 4718734;BA.debugLine="panel.AddView(btnNext, btnNextX, buttonY, button";
_panel.AddView((android.view.View)(__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .getObject()),_btnnextx,_buttony,_buttonwidth,_buttonheight);
 } 
       catch (Exception e110) {
			ba.setLastException(e110);RDebugUtils.currentLine=4718739;
 //BA.debugLineNum = 4718739;BA.debugLine="Log(LastException)";
__c.LogImpl("54718739",BA.ObjectToString(__c.LastException(ba)),0);
 };
RDebugUtils.currentLine=4718741;
 //BA.debugLineNum = 4718741;BA.debugLine="End Sub";
return "";
}
public String  _formatnumberwithsuffix(b4a.example.bargraph __ref,int _number) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "formatnumberwithsuffix", false))
	 {return ((String) Debug.delegate(ba, "formatnumberwithsuffix", new Object[] {_number}));}
RDebugUtils.currentLine=5046272;
 //BA.debugLineNum = 5046272;BA.debugLine="Sub FormatNumberWithSuffix(number As Int) As Strin";
RDebugUtils.currentLine=5046273;
 //BA.debugLineNum = 5046273;BA.debugLine="If number >= 1000000 Then";
if (_number>=1000000) { 
RDebugUtils.currentLine=5046274;
 //BA.debugLineNum = 5046274;BA.debugLine="Return NumberFormat(number / 1000000, 1, 1) & \"M";
if (true) return __c.NumberFormat(_number/(double)1000000,(int) (1),(int) (1))+"M";
 }else 
{RDebugUtils.currentLine=5046275;
 //BA.debugLineNum = 5046275;BA.debugLine="Else If number >= 1000 Then";
if (_number>=1000) { 
RDebugUtils.currentLine=5046276;
 //BA.debugLineNum = 5046276;BA.debugLine="Return NumberFormat(number / 1000, 1, 1) & \"k\"";
if (true) return __c.NumberFormat(_number/(double)1000,(int) (1),(int) (1))+"k";
 }else {
RDebugUtils.currentLine=5046278;
 //BA.debugLineNum = 5046278;BA.debugLine="Return NumberFormat(number, 1, 0)";
if (true) return __c.NumberFormat(_number,(int) (1),(int) (0));
 }}
;
RDebugUtils.currentLine=5046280;
 //BA.debugLineNum = 5046280;BA.debugLine="End Sub";
return "";
}
public String  _formatnumberwithlabel(b4a.example.bargraph __ref,int _number) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "formatnumberwithlabel", false))
	 {return ((String) Debug.delegate(ba, "formatnumberwithlabel", new Object[] {_number}));}
RDebugUtils.currentLine=5111808;
 //BA.debugLineNum = 5111808;BA.debugLine="Sub FormatNumberWithLabel(number As Int) As String";
RDebugUtils.currentLine=5111809;
 //BA.debugLineNum = 5111809;BA.debugLine="If number >= 1000000 Then";
if (_number>=1000000) { 
RDebugUtils.currentLine=5111810;
 //BA.debugLineNum = 5111810;BA.debugLine="Return Floor(number / 1000000) & \"M\"";
if (true) return BA.NumberToString(__c.Floor(_number/(double)1000000))+"M";
 }else 
{RDebugUtils.currentLine=5111811;
 //BA.debugLineNum = 5111811;BA.debugLine="Else If number >= 1000 Then";
if (_number>=1000) { 
RDebugUtils.currentLine=5111812;
 //BA.debugLineNum = 5111812;BA.debugLine="Return Floor(number / 1000) & \"k\"";
if (true) return BA.NumberToString(__c.Floor(_number/(double)1000))+"k";
 }else {
RDebugUtils.currentLine=5111814;
 //BA.debugLineNum = 5111814;BA.debugLine="Return number";
if (true) return BA.NumberToString(_number);
 }}
;
RDebugUtils.currentLine=5111816;
 //BA.debugLineNum = 5111816;BA.debugLine="End Sub";
return "";
}
public int  _getcurrentpage(b4a.example.bargraph __ref) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "getcurrentpage", false))
	 {return ((Integer) Debug.delegate(ba, "getcurrentpage", null));}
RDebugUtils.currentLine=4849664;
 //BA.debugLineNum = 4849664;BA.debugLine="Public Sub GetCurrentPage As Int";
RDebugUtils.currentLine=4849665;
 //BA.debugLineNum = 4849665;BA.debugLine="Return currentPage";
if (true) return __ref._currentpage /*int*/ ;
RDebugUtils.currentLine=4849666;
 //BA.debugLineNum = 4849666;BA.debugLine="End Sub";
return 0;
}
public String  _productlabel_click(b4a.example.bargraph __ref) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "productlabel_click", false))
	 {return ((String) Debug.delegate(ba, "productlabel_click", null));}
anywheresoftware.b4a.objects.LabelWrapper _clickedlabel = null;
int _selectedcompany = 0;
RDebugUtils.currentLine=4980736;
 //BA.debugLineNum = 4980736;BA.debugLine="Sub productLabel_Click";
RDebugUtils.currentLine=4980737;
 //BA.debugLineNum = 4980737;BA.debugLine="Dim clickedLabel As Label = Sender";
_clickedlabel = new anywheresoftware.b4a.objects.LabelWrapper();
_clickedlabel = (anywheresoftware.b4a.objects.LabelWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.LabelWrapper(), (android.widget.TextView)(__c.Sender(ba)));
RDebugUtils.currentLine=4980738;
 //BA.debugLineNum = 4980738;BA.debugLine="Dim selectedCompany As Int = clickedLabel.Tag";
_selectedcompany = (int)(BA.ObjectToNumber(_clickedlabel.getTag()));
RDebugUtils.currentLine=4980739;
 //BA.debugLineNum = 4980739;BA.debugLine="Log(\"Selected Company ID: \" & selectedCompany)";
__c.LogImpl("54980739","Selected Company ID: "+BA.NumberToString(_selectedcompany),0);
RDebugUtils.currentLine=4980740;
 //BA.debugLineNum = 4980740;BA.debugLine="Starter.company_selected = selectedCompany";
_starter._company_selected /*String*/  = BA.NumberToString(_selectedcompany);
RDebugUtils.currentLine=4980741;
 //BA.debugLineNum = 4980741;BA.debugLine="StartActivity(layout)";
__c.StartActivity(ba,(Object)(__ref._layout /*String*/ ));
RDebugUtils.currentLine=4980742;
 //BA.debugLineNum = 4980742;BA.debugLine="Active1.Finish";
__ref._active1 /*anywheresoftware.b4a.objects.ActivityWrapper*/ .Finish();
RDebugUtils.currentLine=4980743;
 //BA.debugLineNum = 4980743;BA.debugLine="End Sub";
return "";
}
}