package b4a.example;


import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.B4AClass;
import anywheresoftware.b4a.BALayout;
import anywheresoftware.b4a.debug.*;

public class bargraph extends B4AClass.ImplB4AClass implements BA.SubDelegator{
    private static java.util.HashMap<String, java.lang.reflect.Method> htSubs;
    private void innerInitialize(BA _ba) throws Exception {
        if (ba == null) {
            ba = new anywheresoftware.b4a.ShellBA(_ba, this, htSubs, "b4a.example.bargraph");
            if (htSubs == null) {
                ba.loadHtSubs(this.getClass());
                htSubs = ba.htSubs;
            }
            
        }
        if (BA.isShellModeRuntimeCheck(ba)) 
			   this.getClass().getMethod("_class_globals", b4a.example.bargraph.class).invoke(this, new Object[] {null});
        else
            ba.raiseEvent2(null, true, "class_globals", false);
    }

 
    public void  innerInitializeHelper(anywheresoftware.b4a.BA _ba) throws Exception{
        innerInitialize(_ba);
    }
    public Object callSub(String sub, Object sender, Object[] args) throws Exception {
        return BA.SubDelegator.SubNotFound;
    }
public anywheresoftware.b4a.keywords.Common __c = null;
public anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[] _checkboxes = null;
public boolean[] _checkedsales = null;
public int[] _color = null;
public anywheresoftware.b4a.objects.PanelWrapper _legendpanel = null;
public anywheresoftware.b4a.objects.PanelWrapper _sortpanels = null;
public anywheresoftware.b4a.objects.PanelWrapper _radiopanel = null;
public anywheresoftware.b4a.objects.PanelWrapper _salespanels = null;
public anywheresoftware.b4a.objects.LabelWrapper _radiolabelsalestitles = null;
public anywheresoftware.b4a.objects.LabelWrapper _radiolabelsorttitles = null;
public anywheresoftware.b4a.objects.LabelWrapper _radiolabellegendtitles = null;
public anywheresoftware.b4a.objects.ActivityWrapper _active1 = null;
public anywheresoftware.b4a.objects.PanelWrapper _panel_l = null;
public int[] _sale_1 = null;
public int[] _sale_2 = null;
public int[] _sale_3 = null;
public String[] _product1 = null;
public String[] _legend1 = null;
public int _maxsales1 = 0;
public String _titlestring1 = "";
public int[] _comid1 = null;
public int _currentpage = 0;
public int _itemsperpage = 0;
public anywheresoftware.b4a.objects.ButtonWrapper _btnnext = null;
public anywheresoftware.b4a.objects.ButtonWrapper _btnback = null;
public anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sortbtn1 = null;
public anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sortbtn2 = null;
public anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _defbtn = null;
public anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sales1 = null;
public anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sales2 = null;
public anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sales3 = null;
public String _layout = "";
public boolean _isfirstinit = false;
public anywheresoftware.b4a.objects.PanelWrapper _sortmainpanel = null;
public anywheresoftware.b4a.objects.PanelWrapper _shownmainpanel = null;
public anywheresoftware.b4a.objects.ButtonWrapper _showhidebtn = null;
public b4a.example.main _main = null;
public b4a.example.branch _branch = null;
public b4a.example.device _device = null;
public b4a.example.starter _starter = null;
public b4a.example.httputils2service _httputils2service = null;
public String  _initialize(b4a.example.bargraph __ref,anywheresoftware.b4a.BA _ba,anywheresoftware.b4a.objects.ActivityWrapper _active,anywheresoftware.b4a.objects.PanelWrapper _panel,int[] _sale1,int[] _sale2,int[] _sale3,String[] _product,String[] _legend,int _maxsales,String _titlestring,int[] _comid,String _layout1,anywheresoftware.b4a.objects.ButtonWrapper _nextbtn,anywheresoftware.b4a.objects.ButtonWrapper _backbtn,anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sortbtn,anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _btnsort2,anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _defaultbtn,anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sales1btn,anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sales2btn,anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper _sales3btn) throws Exception{
__ref = this;
innerInitialize(_ba);
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "initialize", false))
	 {return ((String) Debug.delegate(ba, "initialize", new Object[] {_ba,_active,_panel,_sale1,_sale2,_sale3,_product,_legend,_maxsales,_titlestring,_comid,_layout1,_nextbtn,_backbtn,_sortbtn,_btnsort2,_defaultbtn,_sales1btn,_sales2btn,_sales3btn}));}
anywheresoftware.b4a.objects.drawable.ColorDrawable _cd = null;
int _halfwidth = 0;
anywheresoftware.b4a.objects.PanelWrapper _borderpanel = null;
int _legendwidth = 0;
anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[] _tempcheckboxes = null;
boolean[] _tempcheckedsales = null;
int _i = 0;
anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper _chk = null;
anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper[] _radiobuttons = null;
String[] _radiotexts = null;
int _totalbuttons = 0;
int _buttonwidth = 0;
int _spacing = 0;
anywheresoftware.b4a.objects.drawable.ColorDrawable _cdnext = null;
anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper[] _saleslabels = null;
String[] _salestexts = null;
int _totallabels = 0;
int _labelwidth = 0;
anywheresoftware.b4a.objects.drawable.ColorDrawable _cdback = null;
RDebugUtils.currentLine=2949120;
 //BA.debugLineNum = 2949120;BA.debugLine="Public Sub Initialize(Active As Activity, panel As";
RDebugUtils.currentLine=2949121;
 //BA.debugLineNum = 2949121;BA.debugLine="If Active.IsInitialized = False Then";
if (_active.IsInitialized()==__c.False) { 
RDebugUtils.currentLine=2949122;
 //BA.debugLineNum = 2949122;BA.debugLine="Log(\"Error: Activity is not initialized\")";
__c.LogImpl("22949122","Error: Activity is not initialized",0);
RDebugUtils.currentLine=2949123;
 //BA.debugLineNum = 2949123;BA.debugLine="Return";
if (true) return "";
 };
RDebugUtils.currentLine=2949125;
 //BA.debugLineNum = 2949125;BA.debugLine="Active1 = Active";
__ref._active1 /*anywheresoftware.b4a.objects.ActivityWrapper*/  = _active;
RDebugUtils.currentLine=2949126;
 //BA.debugLineNum = 2949126;BA.debugLine="panel_l = panel";
__ref._panel_l /*anywheresoftware.b4a.objects.PanelWrapper*/  = _panel;
RDebugUtils.currentLine=2949127;
 //BA.debugLineNum = 2949127;BA.debugLine="sale_1 = sale1";
__ref._sale_1 /*int[]*/  = _sale1;
RDebugUtils.currentLine=2949128;
 //BA.debugLineNum = 2949128;BA.debugLine="sale_2 = sale2";
__ref._sale_2 /*int[]*/  = _sale2;
RDebugUtils.currentLine=2949129;
 //BA.debugLineNum = 2949129;BA.debugLine="sale_3 = sale3";
__ref._sale_3 /*int[]*/  = _sale3;
RDebugUtils.currentLine=2949130;
 //BA.debugLineNum = 2949130;BA.debugLine="product1 = product";
__ref._product1 /*String[]*/  = _product;
RDebugUtils.currentLine=2949131;
 //BA.debugLineNum = 2949131;BA.debugLine="legend1 = legend";
__ref._legend1 /*String[]*/  = _legend;
RDebugUtils.currentLine=2949132;
 //BA.debugLineNum = 2949132;BA.debugLine="maxSales1 = maxSales";
__ref._maxsales1 /*int*/  = _maxsales;
RDebugUtils.currentLine=2949133;
 //BA.debugLineNum = 2949133;BA.debugLine="titleString1 = TitleString";
__ref._titlestring1 /*String*/  = _titlestring;
RDebugUtils.currentLine=2949134;
 //BA.debugLineNum = 2949134;BA.debugLine="comId1 = comId";
__ref._comid1 /*int[]*/  = _comid;
RDebugUtils.currentLine=2949135;
 //BA.debugLineNum = 2949135;BA.debugLine="layout = layout1";
__ref._layout /*String*/  = _layout1;
RDebugUtils.currentLine=2949136;
 //BA.debugLineNum = 2949136;BA.debugLine="btnNext = NextBtn";
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/  = _nextbtn;
RDebugUtils.currentLine=2949137;
 //BA.debugLineNum = 2949137;BA.debugLine="btnBack = Backbtn";
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/  = _backbtn;
RDebugUtils.currentLine=2949138;
 //BA.debugLineNum = 2949138;BA.debugLine="sortBtn1 = sortBtn";
__ref._sortbtn1 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/  = _sortbtn;
RDebugUtils.currentLine=2949139;
 //BA.debugLineNum = 2949139;BA.debugLine="sortBtn2 = BtnSort2";
__ref._sortbtn2 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/  = _btnsort2;
RDebugUtils.currentLine=2949140;
 //BA.debugLineNum = 2949140;BA.debugLine="defBtn = Defaultbtn";
__ref._defbtn /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/  = _defaultbtn;
RDebugUtils.currentLine=2949141;
 //BA.debugLineNum = 2949141;BA.debugLine="sales1 = Sales1btn";
__ref._sales1 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/  = _sales1btn;
RDebugUtils.currentLine=2949142;
 //BA.debugLineNum = 2949142;BA.debugLine="sales2 = Sales2btn";
__ref._sales2 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/  = _sales2btn;
RDebugUtils.currentLine=2949143;
 //BA.debugLineNum = 2949143;BA.debugLine="sales3 = Sales3btn";
__ref._sales3 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/  = _sales3btn;
RDebugUtils.currentLine=2949145;
 //BA.debugLineNum = 2949145;BA.debugLine="Dim cd As ColorDrawable";
_cd = new anywheresoftware.b4a.objects.drawable.ColorDrawable();
RDebugUtils.currentLine=2949146;
 //BA.debugLineNum = 2949146;BA.debugLine="cd.Initialize2(Colors.White, 5dip, 1dip, Colors.B";
_cd.Initialize2(__c.Colors.White,__c.DipToCurrent((int) (5)),__c.DipToCurrent((int) (1)),__c.Colors.Black);
RDebugUtils.currentLine=2949149;
 //BA.debugLineNum = 2949149;BA.debugLine="If sale1.Length <> product.Length Or sale2.Length";
if (_sale1.length!=_product.length || _sale2.length!=_product.length || _sale3.length!=_product.length) { 
RDebugUtils.currentLine=2949150;
 //BA.debugLineNum = 2949150;BA.debugLine="Return";
if (true) return "";
 };
RDebugUtils.currentLine=2949152;
 //BA.debugLineNum = 2949152;BA.debugLine="Dim halfWidth As Int = panel.Width / 2";
_halfwidth = (int) (_panel.getWidth()/(double)2);
RDebugUtils.currentLine=2949154;
 //BA.debugLineNum = 2949154;BA.debugLine="legendPanel.Initialize(\"\")";
__ref._legendpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .Initialize(ba,"");
RDebugUtils.currentLine=2949155;
 //BA.debugLineNum = 2949155;BA.debugLine="legendPanel.Width = halfWidth";
__ref._legendpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .setWidth(_halfwidth);
RDebugUtils.currentLine=2949156;
 //BA.debugLineNum = 2949156;BA.debugLine="legendPanel.Height = 60dip";
__ref._legendpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .setHeight(__c.DipToCurrent((int) (60)));
RDebugUtils.currentLine=2949158;
 //BA.debugLineNum = 2949158;BA.debugLine="radioPanel.Initialize(\"\")";
__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .Initialize(ba,"");
RDebugUtils.currentLine=2949159;
 //BA.debugLineNum = 2949159;BA.debugLine="radioPanel.Width = halfWidth";
__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .setWidth(_halfwidth);
RDebugUtils.currentLine=2949160;
 //BA.debugLineNum = 2949160;BA.debugLine="radioPanel.Height = 30dip";
__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .setHeight(__c.DipToCurrent((int) (30)));
RDebugUtils.currentLine=2949162;
 //BA.debugLineNum = 2949162;BA.debugLine="radioPanel.Color = Colors.Transparent ' Keep it t";
__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .setColor(__c.Colors.Transparent);
RDebugUtils.currentLine=2949163;
 //BA.debugLineNum = 2949163;BA.debugLine="Dim borderPanel As Panel";
_borderpanel = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=2949164;
 //BA.debugLineNum = 2949164;BA.debugLine="borderPanel.Initialize(\"\")";
_borderpanel.Initialize(ba,"");
RDebugUtils.currentLine=2949165;
 //BA.debugLineNum = 2949165;BA.debugLine="borderPanel.Color = Colors.Black ' Border color";
_borderpanel.setColor(__c.Colors.Black);
RDebugUtils.currentLine=2949166;
 //BA.debugLineNum = 2949166;BA.debugLine="panel.AddView(borderPanel, radioPanel.Left, radio";
_panel.AddView((android.view.View)(_borderpanel.getObject()),__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getLeft(),__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getTop(),__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getWidth(),__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getHeight());
RDebugUtils.currentLine=2949167;
 //BA.debugLineNum = 2949167;BA.debugLine="panel.AddView(radioPanel, radioPanel.Left + 1dip,";
_panel.AddView((android.view.View)(__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getObject()),(int) (__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getLeft()+__c.DipToCurrent((int) (1))),(int) (__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getTop()+__c.DipToCurrent((int) (1))),(int) (__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getWidth()-__c.DipToCurrent((int) (2))),(int) (__ref._radiopanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getHeight()-__c.DipToCurrent((int) (2))));
RDebugUtils.currentLine=2949169;
 //BA.debugLineNum = 2949169;BA.debugLine="Dim legendWidth As Int = (legendPanel.Width-20dip";
_legendwidth = (int) ((__ref._legendpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getWidth()-__c.DipToCurrent((int) (20)))/(double)_legend.length);
RDebugUtils.currentLine=2949170;
 //BA.debugLineNum = 2949170;BA.debugLine="checkBoxes = Array As CheckBox()";
__ref._checkboxes /*anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[]*/  = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[]{};
RDebugUtils.currentLine=2949171;
 //BA.debugLineNum = 2949171;BA.debugLine="checkedSales = Array As Boolean()";
__ref._checkedsales /*boolean[]*/  = new boolean[]{};
RDebugUtils.currentLine=2949173;
 //BA.debugLineNum = 2949173;BA.debugLine="Dim checkBoxes(legend.Length) As CheckBox";
_checkboxes = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[_legend.length];
{
int d0 = _checkboxes.length;
for (int i0 = 0;i0 < d0;i0++) {
_checkboxes[i0] = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper();
}
}
;
RDebugUtils.currentLine=2949174;
 //BA.debugLineNum = 2949174;BA.debugLine="Dim checkedSales(legend.Length) As Boolean";
_checkedsales = new boolean[_legend.length];
;
RDebugUtils.currentLine=2949175;
 //BA.debugLineNum = 2949175;BA.debugLine="If isFirstInit Then";
if (__ref._isfirstinit /*boolean*/ ) { 
RDebugUtils.currentLine=2949177;
 //BA.debugLineNum = 2949177;BA.debugLine="Dim tempCheckBoxes(legend.Length) As CheckBox";
_tempcheckboxes = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[_legend.length];
{
int d0 = _tempcheckboxes.length;
for (int i0 = 0;i0 < d0;i0++) {
_tempcheckboxes[i0] = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper();
}
}
;
RDebugUtils.currentLine=2949178;
 //BA.debugLineNum = 2949178;BA.debugLine="checkBoxes = tempCheckBoxes";
__ref._checkboxes /*anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[]*/  = _tempcheckboxes;
RDebugUtils.currentLine=2949179;
 //BA.debugLineNum = 2949179;BA.debugLine="Dim tempCheckedSales(legend.Length) As Boolean";
_tempcheckedsales = new boolean[_legend.length];
;
RDebugUtils.currentLine=2949180;
 //BA.debugLineNum = 2949180;BA.debugLine="checkedSales = tempCheckedSales";
__ref._checkedsales /*boolean[]*/  = _tempcheckedsales;
RDebugUtils.currentLine=2949183;
 //BA.debugLineNum = 2949183;BA.debugLine="For i = 0 To legend.Length - 1";
{
final int step52 = 1;
final int limit52 = (int) (_legend.length-1);
_i = (int) (0) ;
for (;_i <= limit52 ;_i = _i + step52 ) {
RDebugUtils.currentLine=2949184;
 //BA.debugLineNum = 2949184;BA.debugLine="Dim chk As CheckBox";
_chk = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper();
RDebugUtils.currentLine=2949185;
 //BA.debugLineNum = 2949185;BA.debugLine="chk.Initialize(\"chkChange\")";
_chk.Initialize(ba,"chkChange");
RDebugUtils.currentLine=2949186;
 //BA.debugLineNum = 2949186;BA.debugLine="chk.Text = legend(i)";
_chk.setText(BA.ObjectToCharSequence(_legend[_i]));
RDebugUtils.currentLine=2949187;
 //BA.debugLineNum = 2949187;BA.debugLine="chk.TextSize = 10";
_chk.setTextSize((float) (10));
RDebugUtils.currentLine=2949188;
 //BA.debugLineNum = 2949188;BA.debugLine="chk.Typeface = Typeface.MONOSPACE";
_chk.setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=2949189;
 //BA.debugLineNum = 2949189;BA.debugLine="chk.TextColor = color(i)";
_chk.setTextColor(__ref._color /*int[]*/ [_i]);
RDebugUtils.currentLine=2949190;
 //BA.debugLineNum = 2949190;BA.debugLine="chk.Gravity = Gravity.CENTER";
_chk.setGravity(__c.Gravity.CENTER);
RDebugUtils.currentLine=2949191;
 //BA.debugLineNum = 2949191;BA.debugLine="chk.Tag = i";
_chk.setTag((Object)(_i));
RDebugUtils.currentLine=2949192;
 //BA.debugLineNum = 2949192;BA.debugLine="chk.Checked = True  ' Default state";
_chk.setChecked(__c.True);
RDebugUtils.currentLine=2949193;
 //BA.debugLineNum = 2949193;BA.debugLine="checkedSales(i) = True";
__ref._checkedsales /*boolean[]*/ [_i] = __c.True;
RDebugUtils.currentLine=2949194;
 //BA.debugLineNum = 2949194;BA.debugLine="legendPanel.AddView(chk, (legendWidth * i), 10d";
__ref._legendpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(_chk.getObject()),(int) ((_legendwidth*_i)),__c.DipToCurrent((int) (10)),_legendwidth,(int) (__ref._legendpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getHeight()-__c.DipToCurrent((int) (20))));
RDebugUtils.currentLine=2949195;
 //BA.debugLineNum = 2949195;BA.debugLine="checkBoxes(i) = chk";
__ref._checkboxes /*anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[]*/ [_i] = _chk;
 }
};
RDebugUtils.currentLine=2949197;
 //BA.debugLineNum = 2949197;BA.debugLine="isFirstInit = False";
__ref._isfirstinit /*boolean*/  = __c.False;
 }else {
RDebugUtils.currentLine=2949200;
 //BA.debugLineNum = 2949200;BA.debugLine="For i = 0 To checkBoxes.Length - 1";
{
final int step68 = 1;
final int limit68 = (int) (__ref._checkboxes /*anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[]*/ .length-1);
_i = (int) (0) ;
for (;_i <= limit68 ;_i = _i + step68 ) {
RDebugUtils.currentLine=2949201;
 //BA.debugLineNum = 2949201;BA.debugLine="checkBoxes(i).Checked = checkedSales(i)";
__ref._checkboxes /*anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[]*/ [_i].setChecked(__ref._checkedsales /*boolean[]*/ [_i]);
 }
};
 };
RDebugUtils.currentLine=2949207;
 //BA.debugLineNum = 2949207;BA.debugLine="sortMainpanel.Initialize(\"\")";
__ref._sortmainpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .Initialize(ba,"");
RDebugUtils.currentLine=2949208;
 //BA.debugLineNum = 2949208;BA.debugLine="panel.AddView(sortMainpanel, 0dip, 5dip, halfWidt";
_panel.AddView((android.view.View)(__ref._sortmainpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getObject()),__c.DipToCurrent((int) (0)),__c.DipToCurrent((int) (5)),_halfwidth,__c.DipToCurrent((int) (120)));
RDebugUtils.currentLine=2949211;
 //BA.debugLineNum = 2949211;BA.debugLine="Dim radioButtons() As RadioButton = Array As Radi";
_radiobuttons = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper[]{__ref._sortbtn1 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/ ,__ref._sortbtn2 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/ ,__ref._defbtn /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/ };
RDebugUtils.currentLine=2949212;
 //BA.debugLineNum = 2949212;BA.debugLine="Dim radioTexts() As String = Array As String(\"ASC";
_radiotexts = new String[]{"ASC","DESC","DEFAULT"};
RDebugUtils.currentLine=2949214;
 //BA.debugLineNum = 2949214;BA.debugLine="sortPanels.Initialize(\"\")";
__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .Initialize(ba,"");
RDebugUtils.currentLine=2949215;
 //BA.debugLineNum = 2949215;BA.debugLine="sortPanels.Width = halfWidth";
__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .setWidth(_halfwidth);
RDebugUtils.currentLine=2949216;
 //BA.debugLineNum = 2949216;BA.debugLine="sortPanels.Height = 30dip";
__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .setHeight(__c.DipToCurrent((int) (30)));
RDebugUtils.currentLine=2949217;
 //BA.debugLineNum = 2949217;BA.debugLine="sortPanels.SendToBack";
__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .SendToBack();
RDebugUtils.currentLine=2949218;
 //BA.debugLineNum = 2949218;BA.debugLine="sortMainpanel.AddView(sortPanels, 10dip, 5dip, so";
__ref._sortmainpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .getObject()),__c.DipToCurrent((int) (10)),__c.DipToCurrent((int) (5)),(int) (__ref._sortmainpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getWidth()-__c.DipToCurrent((int) (20))),__c.DipToCurrent((int) (45)));
RDebugUtils.currentLine=2949219;
 //BA.debugLineNum = 2949219;BA.debugLine="sortPanels.Background = cd";
__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .setBackground((android.graphics.drawable.Drawable)(_cd.getObject()));
RDebugUtils.currentLine=2949221;
 //BA.debugLineNum = 2949221;BA.debugLine="radioLabelSalesTitles.Initialize(\"radioLabelSales";
__ref._radiolabelsalestitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .Initialize(ba,"radioLabelSalesTitles");
RDebugUtils.currentLine=2949222;
 //BA.debugLineNum = 2949222;BA.debugLine="radioLabelSalesTitles.Text = \"Base on\"";
__ref._radiolabelsalestitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setText(BA.ObjectToCharSequence("Base on"));
RDebugUtils.currentLine=2949223;
 //BA.debugLineNum = 2949223;BA.debugLine="radioLabelSalesTitles.TextSize = 12";
__ref._radiolabelsalestitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTextSize((float) (12));
RDebugUtils.currentLine=2949224;
 //BA.debugLineNum = 2949224;BA.debugLine="radioLabelSalesTitles.Gravity = Gravity.CENTER";
__ref._radiolabelsalestitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setGravity(__c.Gravity.CENTER);
RDebugUtils.currentLine=2949225;
 //BA.debugLineNum = 2949225;BA.debugLine="radioLabelSalesTitles.Typeface = Typeface.MONOSPA";
__ref._radiolabelsalestitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=2949226;
 //BA.debugLineNum = 2949226;BA.debugLine="radioLabelSalesTitles.TextColor = Colors.Black";
__ref._radiolabelsalestitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=2949227;
 //BA.debugLineNum = 2949227;BA.debugLine="radioLabelSalesTitles.Color = Colors.White";
__ref._radiolabelsalestitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setColor(__c.Colors.White);
RDebugUtils.currentLine=2949228;
 //BA.debugLineNum = 2949228;BA.debugLine="sortMainpanel.AddView(radioLabelSalesTitles, 15di";
__ref._sortmainpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(__ref._radiolabelsalestitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .getObject()),__c.DipToCurrent((int) (15)),(int) (-__c.DipToCurrent((int) (2))),__c.DipToCurrent((int) (60)),__c.DipToCurrent((int) (15)));
RDebugUtils.currentLine=2949230;
 //BA.debugLineNum = 2949230;BA.debugLine="If sortPanels.Width = 0 Then";
if (__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .getWidth()==0) { 
RDebugUtils.currentLine=2949231;
 //BA.debugLineNum = 2949231;BA.debugLine="sortPanels.Width = halfWidth ' Default width to";
__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .setWidth(_halfwidth);
 };
RDebugUtils.currentLine=2949234;
 //BA.debugLineNum = 2949234;BA.debugLine="Dim totalButtons As Int = radioButtons.Length";
_totalbuttons = _radiobuttons.length;
RDebugUtils.currentLine=2949235;
 //BA.debugLineNum = 2949235;BA.debugLine="Dim buttonWidth As Int = (sortPanels.Width - (tot";
_buttonwidth = (int) ((__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .getWidth()-(_totalbuttons*__c.DipToCurrent((int) (5))))/(double)_totalbuttons);
RDebugUtils.currentLine=2949236;
 //BA.debugLineNum = 2949236;BA.debugLine="Dim spacing As Int = 5dip ' Small gap between but";
_spacing = __c.DipToCurrent((int) (5));
RDebugUtils.currentLine=2949238;
 //BA.debugLineNum = 2949238;BA.debugLine="For i = 0 To totalButtons - 1";
{
final int step96 = 1;
final int limit96 = (int) (_totalbuttons-1);
_i = (int) (0) ;
for (;_i <= limit96 ;_i = _i + step96 ) {
RDebugUtils.currentLine=2949239;
 //BA.debugLineNum = 2949239;BA.debugLine="radioButtons(i).Text = radioTexts(i)";
_radiobuttons[_i].setText(BA.ObjectToCharSequence(_radiotexts[_i]));
RDebugUtils.currentLine=2949240;
 //BA.debugLineNum = 2949240;BA.debugLine="radioButtons(i).TextSize = 10";
_radiobuttons[_i].setTextSize((float) (10));
RDebugUtils.currentLine=2949241;
 //BA.debugLineNum = 2949241;BA.debugLine="radioButtons(i).Tag = radioTexts(i)";
_radiobuttons[_i].setTag((Object)(_radiotexts[_i]));
RDebugUtils.currentLine=2949242;
 //BA.debugLineNum = 2949242;BA.debugLine="radioButtons(i).Gravity = Gravity.CENTER_VERTICA";
_radiobuttons[_i].setGravity(__c.Gravity.CENTER_VERTICAL);
RDebugUtils.currentLine=2949243;
 //BA.debugLineNum = 2949243;BA.debugLine="radioButtons(i).Typeface = Typeface.MONOSPACE";
_radiobuttons[_i].setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=2949244;
 //BA.debugLineNum = 2949244;BA.debugLine="radioButtons(i).TextColor = Colors.Black";
_radiobuttons[_i].setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=2949247;
 //BA.debugLineNum = 2949247;BA.debugLine="Dim cdNext As ColorDrawable";
_cdnext = new anywheresoftware.b4a.objects.drawable.ColorDrawable();
RDebugUtils.currentLine=2949248;
 //BA.debugLineNum = 2949248;BA.debugLine="cdNext.Initialize2(Colors.RGB(128, 128, 128), 10";
_cdnext.Initialize2(__c.Colors.RGB((int) (128),(int) (128),(int) (128)),__c.DipToCurrent((int) (10)),__c.DipToCurrent((int) (2)),__c.Colors.Black);
RDebugUtils.currentLine=2949251;
 //BA.debugLineNum = 2949251;BA.debugLine="sortPanels.AddView(radioButtons(i), (i * (button";
__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(_radiobuttons[_i].getObject()),(int) ((_i*(_buttonwidth+_spacing))),__c.DipToCurrent((int) (10)),_buttonwidth,__c.DipToCurrent((int) (25)));
 }
};
RDebugUtils.currentLine=2949254;
 //BA.debugLineNum = 2949254;BA.debugLine="Dim salesLabels() As RadioButton = Array As Radio";
_saleslabels = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper[]{__ref._sales1 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/ ,__ref._sales2 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/ ,__ref._sales3 /*anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper*/ };
RDebugUtils.currentLine=2949255;
 //BA.debugLineNum = 2949255;BA.debugLine="Dim salesTexts() As String = Array As String(\"1\",";
_salestexts = new String[]{"1","2","3"};
RDebugUtils.currentLine=2949257;
 //BA.debugLineNum = 2949257;BA.debugLine="salesPanels.Initialize(\"\")";
__ref._salespanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .Initialize(ba,"");
RDebugUtils.currentLine=2949258;
 //BA.debugLineNum = 2949258;BA.debugLine="salesPanels.Width = halfWidth ' Half of the main";
__ref._salespanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .setWidth(_halfwidth);
RDebugUtils.currentLine=2949259;
 //BA.debugLineNum = 2949259;BA.debugLine="salesPanels.Height = 30dip ' Height remains the s";
__ref._salespanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .setHeight(__c.DipToCurrent((int) (30)));
RDebugUtils.currentLine=2949260;
 //BA.debugLineNum = 2949260;BA.debugLine="sortMainpanel.AddView(salesPanels, 10dip, sortPan";
__ref._sortmainpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(__ref._salespanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .getObject()),__c.DipToCurrent((int) (10)),(int) (__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .getHeight()+__c.DipToCurrent((int) (20))),(int) (__ref._sortmainpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getWidth()-__c.DipToCurrent((int) (20))),__c.DipToCurrent((int) (45)));
RDebugUtils.currentLine=2949261;
 //BA.debugLineNum = 2949261;BA.debugLine="salesPanels.Background = cd";
__ref._salespanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .setBackground((android.graphics.drawable.Drawable)(_cd.getObject()));
RDebugUtils.currentLine=2949263;
 //BA.debugLineNum = 2949263;BA.debugLine="radioLabelSortTitles.Initialize(\"radioLabelSortTi";
__ref._radiolabelsorttitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .Initialize(ba,"radioLabelSortTitles");
RDebugUtils.currentLine=2949264;
 //BA.debugLineNum = 2949264;BA.debugLine="radioLabelSortTitles.Text = \"Sort By\"";
__ref._radiolabelsorttitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setText(BA.ObjectToCharSequence("Sort By"));
RDebugUtils.currentLine=2949265;
 //BA.debugLineNum = 2949265;BA.debugLine="radioLabelSortTitles.TextSize = 12";
__ref._radiolabelsorttitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTextSize((float) (12));
RDebugUtils.currentLine=2949266;
 //BA.debugLineNum = 2949266;BA.debugLine="radioLabelSortTitles.Typeface = Typeface.MONOSPAC";
__ref._radiolabelsorttitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=2949267;
 //BA.debugLineNum = 2949267;BA.debugLine="radioLabelSortTitles.Gravity = Gravity.CENTER";
__ref._radiolabelsorttitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setGravity(__c.Gravity.CENTER);
RDebugUtils.currentLine=2949268;
 //BA.debugLineNum = 2949268;BA.debugLine="radioLabelSortTitles.TextColor = Colors.Black";
__ref._radiolabelsorttitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=2949269;
 //BA.debugLineNum = 2949269;BA.debugLine="radioLabelSortTitles.Color = Colors.White";
__ref._radiolabelsorttitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setColor(__c.Colors.White);
RDebugUtils.currentLine=2949270;
 //BA.debugLineNum = 2949270;BA.debugLine="sortMainpanel.AddView(radioLabelSortTitles,15dip,";
__ref._sortmainpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(__ref._radiolabelsorttitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .getObject()),__c.DipToCurrent((int) (15)),(int) (__ref._sortpanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .getHeight()+__c.DipToCurrent((int) (12))),__c.DipToCurrent((int) (60)),__c.DipToCurrent((int) (15)));
RDebugUtils.currentLine=2949272;
 //BA.debugLineNum = 2949272;BA.debugLine="Dim totalLabels As Int = salesLabels.Length";
_totallabels = _saleslabels.length;
RDebugUtils.currentLine=2949273;
 //BA.debugLineNum = 2949273;BA.debugLine="Dim labelWidth As Int = (salesPanels.Width - (tot";
_labelwidth = (int) ((__ref._salespanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .getWidth()-(_totallabels*__c.DipToCurrent((int) (5))))/(double)_totallabels);
RDebugUtils.currentLine=2949274;
 //BA.debugLineNum = 2949274;BA.debugLine="Dim spacing As Int = 5dip ' Small spacing between";
_spacing = __c.DipToCurrent((int) (5));
RDebugUtils.currentLine=2949276;
 //BA.debugLineNum = 2949276;BA.debugLine="For i = 0 To totalLabels - 1";
{
final int step125 = 1;
final int limit125 = (int) (_totallabels-1);
_i = (int) (0) ;
for (;_i <= limit125 ;_i = _i + step125 ) {
RDebugUtils.currentLine=2949277;
 //BA.debugLineNum = 2949277;BA.debugLine="salesLabels(i).Text = \"Sales\" & (i + 1)";
_saleslabels[_i].setText(BA.ObjectToCharSequence("Sales"+BA.NumberToString((_i+1))));
RDebugUtils.currentLine=2949278;
 //BA.debugLineNum = 2949278;BA.debugLine="salesLabels(i).TextSize = 10";
_saleslabels[_i].setTextSize((float) (10));
RDebugUtils.currentLine=2949279;
 //BA.debugLineNum = 2949279;BA.debugLine="salesLabels(i).Tag = salesTexts(i)";
_saleslabels[_i].setTag((Object)(_salestexts[_i]));
RDebugUtils.currentLine=2949280;
 //BA.debugLineNum = 2949280;BA.debugLine="salesLabels(i).Typeface = Typeface.MONOSPACE";
_saleslabels[_i].setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=2949281;
 //BA.debugLineNum = 2949281;BA.debugLine="salesLabels(i).TextColor = Colors.Black";
_saleslabels[_i].setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=2949283;
 //BA.debugLineNum = 2949283;BA.debugLine="Dim cdBack As ColorDrawable";
_cdback = new anywheresoftware.b4a.objects.drawable.ColorDrawable();
RDebugUtils.currentLine=2949284;
 //BA.debugLineNum = 2949284;BA.debugLine="cdBack.Initialize2(Colors.RGB(128, 128, 128), 10";
_cdback.Initialize2(__c.Colors.RGB((int) (128),(int) (128),(int) (128)),__c.DipToCurrent((int) (10)),__c.DipToCurrent((int) (2)),__c.Colors.Black);
RDebugUtils.currentLine=2949288;
 //BA.debugLineNum = 2949288;BA.debugLine="salesPanels.AddView(salesLabels(i), (i * (labelW";
__ref._salespanels /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(_saleslabels[_i].getObject()),(int) ((_i*(_labelwidth+_spacing))),__c.DipToCurrent((int) (10)),_labelwidth,__c.DipToCurrent((int) (20)));
 }
};
RDebugUtils.currentLine=2949293;
 //BA.debugLineNum = 2949293;BA.debugLine="DrawGraph(Active, panel, sale1, sale2, sale3, pro";
__ref._drawgraph /*String*/ (null,_active,_panel,_sale1,_sale2,_sale3,_product,_maxsales,_titlestring);
RDebugUtils.currentLine=2949294;
 //BA.debugLineNum = 2949294;BA.debugLine="End Sub";
return "";
}
public String  _updategraph(b4a.example.bargraph __ref) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "updategraph", false))
	 {return ((String) Debug.delegate(ba, "updategraph", null));}
RDebugUtils.currentLine=3080192;
 //BA.debugLineNum = 3080192;BA.debugLine="Public Sub UpdateGraph";
RDebugUtils.currentLine=3080193;
 //BA.debugLineNum = 3080193;BA.debugLine="DrawGraph(Active1, panel_l, sale_1, sale_2, sale_";
__ref._drawgraph /*String*/ (null,__ref._active1 /*anywheresoftware.b4a.objects.ActivityWrapper*/ ,__ref._panel_l /*anywheresoftware.b4a.objects.PanelWrapper*/ ,__ref._sale_1 /*int[]*/ ,__ref._sale_2 /*int[]*/ ,__ref._sale_3 /*int[]*/ ,__ref._product1 /*String[]*/ ,__ref._maxsales1 /*int*/ ,__ref._titlestring1 /*String*/ );
RDebugUtils.currentLine=3080194;
 //BA.debugLineNum = 3080194;BA.debugLine="End Sub";
return "";
}
public boolean[]  _getcheckedsales(b4a.example.bargraph __ref) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "getcheckedsales", false))
	 {return ((boolean[]) Debug.delegate(ba, "getcheckedsales", null));}
RDebugUtils.currentLine=3538944;
 //BA.debugLineNum = 3538944;BA.debugLine="Public Sub GetCheckedSales As Boolean()";
RDebugUtils.currentLine=3538945;
 //BA.debugLineNum = 3538945;BA.debugLine="Return checkedSales";
if (true) return __ref._checkedsales /*boolean[]*/ ;
RDebugUtils.currentLine=3538946;
 //BA.debugLineNum = 3538946;BA.debugLine="End Sub";
return null;
}
public String  _chkchange_checkedchange(b4a.example.bargraph __ref,boolean _checked) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "chkchange_checkedchange", false))
	 {return ((String) Debug.delegate(ba, "chkchange_checkedchange", new Object[] {_checked}));}
anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper _chk = null;
int _index = 0;
int _checkedcount = 0;
int _i = 0;
RDebugUtils.currentLine=3473408;
 //BA.debugLineNum = 3473408;BA.debugLine="Sub chkChange_CheckedChange(Checked As Boolean)";
RDebugUtils.currentLine=3473409;
 //BA.debugLineNum = 3473409;BA.debugLine="If Sender Is CheckBox Then";
if (__c.Sender(ba) instanceof android.widget.CheckBox) { 
RDebugUtils.currentLine=3473410;
 //BA.debugLineNum = 3473410;BA.debugLine="Dim chk As CheckBox = Sender";
_chk = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper();
_chk = (anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper(), (android.widget.CheckBox)(__c.Sender(ba)));
RDebugUtils.currentLine=3473411;
 //BA.debugLineNum = 3473411;BA.debugLine="Dim index As Int = chk.Tag";
_index = (int)(BA.ObjectToNumber(_chk.getTag()));
RDebugUtils.currentLine=3473413;
 //BA.debugLineNum = 3473413;BA.debugLine="Dim checkedCount As Int = 0";
_checkedcount = (int) (0);
RDebugUtils.currentLine=3473414;
 //BA.debugLineNum = 3473414;BA.debugLine="For i = 0 To checkedSales.Length - 1";
{
final int step5 = 1;
final int limit5 = (int) (__ref._checkedsales /*boolean[]*/ .length-1);
_i = (int) (0) ;
for (;_i <= limit5 ;_i = _i + step5 ) {
RDebugUtils.currentLine=3473415;
 //BA.debugLineNum = 3473415;BA.debugLine="If checkedSales(i) = True Then checkedCount = c";
if (__ref._checkedsales /*boolean[]*/ [_i]==__c.True) { 
_checkedcount = (int) (_checkedcount+1);};
 }
};
RDebugUtils.currentLine=3473418;
 //BA.debugLineNum = 3473418;BA.debugLine="If Checked = False And checkedCount = 1 Then";
if (_checked==__c.False && _checkedcount==1) { 
RDebugUtils.currentLine=3473419;
 //BA.debugLineNum = 3473419;BA.debugLine="chk.Checked = True";
_chk.setChecked(__c.True);
RDebugUtils.currentLine=3473420;
 //BA.debugLineNum = 3473420;BA.debugLine="Return";
if (true) return "";
 };
RDebugUtils.currentLine=3473423;
 //BA.debugLineNum = 3473423;BA.debugLine="checkedSales(index) = Checked";
__ref._checkedsales /*boolean[]*/ [_index] = _checked;
RDebugUtils.currentLine=3473424;
 //BA.debugLineNum = 3473424;BA.debugLine="UpdateGraph ' Call DrawGraph without parameters";
__ref._updategraph /*String*/ (null);
 }else {
RDebugUtils.currentLine=3473426;
 //BA.debugLineNum = 3473426;BA.debugLine="Log(\"Error: Sender is not a CheckBox\")";
__c.LogImpl("23473426","Error: Sender is not a CheckBox",0);
 };
RDebugUtils.currentLine=3473428;
 //BA.debugLineNum = 3473428;BA.debugLine="End Sub";
return "";
}
public String  _class_globals(b4a.example.bargraph __ref) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
RDebugUtils.currentLine=2883584;
 //BA.debugLineNum = 2883584;BA.debugLine="Sub Class_Globals";
RDebugUtils.currentLine=2883585;
 //BA.debugLineNum = 2883585;BA.debugLine="Private checkBoxes() As CheckBox";
_checkboxes = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper[(int) (0)];
{
int d0 = _checkboxes.length;
for (int i0 = 0;i0 < d0;i0++) {
_checkboxes[i0] = new anywheresoftware.b4a.objects.CompoundButtonWrapper.CheckBoxWrapper();
}
}
;
RDebugUtils.currentLine=2883586;
 //BA.debugLineNum = 2883586;BA.debugLine="Public checkedSales() As Boolean";
_checkedsales = new boolean[(int) (0)];
;
RDebugUtils.currentLine=2883587;
 //BA.debugLineNum = 2883587;BA.debugLine="Dim color() As Int = Array As Int(Colors.RGB(255,";
_color = new int[]{__c.Colors.RGB((int) (255),(int) (0),(int) (0)),__c.Colors.RGB((int) (200),(int) (20),(int) (20)),__c.Colors.RGB((int) (100),(int) (10),(int) (10))};
RDebugUtils.currentLine=2883588;
 //BA.debugLineNum = 2883588;BA.debugLine="Dim legendPanel As Panel";
_legendpanel = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=2883589;
 //BA.debugLineNum = 2883589;BA.debugLine="Dim sortPanels As Panel";
_sortpanels = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=2883590;
 //BA.debugLineNum = 2883590;BA.debugLine="Dim radioPanel As Panel";
_radiopanel = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=2883591;
 //BA.debugLineNum = 2883591;BA.debugLine="Dim salesPanels As Panel";
_salespanels = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=2883592;
 //BA.debugLineNum = 2883592;BA.debugLine="Dim radioLabelSalesTitles As Label";
_radiolabelsalestitles = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=2883593;
 //BA.debugLineNum = 2883593;BA.debugLine="Dim radioLabelSortTitles As Label";
_radiolabelsorttitles = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=2883594;
 //BA.debugLineNum = 2883594;BA.debugLine="Dim radioLabelLegendTitles As Label";
_radiolabellegendtitles = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=2883595;
 //BA.debugLineNum = 2883595;BA.debugLine="Dim Active1 As Activity";
_active1 = new anywheresoftware.b4a.objects.ActivityWrapper();
RDebugUtils.currentLine=2883596;
 //BA.debugLineNum = 2883596;BA.debugLine="Dim panel_l As Panel";
_panel_l = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=2883597;
 //BA.debugLineNum = 2883597;BA.debugLine="Dim sale_1() As Int";
_sale_1 = new int[(int) (0)];
;
RDebugUtils.currentLine=2883598;
 //BA.debugLineNum = 2883598;BA.debugLine="Dim sale_2() As Int";
_sale_2 = new int[(int) (0)];
;
RDebugUtils.currentLine=2883599;
 //BA.debugLineNum = 2883599;BA.debugLine="Dim sale_3() As Int";
_sale_3 = new int[(int) (0)];
;
RDebugUtils.currentLine=2883600;
 //BA.debugLineNum = 2883600;BA.debugLine="Dim product1() As String";
_product1 = new String[(int) (0)];
java.util.Arrays.fill(_product1,"");
RDebugUtils.currentLine=2883601;
 //BA.debugLineNum = 2883601;BA.debugLine="Dim legend1() As String";
_legend1 = new String[(int) (0)];
java.util.Arrays.fill(_legend1,"");
RDebugUtils.currentLine=2883602;
 //BA.debugLineNum = 2883602;BA.debugLine="Dim maxSales1 As Int = 0";
_maxsales1 = (int) (0);
RDebugUtils.currentLine=2883603;
 //BA.debugLineNum = 2883603;BA.debugLine="Dim titleString1 As String = \"\"";
_titlestring1 = "";
RDebugUtils.currentLine=2883604;
 //BA.debugLineNum = 2883604;BA.debugLine="Dim comId1() As Int";
_comid1 = new int[(int) (0)];
;
RDebugUtils.currentLine=2883605;
 //BA.debugLineNum = 2883605;BA.debugLine="Private currentPage As Int = 1";
_currentpage = (int) (1);
RDebugUtils.currentLine=2883606;
 //BA.debugLineNum = 2883606;BA.debugLine="Private itemsPerPage As Int = 5";
_itemsperpage = (int) (5);
RDebugUtils.currentLine=2883607;
 //BA.debugLineNum = 2883607;BA.debugLine="Public btnNext As Button";
_btnnext = new anywheresoftware.b4a.objects.ButtonWrapper();
RDebugUtils.currentLine=2883608;
 //BA.debugLineNum = 2883608;BA.debugLine="Public btnBack As Button";
_btnback = new anywheresoftware.b4a.objects.ButtonWrapper();
RDebugUtils.currentLine=2883609;
 //BA.debugLineNum = 2883609;BA.debugLine="Public sortBtn1 As RadioButton";
_sortbtn1 = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper();
RDebugUtils.currentLine=2883610;
 //BA.debugLineNum = 2883610;BA.debugLine="Public sortBtn2 As RadioButton";
_sortbtn2 = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper();
RDebugUtils.currentLine=2883611;
 //BA.debugLineNum = 2883611;BA.debugLine="Public defBtn As RadioButton";
_defbtn = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper();
RDebugUtils.currentLine=2883612;
 //BA.debugLineNum = 2883612;BA.debugLine="Public sales1 As RadioButton";
_sales1 = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper();
RDebugUtils.currentLine=2883613;
 //BA.debugLineNum = 2883613;BA.debugLine="Public sales2 As RadioButton";
_sales2 = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper();
RDebugUtils.currentLine=2883614;
 //BA.debugLineNum = 2883614;BA.debugLine="Public sales3 As RadioButton";
_sales3 = new anywheresoftware.b4a.objects.CompoundButtonWrapper.RadioButtonWrapper();
RDebugUtils.currentLine=2883615;
 //BA.debugLineNum = 2883615;BA.debugLine="Dim layout As String = \"\"";
_layout = "";
RDebugUtils.currentLine=2883616;
 //BA.debugLineNum = 2883616;BA.debugLine="Private isFirstInit As Boolean = True";
_isfirstinit = __c.True;
RDebugUtils.currentLine=2883617;
 //BA.debugLineNum = 2883617;BA.debugLine="Dim sortMainpanel As Panel";
_sortmainpanel = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=2883618;
 //BA.debugLineNum = 2883618;BA.debugLine="Dim shownMainpanel As Panel";
_shownmainpanel = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=2883619;
 //BA.debugLineNum = 2883619;BA.debugLine="Dim showHideBtn As Button";
_showhidebtn = new anywheresoftware.b4a.objects.ButtonWrapper();
RDebugUtils.currentLine=2883620;
 //BA.debugLineNum = 2883620;BA.debugLine="End Sub";
return "";
}
public String  _drawgraph(b4a.example.bargraph __ref,anywheresoftware.b4a.objects.ActivityWrapper _active,anywheresoftware.b4a.objects.PanelWrapper _panel,int[] _sale1,int[] _sale2,int[] _sale3,String[] _product,int _maxsales,String _titlestring) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "drawgraph", false))
	 {return ((String) Debug.delegate(ba, "drawgraph", new Object[] {_active,_panel,_sale1,_sale2,_sale3,_product,_maxsales,_titlestring}));}
int _halfwidth = 0;
anywheresoftware.b4a.objects.drawable.ColorDrawable _cd = null;
anywheresoftware.b4a.objects.PanelWrapper _activitypanel = null;
int _alignleftcenter = 0;
int _aligntopcenter = 0;
anywheresoftware.b4a.objects.LabelWrapper _title = null;
anywheresoftware.b4a.objects.drawable.CanvasWrapper _graphcanvas = null;
int _maxsale = 0;
anywheresoftware.b4a.objects.drawable.CanvasWrapper _cv = null;
int _totalproducts = 0;
int _startindex = 0;
int _endindex = 0;
int _barsperproduct = 0;
int _totalbars = 0;
int _gap = 0;
int _productgap = 0;
int _padding = 0;
int _availablewidth = 0;
int _barwidth = 0;
int _xstart = 0;
int _i = 0;
int _xpos = 0;
int[] _salevalues = null;
int _indexoffset = 0;
int _j = 0;
int _sale = 0;
int _barheight = 0;
int _xbar = 0;
anywheresoftware.b4a.objects.drawable.CanvasWrapper.RectWrapper _r = null;
int _fontsize = 0;
anywheresoftware.b4a.objects.LabelWrapper _productlabel = null;
int _productlabely = 0;
int _productlabelx = 0;
int _productlabelwidth = 0;
int _numlabels = 0;
int _labelvalue = 0;
int _labelypos = 0;
anywheresoftware.b4a.objects.LabelWrapper _yaxislabel = null;
int _buttonwidth = 0;
int _buttonheight = 0;
anywheresoftware.b4a.objects.PanelWrapper _btnmainpanel = null;
anywheresoftware.b4a.objects.PanelWrapper _paginationpanel = null;
anywheresoftware.b4a.objects.drawable.ColorDrawable _cdback = null;
anywheresoftware.b4a.objects.drawable.ColorDrawable _cdnext = null;
anywheresoftware.b4a.objects.LabelWrapper _paginationlabel = null;
RDebugUtils.currentLine=3014656;
 //BA.debugLineNum = 3014656;BA.debugLine="Public Sub DrawGraph(Active As Activity, panel As";
RDebugUtils.currentLine=3014657;
 //BA.debugLineNum = 3014657;BA.debugLine="Try";
try {RDebugUtils.currentLine=3014658;
 //BA.debugLineNum = 3014658;BA.debugLine="panel.Invalidate";
_panel.Invalidate();
RDebugUtils.currentLine=3014659;
 //BA.debugLineNum = 3014659;BA.debugLine="panel.RemoveAllViews";
_panel.RemoveAllViews();
RDebugUtils.currentLine=3014660;
 //BA.debugLineNum = 3014660;BA.debugLine="panel.Height = 530dip";
_panel.setHeight(__c.DipToCurrent((int) (530)));
RDebugUtils.currentLine=3014661;
 //BA.debugLineNum = 3014661;BA.debugLine="If panel.Width = 0 Then";
if (_panel.getWidth()==0) { 
RDebugUtils.currentLine=3014662;
 //BA.debugLineNum = 3014662;BA.debugLine="panel.Width = 800dip";
_panel.setWidth(__c.DipToCurrent((int) (800)));
 };
RDebugUtils.currentLine=3014664;
 //BA.debugLineNum = 3014664;BA.debugLine="Dim halfWidth As Int = panel.Width / 2";
_halfwidth = (int) (_panel.getWidth()/(double)2);
RDebugUtils.currentLine=3014665;
 //BA.debugLineNum = 3014665;BA.debugLine="If sortMainpanel.IsInitialized = False Then";
if (__ref._sortmainpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .IsInitialized()==__c.False) { 
RDebugUtils.currentLine=3014666;
 //BA.debugLineNum = 3014666;BA.debugLine="sortMainpanel.Initialize(\"\")";
__ref._sortmainpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .Initialize(ba,"");
 };
RDebugUtils.currentLine=3014668;
 //BA.debugLineNum = 3014668;BA.debugLine="sortMainpanel.Left = 0dip";
__ref._sortmainpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .setLeft(__c.DipToCurrent((int) (0)));
RDebugUtils.currentLine=3014669;
 //BA.debugLineNum = 3014669;BA.debugLine="sortMainpanel.Top = 5dip";
__ref._sortmainpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .setTop(__c.DipToCurrent((int) (5)));
RDebugUtils.currentLine=3014670;
 //BA.debugLineNum = 3014670;BA.debugLine="sortMainpanel.Width = halfWidth";
__ref._sortmainpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .setWidth(_halfwidth);
RDebugUtils.currentLine=3014671;
 //BA.debugLineNum = 3014671;BA.debugLine="sortMainpanel.Height = 120dip";
__ref._sortmainpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .setHeight(__c.DipToCurrent((int) (120)));
RDebugUtils.currentLine=3014672;
 //BA.debugLineNum = 3014672;BA.debugLine="panel.AddView(sortMainpanel, 0dip, 5dip, halfWid";
_panel.AddView((android.view.View)(__ref._sortmainpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getObject()),__c.DipToCurrent((int) (0)),__c.DipToCurrent((int) (5)),_halfwidth,__c.DipToCurrent((int) (120)));
RDebugUtils.currentLine=3014674;
 //BA.debugLineNum = 3014674;BA.debugLine="Dim cd As ColorDrawable";
_cd = new anywheresoftware.b4a.objects.drawable.ColorDrawable();
RDebugUtils.currentLine=3014675;
 //BA.debugLineNum = 3014675;BA.debugLine="cd.Initialize2(Colors.White, 5dip, 1dip, Colors.";
_cd.Initialize2(__c.Colors.White,__c.DipToCurrent((int) (5)),__c.DipToCurrent((int) (1)),__c.Colors.Black);
RDebugUtils.currentLine=3014676;
 //BA.debugLineNum = 3014676;BA.debugLine="panel.AddView(legendPanel, halfWidth +10dip, 10d";
_panel.AddView((android.view.View)(__ref._legendpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .getObject()),(int) (_halfwidth+__c.DipToCurrent((int) (10))),__c.DipToCurrent((int) (10)),(int) (_halfwidth-__c.DipToCurrent((int) (20))),__c.DipToCurrent((int) (45)));
RDebugUtils.currentLine=3014677;
 //BA.debugLineNum = 3014677;BA.debugLine="legendPanel.Background = cd";
__ref._legendpanel /*anywheresoftware.b4a.objects.PanelWrapper*/ .setBackground((android.graphics.drawable.Drawable)(_cd.getObject()));
RDebugUtils.currentLine=3014679;
 //BA.debugLineNum = 3014679;BA.debugLine="radioLabelLegendTitles.Initialize(\"radioLabelLeg";
__ref._radiolabellegendtitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .Initialize(ba,"radioLabelLegendTitles");
RDebugUtils.currentLine=3014680;
 //BA.debugLineNum = 3014680;BA.debugLine="radioLabelLegendTitles.Text = \"Shown Details\"";
__ref._radiolabellegendtitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setText(BA.ObjectToCharSequence("Shown Details"));
RDebugUtils.currentLine=3014681;
 //BA.debugLineNum = 3014681;BA.debugLine="radioLabelLegendTitles.TextSize = 12";
__ref._radiolabellegendtitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTextSize((float) (12));
RDebugUtils.currentLine=3014682;
 //BA.debugLineNum = 3014682;BA.debugLine="radioLabelLegendTitles.Typeface = Typeface.MONOS";
__ref._radiolabellegendtitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=3014683;
 //BA.debugLineNum = 3014683;BA.debugLine="radioLabelLegendTitles.Gravity = Gravity.CENTER";
__ref._radiolabellegendtitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setGravity(__c.Gravity.CENTER);
RDebugUtils.currentLine=3014684;
 //BA.debugLineNum = 3014684;BA.debugLine="radioLabelLegendTitles.TextColor = Colors.Black";
__ref._radiolabellegendtitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=3014685;
 //BA.debugLineNum = 3014685;BA.debugLine="radioLabelLegendTitles.Color = Colors.White";
__ref._radiolabellegendtitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .setColor(__c.Colors.White);
RDebugUtils.currentLine=3014686;
 //BA.debugLineNum = 3014686;BA.debugLine="panel.AddView(radioLabelLegendTitles, halfWidth+";
_panel.AddView((android.view.View)(__ref._radiolabellegendtitles /*anywheresoftware.b4a.objects.LabelWrapper*/ .getObject()),(int) (_halfwidth+__c.DipToCurrent((int) (15))),__c.DipToCurrent((int) (2.5)),__c.DipToCurrent((int) (100)),__c.DipToCurrent((int) (16)));
RDebugUtils.currentLine=3014689;
 //BA.debugLineNum = 3014689;BA.debugLine="Dim activityPanel As Panel";
_activitypanel = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=3014690;
 //BA.debugLineNum = 3014690;BA.debugLine="activityPanel.Initialize(\"activityPanel\")";
_activitypanel.Initialize(ba,"activityPanel");
RDebugUtils.currentLine=3014692;
 //BA.debugLineNum = 3014692;BA.debugLine="activityPanel.Width = 80%x";
_activitypanel.setWidth(__c.PerXToCurrent((float) (80),ba));
RDebugUtils.currentLine=3014693;
 //BA.debugLineNum = 3014693;BA.debugLine="If Active.Width > 800 Then";
if (_active.getWidth()>800) { 
RDebugUtils.currentLine=3014694;
 //BA.debugLineNum = 3014694;BA.debugLine="activityPanel.Width = 55%x";
_activitypanel.setWidth(__c.PerXToCurrent((float) (55),ba));
 };
RDebugUtils.currentLine=3014696;
 //BA.debugLineNum = 3014696;BA.debugLine="activityPanel.Height = 250dip";
_activitypanel.setHeight(__c.DipToCurrent((int) (250)));
RDebugUtils.currentLine=3014697;
 //BA.debugLineNum = 3014697;BA.debugLine="activityPanel.Color = Colors.ARGB(70, 211, 211,";
_activitypanel.setColor(__c.Colors.ARGB((int) (70),(int) (211),(int) (211),(int) (211)));
RDebugUtils.currentLine=3014699;
 //BA.debugLineNum = 3014699;BA.debugLine="Dim alignLeftCenter As Int = (Active.Width - act";
_alignleftcenter = (int) ((_active.getWidth()-_activitypanel.getWidth())/(double)2);
RDebugUtils.currentLine=3014700;
 //BA.debugLineNum = 3014700;BA.debugLine="Dim alignTopCenter As Int = (panel.Height - acti";
_aligntopcenter = (int) ((_panel.getHeight()-_activitypanel.getHeight())/(double)2-__c.DipToCurrent((int) (20)));
RDebugUtils.currentLine=3014702;
 //BA.debugLineNum = 3014702;BA.debugLine="Dim Title As Label";
_title = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=3014703;
 //BA.debugLineNum = 3014703;BA.debugLine="Title.Initialize(\"\")";
_title.Initialize(ba,"");
RDebugUtils.currentLine=3014704;
 //BA.debugLineNum = 3014704;BA.debugLine="Title.Text = TitleString";
_title.setText(BA.ObjectToCharSequence(_titlestring));
RDebugUtils.currentLine=3014705;
 //BA.debugLineNum = 3014705;BA.debugLine="Title.TextSize = 20";
_title.setTextSize((float) (20));
RDebugUtils.currentLine=3014706;
 //BA.debugLineNum = 3014706;BA.debugLine="Title.Typeface = Typeface.MONOSPACE";
_title.setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=3014707;
 //BA.debugLineNum = 3014707;BA.debugLine="Title.Gravity = Gravity.CENTER";
_title.setGravity(__c.Gravity.CENTER);
RDebugUtils.currentLine=3014708;
 //BA.debugLineNum = 3014708;BA.debugLine="Title.TextColor = Colors.Black";
_title.setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=3014709;
 //BA.debugLineNum = 3014709;BA.debugLine="panel.AddView(Title, 0, alignTopCenter / 2 +55di";
_panel.AddView((android.view.View)(_title.getObject()),(int) (0),(int) (_aligntopcenter/(double)2+__c.DipToCurrent((int) (55))),_panel.getWidth(),__c.DipToCurrent((int) (30)));
RDebugUtils.currentLine=3014711;
 //BA.debugLineNum = 3014711;BA.debugLine="panel.AddView(activityPanel, alignLeftCenter, al";
_panel.AddView((android.view.View)(_activitypanel.getObject()),_alignleftcenter,(int) (_aligntopcenter+(_aligntopcenter/(double)4)),_activitypanel.getWidth(),_activitypanel.getHeight());
RDebugUtils.currentLine=3014713;
 //BA.debugLineNum = 3014713;BA.debugLine="Dim graphCanvas As Canvas";
_graphcanvas = new anywheresoftware.b4a.objects.drawable.CanvasWrapper();
RDebugUtils.currentLine=3014714;
 //BA.debugLineNum = 3014714;BA.debugLine="graphCanvas.Initialize(activityPanel)";
_graphcanvas.Initialize((android.view.View)(_activitypanel.getObject()));
RDebugUtils.currentLine=3014716;
 //BA.debugLineNum = 3014716;BA.debugLine="Dim maxSale As Int = maxSales * 1.2";
_maxsale = (int) (_maxsales*1.2);
RDebugUtils.currentLine=3014717;
 //BA.debugLineNum = 3014717;BA.debugLine="Dim cv As Canvas";
_cv = new anywheresoftware.b4a.objects.drawable.CanvasWrapper();
RDebugUtils.currentLine=3014718;
 //BA.debugLineNum = 3014718;BA.debugLine="cv.Initialize(panel)";
_cv.Initialize((android.view.View)(_panel.getObject()));
RDebugUtils.currentLine=3014720;
 //BA.debugLineNum = 3014720;BA.debugLine="Dim totalProducts As Int = sale1.Length";
_totalproducts = _sale1.length;
RDebugUtils.currentLine=3014721;
 //BA.debugLineNum = 3014721;BA.debugLine="Dim startIndex As Int = (currentPage - 1) * item";
_startindex = (int) ((__ref._currentpage /*int*/ -1)*__ref._itemsperpage /*int*/ );
RDebugUtils.currentLine=3014722;
 //BA.debugLineNum = 3014722;BA.debugLine="Dim endIndex As Int = Min(startIndex + itemsPerP";
_endindex = (int) (__c.Min(_startindex+__ref._itemsperpage /*int*/ -1,_totalproducts-1));
RDebugUtils.currentLine=3014723;
 //BA.debugLineNum = 3014723;BA.debugLine="Dim barsPerProduct As Int = 3";
_barsperproduct = (int) (3);
RDebugUtils.currentLine=3014724;
 //BA.debugLineNum = 3014724;BA.debugLine="Dim totalBars As Int = (endIndex - startIndex +";
_totalbars = (int) ((_endindex-_startindex+1)*_barsperproduct);
RDebugUtils.currentLine=3014725;
 //BA.debugLineNum = 3014725;BA.debugLine="Dim gap As Int = 5dip";
_gap = __c.DipToCurrent((int) (5));
RDebugUtils.currentLine=3014726;
 //BA.debugLineNum = 3014726;BA.debugLine="Dim productGap As Int = 0dip";
_productgap = __c.DipToCurrent((int) (0));
RDebugUtils.currentLine=3014727;
 //BA.debugLineNum = 3014727;BA.debugLine="Dim padding As Int = 10dip";
_padding = __c.DipToCurrent((int) (10));
RDebugUtils.currentLine=3014729;
 //BA.debugLineNum = 3014729;BA.debugLine="Dim availableWidth As Int = activityPanel.Width";
_availablewidth = (int) (_activitypanel.getWidth()-(_padding*2)-(((_endindex-_startindex+1)-1)*_productgap)-((_totalbars-(_endindex-_startindex+1))*_gap));
RDebugUtils.currentLine=3014730;
 //BA.debugLineNum = 3014730;BA.debugLine="Dim barWidth As Int = availableWidth / totalBars";
_barwidth = (int) (_availablewidth/(double)_totalbars);
RDebugUtils.currentLine=3014731;
 //BA.debugLineNum = 3014731;BA.debugLine="Dim xStart As Int = padding";
_xstart = _padding;
RDebugUtils.currentLine=3014733;
 //BA.debugLineNum = 3014733;BA.debugLine="For i = startIndex To endIndex";
{
final int step64 = 1;
final int limit64 = _endindex;
_i = _startindex ;
for (;_i <= limit64 ;_i = _i + step64 ) {
RDebugUtils.currentLine=3014734;
 //BA.debugLineNum = 3014734;BA.debugLine="Dim xPos As Int = xStart + (i - startIndex) * (";
_xpos = (int) (_xstart+(_i-_startindex)*(_barsperproduct*(_barwidth+_gap)+_productgap));
RDebugUtils.currentLine=3014735;
 //BA.debugLineNum = 3014735;BA.debugLine="Dim saleValues() As Int = Array As Int(sale1(i)";
_salevalues = new int[]{_sale1[_i],_sale2[_i],_sale3[_i]};
RDebugUtils.currentLine=3014736;
 //BA.debugLineNum = 3014736;BA.debugLine="Dim indexOffset As Int = 0";
_indexoffset = (int) (0);
RDebugUtils.currentLine=3014738;
 //BA.debugLineNum = 3014738;BA.debugLine="For j = 0 To barsPerProduct - 1";
{
final int step68 = 1;
final int limit68 = (int) (_barsperproduct-1);
_j = (int) (0) ;
for (;_j <= limit68 ;_j = _j + step68 ) {
RDebugUtils.currentLine=3014739;
 //BA.debugLineNum = 3014739;BA.debugLine="If j < checkedSales.Length And checkedSales(j)";
if (_j<__ref._checkedsales /*boolean[]*/ .length && __ref._checkedsales /*boolean[]*/ [_j]) { 
RDebugUtils.currentLine=3014740;
 //BA.debugLineNum = 3014740;BA.debugLine="Dim sale As Int = saleValues(j)";
_sale = _salevalues[_j];
RDebugUtils.currentLine=3014741;
 //BA.debugLineNum = 3014741;BA.debugLine="Dim barHeight As Int = (sale / maxSale) * (ac";
_barheight = (int) ((_sale/(double)_maxsale)*(_activitypanel.getHeight()));
RDebugUtils.currentLine=3014742;
 //BA.debugLineNum = 3014742;BA.debugLine="Dim xBar As Int = xPos + indexOffset * barWid";
_xbar = (int) (_xpos+_indexoffset*_barwidth);
RDebugUtils.currentLine=3014744;
 //BA.debugLineNum = 3014744;BA.debugLine="Dim r As Rect";
_r = new anywheresoftware.b4a.objects.drawable.CanvasWrapper.RectWrapper();
RDebugUtils.currentLine=3014745;
 //BA.debugLineNum = 3014745;BA.debugLine="r.Initialize(xBar, activityPanel.Height - bar";
_r.Initialize(_xbar,(int) (_activitypanel.getHeight()-_barheight),(int) (_xbar+_barwidth),_activitypanel.getHeight());
RDebugUtils.currentLine=3014746;
 //BA.debugLineNum = 3014746;BA.debugLine="graphCanvas.DrawRect(r, color(j), True, 2dip)";
_graphcanvas.DrawRect((android.graphics.Rect)(_r.getObject()),__ref._color /*int[]*/ [_j],__c.True,(float) (__c.DipToCurrent((int) (2))));
RDebugUtils.currentLine=3014748;
 //BA.debugLineNum = 3014748;BA.debugLine="Dim fontSize As Int = 8";
_fontsize = (int) (8);
RDebugUtils.currentLine=3014749;
 //BA.debugLineNum = 3014749;BA.debugLine="If Active.Width > 800 Then";
if (_active.getWidth()>800) { 
RDebugUtils.currentLine=3014750;
 //BA.debugLineNum = 3014750;BA.debugLine="fontSize = 10";
_fontsize = (int) (10);
 };
RDebugUtils.currentLine=3014752;
 //BA.debugLineNum = 3014752;BA.debugLine="graphCanvas.DrawText(FormatNumberWithSuffix(s";
_graphcanvas.DrawText(ba,__ref._formatnumberwithsuffix /*String*/ (null,_sale),(float) (_xbar+(_barwidth/(double)2)),(float) (_activitypanel.getHeight()-_barheight-__c.DipToCurrent((int) (5))),__c.Typeface.MONOSPACE,(float) (_fontsize),__c.Colors.Black,BA.getEnumFromString(android.graphics.Paint.Align.class,"CENTER"));
RDebugUtils.currentLine=3014753;
 //BA.debugLineNum = 3014753;BA.debugLine="indexOffset = indexOffset + 1";
_indexoffset = (int) (_indexoffset+1);
 };
 }
};
RDebugUtils.currentLine=3014757;
 //BA.debugLineNum = 3014757;BA.debugLine="Dim productLabel As Label";
_productlabel = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=3014758;
 //BA.debugLineNum = 3014758;BA.debugLine="productLabel.Initialize(\"productLabel\")";
_productlabel.Initialize(ba,"productLabel");
RDebugUtils.currentLine=3014759;
 //BA.debugLineNum = 3014759;BA.debugLine="productLabel.Text = product(i)";
_productlabel.setText(BA.ObjectToCharSequence(_product[_i]));
RDebugUtils.currentLine=3014760;
 //BA.debugLineNum = 3014760;BA.debugLine="productLabel.Typeface = Typeface.MONOSPACE";
_productlabel.setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=3014761;
 //BA.debugLineNum = 3014761;BA.debugLine="productLabel.TextSize = 12";
_productlabel.setTextSize((float) (12));
RDebugUtils.currentLine=3014762;
 //BA.debugLineNum = 3014762;BA.debugLine="productLabel.Tag = comId1(i)";
_productlabel.setTag((Object)(__ref._comid1 /*int[]*/ [_i]));
RDebugUtils.currentLine=3014763;
 //BA.debugLineNum = 3014763;BA.debugLine="productLabel.TextColor = Colors.Black";
_productlabel.setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=3014764;
 //BA.debugLineNum = 3014764;BA.debugLine="productLabel.Gravity = Gravity.CENTER";
_productlabel.setGravity(__c.Gravity.CENTER);
RDebugUtils.currentLine=3014765;
 //BA.debugLineNum = 3014765;BA.debugLine="Dim productLabelY As Int = activityPanel.Height";
_productlabely = (int) (_activitypanel.getHeight()+_aligntopcenter+__c.DipToCurrent((int) (10)));
RDebugUtils.currentLine=3014766;
 //BA.debugLineNum = 3014766;BA.debugLine="Dim productLabelX As Int = alignLeftCenter";
_productlabelx = _alignleftcenter;
RDebugUtils.currentLine=3014767;
 //BA.debugLineNum = 3014767;BA.debugLine="Dim productLabelWidth As Int = (activityPanel.W";
_productlabelwidth = (int) ((_activitypanel.getWidth()/(double)_totalproducts)-(_padding+_gap));
RDebugUtils.currentLine=3014768;
 //BA.debugLineNum = 3014768;BA.debugLine="panel.AddView(productLabel, xPos + productLabel";
_panel.AddView((android.view.View)(_productlabel.getObject()),(int) (_xpos+_productlabelx),(int) (_productlabely+__c.DipToCurrent((int) (20))),_productlabelwidth,__c.DipToCurrent((int) (30)));
 }
};
RDebugUtils.currentLine=3014771;
 //BA.debugLineNum = 3014771;BA.debugLine="Dim numLabels As Int = 10";
_numlabels = (int) (10);
RDebugUtils.currentLine=3014772;
 //BA.debugLineNum = 3014772;BA.debugLine="For i = 0 To numLabels";
{
final int step98 = 1;
final int limit98 = _numlabels;
_i = (int) (0) ;
for (;_i <= limit98 ;_i = _i + step98 ) {
RDebugUtils.currentLine=3014773;
 //BA.debugLineNum = 3014773;BA.debugLine="Dim labelValue As Int = Round((maxSale / numLab";
_labelvalue = (int) (__c.Round((_maxsale/(double)_numlabels)*_i));
RDebugUtils.currentLine=3014774;
 //BA.debugLineNum = 3014774;BA.debugLine="Dim labelYPos As Int = activityPanel.Height - (";
_labelypos = (int) (_activitypanel.getHeight()-((_labelvalue/(double)_maxsale)*_activitypanel.getHeight()));
RDebugUtils.currentLine=3014776;
 //BA.debugLineNum = 3014776;BA.debugLine="Dim yAxisLabel As Label";
_yaxislabel = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=3014777;
 //BA.debugLineNum = 3014777;BA.debugLine="yAxisLabel.Initialize(\"\")";
_yaxislabel.Initialize(ba,"");
RDebugUtils.currentLine=3014778;
 //BA.debugLineNum = 3014778;BA.debugLine="yAxisLabel.Text = FormatNumberWithLabel(labelVa";
_yaxislabel.setText(BA.ObjectToCharSequence(__ref._formatnumberwithlabel /*String*/ (null,_labelvalue)));
RDebugUtils.currentLine=3014779;
 //BA.debugLineNum = 3014779;BA.debugLine="yAxisLabel.TextSize = 10";
_yaxislabel.setTextSize((float) (10));
RDebugUtils.currentLine=3014780;
 //BA.debugLineNum = 3014780;BA.debugLine="yAxisLabel.Typeface = Typeface.MONOSPACE";
_yaxislabel.setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=3014781;
 //BA.debugLineNum = 3014781;BA.debugLine="yAxisLabel.TextColor = Colors.Black";
_yaxislabel.setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=3014782;
 //BA.debugLineNum = 3014782;BA.debugLine="yAxisLabel.Gravity = Gravity.RIGHT";
_yaxislabel.setGravity(__c.Gravity.RIGHT);
RDebugUtils.currentLine=3014784;
 //BA.debugLineNum = 3014784;BA.debugLine="panel.AddView(yAxisLabel, alignLeftCenter - 40d";
_panel.AddView((android.view.View)(_yaxislabel.getObject()),(int) (_alignleftcenter-__c.DipToCurrent((int) (40))),(int) (_activitypanel.getTop()+_labelypos-__c.DipToCurrent((int) (10))),__c.DipToCurrent((int) (30)),__c.DipToCurrent((int) (15)));
 }
};
RDebugUtils.currentLine=3014786;
 //BA.debugLineNum = 3014786;BA.debugLine="btnBack.Enabled = currentPage > 1";
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setEnabled(__ref._currentpage /*int*/ >1);
RDebugUtils.currentLine=3014787;
 //BA.debugLineNum = 3014787;BA.debugLine="btnNext.Enabled = (currentPage * itemsPerPage) <";
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setEnabled((__ref._currentpage /*int*/ *__ref._itemsperpage /*int*/ )<_sale1.length);
RDebugUtils.currentLine=3014790;
 //BA.debugLineNum = 3014790;BA.debugLine="Dim buttonWidth As Int = 50dip";
_buttonwidth = __c.DipToCurrent((int) (50));
RDebugUtils.currentLine=3014791;
 //BA.debugLineNum = 3014791;BA.debugLine="Dim buttonHeight As Int = 40dip";
_buttonheight = __c.DipToCurrent((int) (40));
RDebugUtils.currentLine=3014793;
 //BA.debugLineNum = 3014793;BA.debugLine="Dim btnMainPanel As Panel";
_btnmainpanel = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=3014794;
 //BA.debugLineNum = 3014794;BA.debugLine="btnMainPanel.Initialize(\"\")";
_btnmainpanel.Initialize(ba,"");
RDebugUtils.currentLine=3014795;
 //BA.debugLineNum = 3014795;BA.debugLine="Log($\"alignTopCenter:${alignTopCenter}\"$)";
__c.LogImpl("23014795",("alignTopCenter:"+__c.SmartStringFormatter("",(Object)(_aligntopcenter))+""),0);
RDebugUtils.currentLine=3014796;
 //BA.debugLineNum = 3014796;BA.debugLine="panel.AddView(btnMainPanel,alignLeftCenter,panel";
_panel.AddView((android.view.View)(_btnmainpanel.getObject()),_alignleftcenter,(int) (_panel.getHeight()-((_aligntopcenter/(double)2)+__c.DipToCurrent((int) (20)))),_activitypanel.getWidth(),__c.DipToCurrent((int) (50)));
RDebugUtils.currentLine=3014798;
 //BA.debugLineNum = 3014798;BA.debugLine="Dim paginationPanel As Panel";
_paginationpanel = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=3014799;
 //BA.debugLineNum = 3014799;BA.debugLine="paginationPanel.Initialize(\"\")";
_paginationpanel.Initialize(ba,"");
RDebugUtils.currentLine=3014800;
 //BA.debugLineNum = 3014800;BA.debugLine="btnMainPanel.AddView(paginationPanel,0,0,btnMain";
_btnmainpanel.AddView((android.view.View)(_paginationpanel.getObject()),(int) (0),(int) (0),(int) (_btnmainpanel.getWidth()-__c.DipToCurrent((int) (150))),_btnmainpanel.getHeight());
RDebugUtils.currentLine=3014804;
 //BA.debugLineNum = 3014804;BA.debugLine="If btnBack.Parent <> Null Then btnBack.RemoveVie";
if (__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .getParent()!= null) { 
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .RemoveView();};
RDebugUtils.currentLine=3014805;
 //BA.debugLineNum = 3014805;BA.debugLine="If btnNext.Parent <> Null Then btnNext.RemoveVie";
if (__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .getParent()!= null) { 
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .RemoveView();};
RDebugUtils.currentLine=3014808;
 //BA.debugLineNum = 3014808;BA.debugLine="btnBack.Text = \"<\"";
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setText(BA.ObjectToCharSequence("<"));
RDebugUtils.currentLine=3014809;
 //BA.debugLineNum = 3014809;BA.debugLine="btnBack.TextSize = 14";
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setTextSize((float) (14));
RDebugUtils.currentLine=3014810;
 //BA.debugLineNum = 3014810;BA.debugLine="btnBack.Typeface = Typeface.MONOSPACE";
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=3014811;
 //BA.debugLineNum = 3014811;BA.debugLine="btnBack.TextColor = Colors.White";
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setTextColor(__c.Colors.White);
RDebugUtils.currentLine=3014812;
 //BA.debugLineNum = 3014812;BA.debugLine="Dim cdBack As ColorDrawable";
_cdback = new anywheresoftware.b4a.objects.drawable.ColorDrawable();
RDebugUtils.currentLine=3014813;
 //BA.debugLineNum = 3014813;BA.debugLine="cdBack.Initialize2(Colors.RGB(61, 12, 2), 10dip,";
_cdback.Initialize2(__c.Colors.RGB((int) (61),(int) (12),(int) (2)),__c.DipToCurrent((int) (10)),__c.DipToCurrent((int) (2)),__c.Colors.Black);
RDebugUtils.currentLine=3014814;
 //BA.debugLineNum = 3014814;BA.debugLine="btnBack.Background = cdBack";
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setBackground((android.graphics.drawable.Drawable)(_cdback.getObject()));
RDebugUtils.currentLine=3014817;
 //BA.debugLineNum = 3014817;BA.debugLine="btnNext.Text = \">\"";
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setText(BA.ObjectToCharSequence(">"));
RDebugUtils.currentLine=3014818;
 //BA.debugLineNum = 3014818;BA.debugLine="btnNext.TextSize = 14";
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setTextSize((float) (14));
RDebugUtils.currentLine=3014819;
 //BA.debugLineNum = 3014819;BA.debugLine="btnNext.Typeface = Typeface.MONOSPACE";
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=3014820;
 //BA.debugLineNum = 3014820;BA.debugLine="btnNext.TextColor = Colors.White";
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setTextColor(__c.Colors.White);
RDebugUtils.currentLine=3014821;
 //BA.debugLineNum = 3014821;BA.debugLine="Dim cdNext As ColorDrawable";
_cdnext = new anywheresoftware.b4a.objects.drawable.ColorDrawable();
RDebugUtils.currentLine=3014822;
 //BA.debugLineNum = 3014822;BA.debugLine="cdNext.Initialize2(Colors.RGB(185, 46, 52), 10di";
_cdnext.Initialize2(__c.Colors.RGB((int) (185),(int) (46),(int) (52)),__c.DipToCurrent((int) (10)),__c.DipToCurrent((int) (2)),__c.Colors.Black);
RDebugUtils.currentLine=3014823;
 //BA.debugLineNum = 3014823;BA.debugLine="btnNext.Background = cdNext";
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setBackground((android.graphics.drawable.Drawable)(_cdnext.getObject()));
RDebugUtils.currentLine=3014825;
 //BA.debugLineNum = 3014825;BA.debugLine="Dim paginationLabel As Label";
_paginationlabel = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=3014826;
 //BA.debugLineNum = 3014826;BA.debugLine="paginationLabel.Initialize(\"\")";
_paginationlabel.Initialize(ba,"");
RDebugUtils.currentLine=3014827;
 //BA.debugLineNum = 3014827;BA.debugLine="paginationLabel.Text = $\"Page 1 out of 1\"$";
_paginationlabel.setText(BA.ObjectToCharSequence(("Page 1 out of 1")));
RDebugUtils.currentLine=3014828;
 //BA.debugLineNum = 3014828;BA.debugLine="paginationLabel.Gravity = Gravity.CENTER";
_paginationlabel.setGravity(__c.Gravity.CENTER);
RDebugUtils.currentLine=3014829;
 //BA.debugLineNum = 3014829;BA.debugLine="paginationLabel.Typeface = Typeface.MONOSPACE";
_paginationlabel.setTypeface(__c.Typeface.MONOSPACE);
RDebugUtils.currentLine=3014830;
 //BA.debugLineNum = 3014830;BA.debugLine="paginationPanel.AddView(paginationLabel,buttonWi";
_paginationpanel.AddView((android.view.View)(_paginationlabel.getObject()),_buttonwidth,(int) (0),(int) (_paginationpanel.getWidth()-(_buttonwidth*2)),_paginationpanel.getHeight());
RDebugUtils.currentLine=3014832;
 //BA.debugLineNum = 3014832;BA.debugLine="Dim buttonWidth As Int = 50dip";
_buttonwidth = __c.DipToCurrent((int) (50));
RDebugUtils.currentLine=3014833;
 //BA.debugLineNum = 3014833;BA.debugLine="Dim buttonHeight As Int = 40dip";
_buttonheight = __c.DipToCurrent((int) (40));
RDebugUtils.currentLine=3014835;
 //BA.debugLineNum = 3014835;BA.debugLine="paginationPanel.AddView(btnBack, 0, (paginationP";
_paginationpanel.AddView((android.view.View)(__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .getObject()),(int) (0),(int) ((_paginationpanel.getHeight()-_buttonheight)/(double)2),_buttonwidth,_buttonheight);
RDebugUtils.currentLine=3014836;
 //BA.debugLineNum = 3014836;BA.debugLine="paginationPanel.AddView(btnNext, paginationPanel";
_paginationpanel.AddView((android.view.View)(__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .getObject()),(int) (_paginationpanel.getWidth()-_buttonwidth),(int) ((_paginationpanel.getHeight()-_buttonheight)/(double)2),_buttonwidth,_buttonheight);
RDebugUtils.currentLine=3014839;
 //BA.debugLineNum = 3014839;BA.debugLine="btnBack.Enabled = currentPage > 1";
__ref._btnback /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setEnabled(__ref._currentpage /*int*/ >1);
RDebugUtils.currentLine=3014840;
 //BA.debugLineNum = 3014840;BA.debugLine="btnNext.Enabled = (currentPage * itemsPerPage) <";
__ref._btnnext /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setEnabled((__ref._currentpage /*int*/ *__ref._itemsperpage /*int*/ )<_sale1.length);
RDebugUtils.currentLine=3014842;
 //BA.debugLineNum = 3014842;BA.debugLine="showHideBtn.Initialize(\"\")";
__ref._showhidebtn /*anywheresoftware.b4a.objects.ButtonWrapper*/ .Initialize(ba,"");
RDebugUtils.currentLine=3014843;
 //BA.debugLineNum = 3014843;BA.debugLine="showHideBtn.Text = $\"Show Details\"$";
__ref._showhidebtn /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setText(BA.ObjectToCharSequence(("Show Details")));
RDebugUtils.currentLine=3014844;
 //BA.debugLineNum = 3014844;BA.debugLine="showHideBtn.TextColor = Colors.White";
__ref._showhidebtn /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setTextColor(__c.Colors.White);
RDebugUtils.currentLine=3014845;
 //BA.debugLineNum = 3014845;BA.debugLine="btnMainPanel.AddView(showHideBtn,paginationPanel";
_btnmainpanel.AddView((android.view.View)(__ref._showhidebtn /*anywheresoftware.b4a.objects.ButtonWrapper*/ .getObject()),(int) (_paginationpanel.getWidth()+__c.DipToCurrent((int) (5))),__c.DipToCurrent((int) (5)),(int) ((_btnmainpanel.getWidth()-_paginationpanel.getWidth())-__c.DipToCurrent((int) (10))),_buttonheight);
RDebugUtils.currentLine=3014847;
 //BA.debugLineNum = 3014847;BA.debugLine="showHideBtn.Width = (btnMainPanel.Width-paginati";
__ref._showhidebtn /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setWidth((int) ((_btnmainpanel.getWidth()-_paginationpanel.getWidth())-__c.DipToCurrent((int) (10))));
RDebugUtils.currentLine=3014849;
 //BA.debugLineNum = 3014849;BA.debugLine="Dim cdBack As ColorDrawable";
_cdback = new anywheresoftware.b4a.objects.drawable.ColorDrawable();
RDebugUtils.currentLine=3014850;
 //BA.debugLineNum = 3014850;BA.debugLine="cdBack.Initialize2(Colors.RGB(61, 12, 2), 10dip,";
_cdback.Initialize2(__c.Colors.RGB((int) (61),(int) (12),(int) (2)),__c.DipToCurrent((int) (10)),__c.DipToCurrent((int) (2)),__c.Colors.Black);
RDebugUtils.currentLine=3014851;
 //BA.debugLineNum = 3014851;BA.debugLine="showHideBtn.Background = cdBack";
__ref._showhidebtn /*anywheresoftware.b4a.objects.ButtonWrapper*/ .setBackground((android.graphics.drawable.Drawable)(_cdback.getObject()));
 } 
       catch (Exception e158) {
			ba.setLastException(e158);RDebugUtils.currentLine=3014853;
 //BA.debugLineNum = 3014853;BA.debugLine="Log(LastException)";
__c.LogImpl("23014853",BA.ObjectToString(__c.LastException(ba)),0);
 };
RDebugUtils.currentLine=3014855;
 //BA.debugLineNum = 3014855;BA.debugLine="End Sub";
return "";
}
public String  _formatnumberwithsuffix(b4a.example.bargraph __ref,int _number) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "formatnumberwithsuffix", false))
	 {return ((String) Debug.delegate(ba, "formatnumberwithsuffix", new Object[] {_number}));}
RDebugUtils.currentLine=3342336;
 //BA.debugLineNum = 3342336;BA.debugLine="Sub FormatNumberWithSuffix(number As Int) As Strin";
RDebugUtils.currentLine=3342337;
 //BA.debugLineNum = 3342337;BA.debugLine="If number >= 1000000 Then";
if (_number>=1000000) { 
RDebugUtils.currentLine=3342338;
 //BA.debugLineNum = 3342338;BA.debugLine="Return NumberFormat(number / 1000000, 1, 1) & \"M";
if (true) return __c.NumberFormat(_number/(double)1000000,(int) (1),(int) (1))+"M";
 }else 
{RDebugUtils.currentLine=3342339;
 //BA.debugLineNum = 3342339;BA.debugLine="Else If number >= 1000 Then";
if (_number>=1000) { 
RDebugUtils.currentLine=3342340;
 //BA.debugLineNum = 3342340;BA.debugLine="Return NumberFormat(number / 1000, 1, 1) & \"k\"";
if (true) return __c.NumberFormat(_number/(double)1000,(int) (1),(int) (1))+"k";
 }else {
RDebugUtils.currentLine=3342342;
 //BA.debugLineNum = 3342342;BA.debugLine="Return NumberFormat(number, 1, 0)";
if (true) return __c.NumberFormat(_number,(int) (1),(int) (0));
 }}
;
RDebugUtils.currentLine=3342344;
 //BA.debugLineNum = 3342344;BA.debugLine="End Sub";
return "";
}
public String  _formatnumberwithlabel(b4a.example.bargraph __ref,int _number) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "formatnumberwithlabel", false))
	 {return ((String) Debug.delegate(ba, "formatnumberwithlabel", new Object[] {_number}));}
RDebugUtils.currentLine=3407872;
 //BA.debugLineNum = 3407872;BA.debugLine="Sub FormatNumberWithLabel(number As Int) As String";
RDebugUtils.currentLine=3407873;
 //BA.debugLineNum = 3407873;BA.debugLine="If number >= 1000000 Then";
if (_number>=1000000) { 
RDebugUtils.currentLine=3407874;
 //BA.debugLineNum = 3407874;BA.debugLine="Return Floor(number / 1000000) & \"M\"";
if (true) return BA.NumberToString(__c.Floor(_number/(double)1000000))+"M";
 }else 
{RDebugUtils.currentLine=3407875;
 //BA.debugLineNum = 3407875;BA.debugLine="Else If number >= 1000 Then";
if (_number>=1000) { 
RDebugUtils.currentLine=3407876;
 //BA.debugLineNum = 3407876;BA.debugLine="Return Floor(number / 1000) & \"k\"";
if (true) return BA.NumberToString(__c.Floor(_number/(double)1000))+"k";
 }else {
RDebugUtils.currentLine=3407878;
 //BA.debugLineNum = 3407878;BA.debugLine="Return number";
if (true) return BA.NumberToString(_number);
 }}
;
RDebugUtils.currentLine=3407880;
 //BA.debugLineNum = 3407880;BA.debugLine="End Sub";
return "";
}
public int  _getcurrentpage(b4a.example.bargraph __ref) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "getcurrentpage", false))
	 {return ((Integer) Debug.delegate(ba, "getcurrentpage", null));}
RDebugUtils.currentLine=3145728;
 //BA.debugLineNum = 3145728;BA.debugLine="Public Sub GetCurrentPage As Int";
RDebugUtils.currentLine=3145729;
 //BA.debugLineNum = 3145729;BA.debugLine="Return currentPage";
if (true) return __ref._currentpage /*int*/ ;
RDebugUtils.currentLine=3145730;
 //BA.debugLineNum = 3145730;BA.debugLine="End Sub";
return 0;
}
public String  _productlabel_click(b4a.example.bargraph __ref) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "productlabel_click", false))
	 {return ((String) Debug.delegate(ba, "productlabel_click", null));}
anywheresoftware.b4a.objects.LabelWrapper _clickedlabel = null;
int _selectedcompany = 0;
RDebugUtils.currentLine=3276800;
 //BA.debugLineNum = 3276800;BA.debugLine="Sub productLabel_Click";
RDebugUtils.currentLine=3276801;
 //BA.debugLineNum = 3276801;BA.debugLine="Dim clickedLabel As Label = Sender";
_clickedlabel = new anywheresoftware.b4a.objects.LabelWrapper();
_clickedlabel = (anywheresoftware.b4a.objects.LabelWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.LabelWrapper(), (android.widget.TextView)(__c.Sender(ba)));
RDebugUtils.currentLine=3276802;
 //BA.debugLineNum = 3276802;BA.debugLine="Dim selectedCompany As Int = clickedLabel.Tag";
_selectedcompany = (int)(BA.ObjectToNumber(_clickedlabel.getTag()));
RDebugUtils.currentLine=3276803;
 //BA.debugLineNum = 3276803;BA.debugLine="Log(\"Selected Company ID: \" & selectedCompany)";
__c.LogImpl("23276803","Selected Company ID: "+BA.NumberToString(_selectedcompany),0);
RDebugUtils.currentLine=3276804;
 //BA.debugLineNum = 3276804;BA.debugLine="Starter.company_selected = selectedCompany";
_starter._company_selected /*String*/  = BA.NumberToString(_selectedcompany);
RDebugUtils.currentLine=3276805;
 //BA.debugLineNum = 3276805;BA.debugLine="StartActivity(layout)";
__c.StartActivity(ba,(Object)(__ref._layout /*String*/ ));
RDebugUtils.currentLine=3276806;
 //BA.debugLineNum = 3276806;BA.debugLine="Active1.Finish";
__ref._active1 /*anywheresoftware.b4a.objects.ActivityWrapper*/ .Finish();
RDebugUtils.currentLine=3276807;
 //BA.debugLineNum = 3276807;BA.debugLine="End Sub";
return "";
}
public String  _setcurrentpage(b4a.example.bargraph __ref,int _page) throws Exception{
__ref = this;
RDebugUtils.currentModule="bargraph";
if (Debug.shouldDelegate(ba, "setcurrentpage", false))
	 {return ((String) Debug.delegate(ba, "setcurrentpage", new Object[] {_page}));}
RDebugUtils.currentLine=3211264;
 //BA.debugLineNum = 3211264;BA.debugLine="Public Sub SetCurrentPage(page As Int)";
RDebugUtils.currentLine=3211265;
 //BA.debugLineNum = 3211265;BA.debugLine="currentPage = page";
__ref._currentpage /*int*/  = _page;
RDebugUtils.currentLine=3211266;
 //BA.debugLineNum = 3211266;BA.debugLine="UpdateGraph";
__ref._updategraph /*String*/ (null);
RDebugUtils.currentLine=3211267;
 //BA.debugLineNum = 3211267;BA.debugLine="End Sub";
return "";
}
}